//! SigmaOS AI Kernel Autotuner Governor
//!
//! Sovereign autonomous kernel self-tuning system.
//! Inspired by:
//! - CachyOS BORE+EEVDF adaptive scheduler parameters
//! - Clear Linux kernel optimization profiles (performance, latency, power-save)
//! - Pop!_OS System76 power management (auto-switching between schedutil/performance)
//! - Intel Clear Containers auto-tuning
//! - Linux `schedtune` and `pm_qos` quality-of-service framework
//!
//! The AI Autotuner continuously monitors system metrics (CPU utilization, memory
//! pressure, I/O wait, network throughput) and adjusts kernel parameters to
//! optimize for the current workload profile without human intervention.

#![allow(dead_code)]

use std::collections::BTreeMap;
use std::string::String;
use std::vec::Vec;
use std::format;

// ─── Workload Profile ─────────────────────────────────────────────────────────

/// Detected system workload profile
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WorkloadProfile {
    /// Interactive desktop: low-latency, high-responsiveness
    Interactive,
    /// Server/batch: maximize throughput, tolerate higher latency
    ServerBatch,
    /// Gaming/Realtime: lowest possible scheduling latency
    Gaming,
    /// Power-save: extend battery life, reduce CPU frequency
    PowerSave,
    /// Compilation/build: sustained CPU-bound throughput
    Compilation,
    /// Network-intensive: I/O latency critical, CPU secondary
    NetworkIntensive,
    /// Mixed: balanced profile for general use
    Mixed,
}

impl WorkloadProfile {
    /// Returns a human-readable label for this profile
    pub fn label(&self) -> &'static str {
        match self {
            WorkloadProfile::Interactive => "Interactive Desktop",
            WorkloadProfile::ServerBatch => "Server / Batch",
            WorkloadProfile::Gaming => "Gaming / Realtime",
            WorkloadProfile::PowerSave => "Power Save",
            WorkloadProfile::Compilation => "Compilation / Build",
            WorkloadProfile::NetworkIntensive => "Network Intensive",
            WorkloadProfile::Mixed => "Mixed / Balanced",
        }
    }
}

// ─── System Metrics Snapshot ──────────────────────────────────────────────────

/// Real-time system metrics snapshot used by the Autotuner
#[derive(Debug, Clone)]
pub struct SystemMetricsSnapshot {
    /// CPU utilization percentage [0, 100]
    pub cpu_utilization_pct: f32,
    /// Memory pressure score [0.0, 1.0] (0 = no pressure, 1 = critical)
    pub memory_pressure: f32,
    /// I/O wait percentage [0, 100]
    pub io_wait_pct: f32,
    /// Network throughput in MB/s
    pub network_throughput_mbps: f32,
    /// Number of runnable tasks in scheduler queue
    pub runqueue_depth: u32,
    /// Average scheduling latency in microseconds
    pub avg_sched_latency_us: u64,
    /// Battery level percentage (None if AC-only)
    pub battery_pct: Option<f32>,
    /// Number of active CPU cores
    pub active_cpu_cores: u32,
    /// Timestamp of this snapshot (monotonic nanoseconds)
    pub timestamp_ns: u64,
}

impl SystemMetricsSnapshot {
    /// Create a baseline (idle system) metrics snapshot
    pub fn idle() -> Self {
        SystemMetricsSnapshot {
            cpu_utilization_pct: 2.0,
            memory_pressure: 0.05,
            io_wait_pct: 0.5,
            network_throughput_mbps: 0.1,
            runqueue_depth: 1,
            avg_sched_latency_us: 200,
            battery_pct: Some(100.0),
            active_cpu_cores: 4,
            timestamp_ns: 0,
        }
    }
}

// ─── Tunable Kernel Parameters ────────────────────────────────────────────────

/// A single tunable kernel parameter (sysctl equivalent)
#[derive(Debug, Clone)]
pub struct KernelTunable {
    /// Parameter name (like `kernel.sched_min_granularity_ns`)
    pub name: String,
    /// Current value
    pub current_value: i64,
    /// Minimum allowed value
    pub min_value: i64,
    /// Maximum allowed value
    pub max_value: i64,
    /// Description
    pub description: String,
}

impl KernelTunable {
    pub fn new(name: &str, current: i64, min: i64, max: i64, desc: &str) -> Self {
        KernelTunable {
            name: String::from(name),
            current_value: current,
            min_value: min,
            max_value: max,
            description: String::from(desc),
        }
    }

    /// Clamp a value within this tunable's valid range
    pub fn clamp(&self, value: i64) -> i64 {
        value.max(self.min_value).min(self.max_value)
    }
}

// ─── Optimization Recommendation ─────────────────────────────────────────────

/// An optimization recommendation generated by the Autotuner
#[derive(Debug, Clone)]
pub struct TuningRecommendation {
    /// Parameter name to tune
    pub parameter: String,
    /// Recommended new value
    pub new_value: i64,
    /// Previous value (for rollback)
    pub old_value: i64,
    /// Why this change is recommended
    pub rationale: String,
    /// Expected improvement (e.g. "-30% scheduling latency")
    pub expected_benefit: String,
    /// Confidence score [0.0, 1.0]
    pub confidence: f32,
}

impl TuningRecommendation {
    pub fn format(&self) -> String {
        format!(
            "[{:.0}% confidence] {}: {} → {} | {} | Benefit: {}",
            self.confidence * 100.0,
            self.parameter,
            self.old_value,
            self.new_value,
            self.rationale,
            self.expected_benefit
        )
    }
}

// ─── AI Kernel Autotuner ─────────────────────────────────────────────────────

/// SigmaOS AI Kernel Autotuner Governor
///
/// Monitors system metrics and autonomously generates tuning recommendations
/// for kernel scheduler, memory allocator, and network stack parameters.
/// Inspired by CachyOS power profiles, Clear Linux optimization, and
/// Pop!_OS System76 power management.
pub struct SigmaKernelAutotuner {
    /// All tunable kernel parameters
    pub tunables: BTreeMap<String, KernelTunable>,
    /// Metrics history (last N snapshots for trend analysis)
    pub metrics_history: Vec<SystemMetricsSnapshot>,
    /// Maximum history size
    pub history_capacity: usize,
    /// Currently detected workload profile
    pub current_profile: WorkloadProfile,
    /// Applied recommendations log
    pub applied_recommendations: Vec<TuningRecommendation>,
    /// Total number of automatic tuning operations performed
    pub tune_count: u64,
}

impl SigmaKernelAutotuner {
    /// Create a new Autotuner with default SigmaOS baseline parameters
    pub fn new() -> Self {
        let mut tunables: BTreeMap<String, KernelTunable> = BTreeMap::new();

        // Scheduler parameters (inspired by CachyOS BORE defaults)
        tunables.insert(
            String::from("kernel.sched_min_granularity_ns"),
            KernelTunable::new(
                "kernel.sched_min_granularity_ns",
                2_000_000,        // 2ms default
                100_000,          // 100µs min (gaming mode)
                20_000_000,       // 20ms max (batch mode)
                "Minimum scheduler preemption granularity (lower = more responsive)",
            ),
        );
        tunables.insert(
            String::from("kernel.sched_latency_ns"),
            KernelTunable::new(
                "kernel.sched_latency_ns",
                8_000_000,
                1_000_000,
                48_000_000,
                "Target scheduling period (CFS/EEVDF latency target)",
            ),
        );
        tunables.insert(
            String::from("kernel.sched_wakeup_granularity_ns"),
            KernelTunable::new(
                "kernel.sched_wakeup_granularity_ns",
                3_000_000,
                500_000,
                15_000_000,
                "Wakeup preemption granularity — lower boosts interactive tasks",
            ),
        );

        // Memory parameters (inspired by Clear Linux vm tunables)
        tunables.insert(
            String::from("vm.swappiness"),
            KernelTunable::new(
                "vm.swappiness",
                10,   // SigmaOS default: prefer RAM over swap
                0,
                200,
                "Swappiness: 0=prefer RAM, 200=aggressive swap",
            ),
        );
        tunables.insert(
            String::from("vm.dirty_ratio"),
            KernelTunable::new(
                "vm.dirty_ratio",
                20,
                5,
                80,
                "Max percentage of dirty pages before process is forced to write",
            ),
        );
        tunables.insert(
            String::from("vm.dirty_background_ratio"),
            KernelTunable::new(
                "vm.dirty_background_ratio",
                5,
                1,
                40,
                "Percentage of dirty pages to trigger background writeback",
            ),
        );
        tunables.insert(
            String::from("vm.vfs_cache_pressure"),
            KernelTunable::new(
                "vm.vfs_cache_pressure",
                50,
                1,
                1000,
                "Tendency to reclaim VFS cache memory (lower = cache more)",
            ),
        );

        // Network parameters (inspired by Linux tcp_bbr + Clear Linux net tuning)
        tunables.insert(
            String::from("net.core.somaxconn"),
            KernelTunable::new(
                "net.core.somaxconn",
                4096,
                128,
                65535,
                "Maximum socket connection backlog queue depth",
            ),
        );
        tunables.insert(
            String::from("net.ipv4.tcp_rmem_max"),
            KernelTunable::new(
                "net.ipv4.tcp_rmem_max",
                16_777_216,   // 16 MB
                4096,
                134_217_728,  // 128 MB
                "Maximum TCP receive buffer size",
            ),
        );
        tunables.insert(
            String::from("net.ipv4.tcp_wmem_max"),
            KernelTunable::new(
                "net.ipv4.tcp_wmem_max",
                16_777_216,
                4096,
                134_217_728,
                "Maximum TCP send buffer size",
            ),
        );

        SigmaKernelAutotuner {
            tunables,
            metrics_history: Vec::new(),
            history_capacity: 60,  // 60 snapshots = 1 minute at 1s intervals
            current_profile: WorkloadProfile::Mixed,
            applied_recommendations: Vec::new(),
            tune_count: 0,
        }
    }

    // ── Metrics Ingestion ─────────────────────────────────────────────────────

    /// Ingest a new metrics snapshot. Triggers workload re-classification.
    pub fn ingest_metrics(&mut self, snapshot: SystemMetricsSnapshot) {
        if self.metrics_history.len() >= self.history_capacity {
            self.metrics_history.remove(0);
        }
        self.metrics_history.push(snapshot.clone());
        self.current_profile = self.classify_workload(&snapshot);
    }

    // ── Workload Classification ───────────────────────────────────────────────

    /// AI-like workload classifier based on metric thresholds.
    ///
    /// Uses a simple rule-based decision tree (fast, zero-dependency).
    /// Can be extended to use a lookup table or lightweight NN in future.
    pub fn classify_workload(&self, m: &SystemMetricsSnapshot) -> WorkloadProfile {
        // Battery saving mode: low battery → power save regardless
        if let Some(battery) = m.battery_pct {
            if battery < 20.0 && m.cpu_utilization_pct < 30.0 {
                return WorkloadProfile::PowerSave;
            }
        }

        // Gaming/Realtime: very low latency required
        if m.avg_sched_latency_us < 500 && m.runqueue_depth <= 4 {
            return WorkloadProfile::Gaming;
        }

        // Compilation: sustained CPU saturation
        if m.cpu_utilization_pct > 85.0 && m.io_wait_pct < 10.0 {
            return WorkloadProfile::Compilation;
        }

        // Network intensive: high throughput, moderate CPU
        if m.network_throughput_mbps > 500.0 && m.cpu_utilization_pct < 60.0 {
            return WorkloadProfile::NetworkIntensive;
        }

        // Server batch: high utilization, many tasks queued
        if m.cpu_utilization_pct > 70.0 && m.runqueue_depth > 8 {
            return WorkloadProfile::ServerBatch;
        }

        // Memory pressure: mostly memory-bound
        if m.memory_pressure > 0.7 {
            return WorkloadProfile::ServerBatch;
        }

        // Interactive desktop: typical desktop workload
        if m.cpu_utilization_pct < 40.0 && m.runqueue_depth <= 6 {
            return WorkloadProfile::Interactive;
        }

        WorkloadProfile::Mixed
    }

    // ── Recommendation Generation ─────────────────────────────────────────────

    /// Generate tuning recommendations based on the current workload profile.
    ///
    /// Returns a list of recommended parameter changes.
    pub fn generate_recommendations(&self) -> Vec<TuningRecommendation> {
        let mut recs: Vec<TuningRecommendation> = Vec::new();

        match &self.current_profile {
            WorkloadProfile::Gaming => {
                recs.push(self.make_rec(
                    "kernel.sched_min_granularity_ns",
                    500_000,   // 0.5ms
                    0.95,
                    "Minimize scheduler granularity for sub-millisecond gaming latency",
                    "-75% scheduling jitter",
                ));
                recs.push(self.make_rec(
                    "kernel.sched_latency_ns",
                    2_000_000, // 2ms period
                    0.90,
                    "Reduce CFS/EEVDF latency target for realtime responsiveness",
                    "-60% wakeup latency",
                ));
                recs.push(self.make_rec(
                    "vm.swappiness",
                    1,
                    0.85,
                    "Near-zero swappiness: keep all gaming data in RAM",
                    "Eliminate swap-induced stuttering",
                ));
            }
            WorkloadProfile::Interactive => {
                recs.push(self.make_rec(
                    "kernel.sched_wakeup_granularity_ns",
                    1_000_000,
                    0.88,
                    "Faster wakeup preemption for interactive BORE boosting",
                    "+20% UI responsiveness",
                ));
                recs.push(self.make_rec(
                    "vm.swappiness",
                    5,
                    0.80,
                    "Low swappiness for responsive desktop feel",
                    "Reduce memory reclaim pauses",
                ));
                recs.push(self.make_rec(
                    "vm.vfs_cache_pressure",
                    30,
                    0.75,
                    "Retain VFS dentry/inode cache for fast file lookups",
                    "+15% filesystem access speed",
                ));
            }
            WorkloadProfile::ServerBatch => {
                recs.push(self.make_rec(
                    "kernel.sched_min_granularity_ns",
                    8_000_000,  // 8ms for batch
                    0.85,
                    "Increase scheduler granularity for throughput-oriented batch jobs",
                    "+20% CPU throughput",
                ));
                recs.push(self.make_rec(
                    "vm.dirty_ratio",
                    40,
                    0.80,
                    "Allow more dirty pages for bursty server I/O patterns",
                    "+25% disk I/O throughput",
                ));
                recs.push(self.make_rec(
                    "net.core.somaxconn",
                    32768,
                    0.90,
                    "Expand socket backlog for high-concurrency server workloads",
                    "Handle 8x more concurrent connections",
                ));
            }
            WorkloadProfile::Compilation => {
                recs.push(self.make_rec(
                    "kernel.sched_latency_ns",
                    20_000_000,  // 20ms period for build throughput
                    0.85,
                    "Maximize scheduler period for sustained compilation throughput",
                    "+15% compiler throughput",
                ));
                recs.push(self.make_rec(
                    "vm.dirty_background_ratio",
                    10,
                    0.78,
                    "More aggressive background writeback for artifact I/O",
                    "+10% build artifact write speed",
                ));
            }
            WorkloadProfile::PowerSave => {
                recs.push(self.make_rec(
                    "kernel.sched_min_granularity_ns",
                    10_000_000,  // 10ms for power save
                    0.90,
                    "Increase scheduler granularity to reduce CPU wake frequency",
                    "+30% battery life extension",
                ));
                recs.push(self.make_rec(
                    "vm.swappiness",
                    60,
                    0.82,
                    "Allow more aggressive memory swapping to reduce DRAM power",
                    "+15% power reduction",
                ));
            }
            WorkloadProfile::NetworkIntensive => {
                recs.push(self.make_rec(
                    "net.ipv4.tcp_rmem_max",
                    67_108_864,  // 64 MB
                    0.88,
                    "Maximize TCP receive buffer for high-throughput XDP networking",
                    "+40% network throughput",
                ));
                recs.push(self.make_rec(
                    "net.ipv4.tcp_wmem_max",
                    67_108_864,
                    0.88,
                    "Maximize TCP send buffer for XDP zero-copy pipeline",
                    "+40% send throughput",
                ));
            }
            WorkloadProfile::Mixed => {
                // Balanced: leave mostly at defaults, minor tweaks
                recs.push(self.make_rec(
                    "vm.swappiness",
                    10,
                    0.70,
                    "Balanced swappiness for mixed workload",
                    "Stable performance across workload types",
                ));
            }
        }

        recs
    }

    /// Apply all generated recommendations to the tunable parameters
    pub fn apply_recommendations(&mut self) -> Vec<TuningRecommendation> {
        let recs = self.generate_recommendations();
        for rec in &recs {
            if let Some(tunable) = self.tunables.get_mut(&rec.parameter) {
                tunable.current_value = tunable.clamp(rec.new_value);
            }
        }
        self.applied_recommendations.extend(recs.clone());
        self.tune_count += 1;
        recs
    }

    /// Helper: build a TuningRecommendation
    fn make_rec(
        &self,
        param: &str,
        new_value: i64,
        confidence: f32,
        rationale: &str,
        benefit: &str,
    ) -> TuningRecommendation {
        let old_value = self
            .tunables
            .get(param)
            .map(|t| t.current_value)
            .unwrap_or(0);
        TuningRecommendation {
            parameter: String::from(param),
            new_value,
            old_value,
            rationale: String::from(rationale),
            expected_benefit: String::from(benefit),
            confidence,
        }
    }

    // ── Status & Reporting ────────────────────────────────────────────────────

    /// Returns a formatted status report
    pub fn status_report(&self) -> String {
        let recs = self.generate_recommendations();
        let rec_summary: Vec<String> = recs.iter().map(|r| format!("  • {}", r.format())).collect();
        format!(
            "=== SigmaOS AI Kernel Autotuner ===\n\
             Profile: {} | {} tune operations | {} metrics snapshots\n\
             Recommendations ({}):\n{}",
            self.current_profile.label(),
            self.tune_count,
            self.metrics_history.len(),
            recs.len(),
            rec_summary.join("\n")
        )
    }

    /// Returns current value of a tunable
    pub fn get_tunable(&self, name: &str) -> Option<i64> {
        self.tunables.get(name).map(|t| t.current_value)
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod autotuner_tests {
    use super::*;

    fn gaming_metrics() -> SystemMetricsSnapshot {
        SystemMetricsSnapshot {
            cpu_utilization_pct: 35.0,
            memory_pressure: 0.3,
            io_wait_pct: 1.0,
            network_throughput_mbps: 10.0,
            runqueue_depth: 3,
            avg_sched_latency_us: 300,
            battery_pct: Some(80.0),
            active_cpu_cores: 8,
            timestamp_ns: 0,
        }
    }

    fn server_metrics() -> SystemMetricsSnapshot {
        SystemMetricsSnapshot {
            cpu_utilization_pct: 90.0,
            memory_pressure: 0.4,
            io_wait_pct: 5.0,
            network_throughput_mbps: 200.0,
            runqueue_depth: 20,
            avg_sched_latency_us: 5000,
            battery_pct: None,
            active_cpu_cores: 32,
            timestamp_ns: 0,
        }
    }

    fn power_save_metrics() -> SystemMetricsSnapshot {
        SystemMetricsSnapshot {
            cpu_utilization_pct: 15.0,
            memory_pressure: 0.1,
            io_wait_pct: 0.5,
            network_throughput_mbps: 1.0,
            runqueue_depth: 2,
            avg_sched_latency_us: 1000,
            battery_pct: Some(12.0),
            active_cpu_cores: 4,
            timestamp_ns: 0,
        }
    }

    #[test]
    fn test_classify_gaming() {
        let tuner = SigmaKernelAutotuner::new();
        let profile = tuner.classify_workload(&gaming_metrics());
        assert_eq!(profile, WorkloadProfile::Gaming);
    }

    #[test]
    fn test_classify_server() {
        let tuner = SigmaKernelAutotuner::new();
        let profile = tuner.classify_workload(&server_metrics());
        assert_eq!(profile, WorkloadProfile::ServerBatch);
    }

    #[test]
    fn test_classify_power_save() {
        let tuner = SigmaKernelAutotuner::new();
        let profile = tuner.classify_workload(&power_save_metrics());
        assert_eq!(profile, WorkloadProfile::PowerSave);
    }

    #[test]
    fn test_gaming_recommendations() {
        let mut tuner = SigmaKernelAutotuner::new();
        tuner.ingest_metrics(gaming_metrics());
        let recs = tuner.generate_recommendations();
        assert!(!recs.is_empty());
        let params: Vec<&str> = recs.iter().map(|r| r.parameter.as_str()).collect();
        assert!(params.contains(&"kernel.sched_min_granularity_ns"));
    }

    #[test]
    fn test_apply_recommendations_changes_tunables() {
        let mut tuner = SigmaKernelAutotuner::new();
        tuner.ingest_metrics(gaming_metrics());
        let old_val = tuner.get_tunable("kernel.sched_min_granularity_ns").unwrap();
        tuner.apply_recommendations();
        let new_val = tuner.get_tunable("kernel.sched_min_granularity_ns").unwrap();
        // Gaming mode should reduce granularity
        assert!(new_val <= old_val);
        assert_eq!(tuner.tune_count, 1);
    }

    #[test]
    fn test_metrics_history_capped() {
        let mut tuner = SigmaKernelAutotuner::new();
        for _ in 0..70 {
            tuner.ingest_metrics(SystemMetricsSnapshot::idle());
        }
        assert!(tuner.metrics_history.len() <= tuner.history_capacity);
    }

    #[test]
    fn test_status_report_format() {
        let mut tuner = SigmaKernelAutotuner::new();
        tuner.ingest_metrics(gaming_metrics());
        let report = tuner.status_report();
        assert!(report.contains("SigmaOS AI Kernel Autotuner"));
        assert!(report.contains("Gaming"));
    }

    #[test]
    fn test_tunable_clamping() {
        let mut tuner = SigmaKernelAutotuner::new();
        tuner.ingest_metrics(SystemMetricsSnapshot::idle());
        // Apply any recs — values should stay within tunable bounds
        tuner.apply_recommendations();
        for (name, tunable) in &tuner.tunables {
            assert!(
                tunable.current_value >= tunable.min_value,
                "tunable {} below min: {} < {}",
                name,
                tunable.current_value,
                tunable.min_value
            );
            assert!(
                tunable.current_value <= tunable.max_value,
                "tunable {} above max: {} > {}",
                name,
                tunable.current_value,
                tunable.max_value
            );
        }
    }
}
