GAME_ID = 'G01'
GAME_NAME = 'Strategic Sovereignty'
CATEGORY = 'Board Strategy'
VERSION = '1.3.0'
SIZE_KB = 1240
ICON = '♟️'
DESC = "Two-player strategy on an 8×8 board. Move pieces to capture the opponent's King."
AGE_RATING = 'G'
PIECES = {'K': '♔', 'Q': '♕', 'R': '♖', 'B': '♗', 'N': '♘', 'P': '♙', 'k': '♚', 'q': '♛', 'r': '♜', 'b': '♝', 'n': '♞', 'p': '♟'}
