[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sigmaos-core"
version = "4.2.0"
authors = [
  { name="Aaryan Singh Chauhan", email="contact@aaryan.com" },
]
description = "SigmaOS Kernel and Core userland ecosystem."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
    "psutil",
]

[project.scripts]
sigmaos = "sigma_cli:main"
