# sigma_build_graph.py
# SigmaOS: Sovereign Build Orchestrator

import os

def generate_makefile():
    print("Σ [BUILD]: Sequencing functional atoms for industrial compilation...")
    
    shards = [f for f in os.listdir('.') if f.endswith('.c') or f.endswith('.asm')]
    objects = [os.path.splitext(f)[0] + '.o' for f in shards]

    makefile_content = f"""
# Sovereign Master Makefile - Auto-Generated by SBG
CC=gcc
AS=nasm
CFLAGS=-ffreestanding -nostdlib -fno-stack-protector -I.
ASFLAGS=-f elf64

all: sigma_kernel

sigma_kernel: {' '.join(objects)}
\t$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
\t$(CC) $(CFLAGS) -c $< -o $@

%.o: %.asm
\t$(AS) $(ASFLAGS) $< -o $@

clean:
\trm -f *.o sigma_kernel
"""
    with open('Makefile_Sovereign', 'w') as f:
        f.write(makefile_content)
    
    print(f"Σ [BUILD]: Makefile generated. {len(shards)} shards integrated.")

if __name__ == "__main__":
    generate_makefile()
