//! # SigmaOS Netfilter / Packet Filtering Engine
//!
//! A SigmaOS-native packet filtering framework inspired by Linux netfilter/nftables
//! and BSD `pf` (Packet Filter).
//!
//! ## Architecture
//! ```text
//!  Incoming packet
//!       │
//!       ▼
//!  [PREROUTING chain]  ← DNAT, connection tracking
//!       │
//!       ├─(local destination?)─▶ [INPUT chain] ─▶ local process
//!       │
//!       └─(forward?)──────────▶ [FORWARD chain] ─▶ [POSTROUTING chain] ─▶ egress
//!
//!  Outgoing (locally-generated) packet
//!       │
//!       ▼
//!  [OUTPUT chain] ─▶ [POSTROUTING chain] ─▶ egress
//! ```
//!
//! ## Tables
//! | Table    | Chains                          | Purpose            |
//! |----------|---------------------------------|--------------------|
//! | filter   | INPUT, FORWARD, OUTPUT          | Packet filtering   |
//! | nat      | PREROUTING, OUTPUT, POSTROUTING | Address translation|
//! | mangle   | All five chains                 | Packet modification|
//!
//! ## Comparison with iptables/nftables/pf
//! | Feature         | iptables       | nftables       | pf             | SigmaOS        |
//! |-----------------|----------------|----------------|----------------|----------------|
//! | Rule language   | CLI flags      | nft syntax     | pf.conf        | Rust structs   |
//! | State tracking  | conntrack      | conntrack      | state tables   | Built-in       |
//! | Sets/maps       | ipset          | native         | tables         | `MatchSet`     |
//! | NAT             | MASQUERADE     | masquerade     | nat on if      | Stub           |

#![allow(dead_code)]
#![allow(unused_variables)]

use std::collections::HashMap;
use std::net::Ipv4Addr;
use std::vec::Vec;
use std::string::String;

// ── Packet representation ─────────────────────────────────────────────────────

/// IP protocol numbers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IpProto {
    Tcp,
    Udp,
    Icmp,
    Other(u8),
}

impl IpProto {
    pub fn from_u8(v: u8) -> Self {
        match v {
            6 => IpProto::Tcp,
            17 => IpProto::Udp,
            1 => IpProto::Icmp,
            n => IpProto::Other(n),
        }
    }
}

/// A simplified packet descriptor passed through the filter engine.
///
/// In a real kernel, this would be an `sk_buff` or mbuf pointer.
#[derive(Debug, Clone)]
pub struct Packet {
    /// Source IP address.
    pub src_ip: Ipv4Addr,
    /// Destination IP address.
    pub dst_ip: Ipv4Addr,
    /// Source port (0 for ICMP).
    pub src_port: u16,
    /// Destination port (0 for ICMP).
    pub dst_port: u16,
    /// IP protocol.
    pub proto: IpProto,
    /// Incoming interface name (e.g. "eth0").
    pub in_iface: String,
    /// Outgoing interface name (e.g. "eth0").
    pub out_iface: String,
    /// Packet payload length in bytes.
    pub len: u32,
    /// Marks set by earlier rules (for packet classification).
    pub mark: u32,
}

impl Packet {
    /// Create a TCP packet.
    pub fn tcp(src: Ipv4Addr, dst: Ipv4Addr, sport: u16, dport: u16) -> Self {
        Packet {
            src_ip: src,
            dst_ip: dst,
            src_port: sport,
            dst_port: dport,
            proto: IpProto::Tcp,
            in_iface: String::new(),
            out_iface: String::new(),
            len: 40,
            mark: 0,
        }
    }

    /// Create a UDP packet.
    pub fn udp(src: Ipv4Addr, dst: Ipv4Addr, sport: u16, dport: u16) -> Self {
        Packet {
            proto: IpProto::Udp,
            ..Self::tcp(src, dst, sport, dport)
        }
    }
}

// ── Chain identifiers ─────────────────────────────────────────────────────────

/// The five standard netfilter hook points (chains).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ChainHook {
    /// Packets entering the machine (before routing).
    Prerouting,
    /// Packets destined for local sockets.
    Input,
    /// Packets being forwarded to another machine.
    Forward,
    /// Packets generated by local processes.
    Output,
    /// Packets leaving the machine (after routing).
    Postrouting,
}

impl ChainHook {
    pub fn name(self) -> &'static str {
        match self {
            ChainHook::Prerouting => "PREROUTING",
            ChainHook::Input => "INPUT",
            ChainHook::Forward => "FORWARD",
            ChainHook::Output => "OUTPUT",
            ChainHook::Postrouting => "POSTROUTING",
        }
    }
}

// ── PacketVerdict ─────────────────────────────────────────────────────────────

/// Decision made after evaluating a rule or chain.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PacketVerdict {
    /// Accept the packet; allow it to continue.
    Accept,
    /// Drop the packet silently.
    Drop,
    /// Queue the packet to userspace.
    Queue(u16),
    /// Return from the current chain to the calling chain.
    Return,
    /// Jump to a named user-defined chain.
    Jump(String),
    /// Reject the packet and send an ICMP unreachable reply.
    Reject,
    /// Log the packet (and continue evaluation).
    Log(String),
}

impl PacketVerdict {
    /// Return `true` if this verdict terminates rule evaluation.
    pub fn is_terminal(&self) -> bool {
        matches!(self, PacketVerdict::Accept | PacketVerdict::Drop
                      | PacketVerdict::Queue(_) | PacketVerdict::Reject)
    }
}

// ── Match Criteria ────────────────────────────────────────────────────────────

/// A single match criterion for a netfilter rule.
///
/// All criteria in a [`NetfilterRule`] must match for the rule to fire.
#[derive(Debug, Clone)]
pub enum MatchCriteria {
    /// Match a specific source IP.
    SrcIp(Ipv4Addr),
    /// Match a source IP range (CIDR represented as addr + prefix length).
    SrcIpCidr { addr: Ipv4Addr, prefix: u8 },
    /// Match a specific destination IP.
    DstIp(Ipv4Addr),
    /// Match a destination IP CIDR.
    DstIpCidr { addr: Ipv4Addr, prefix: u8 },
    /// Match source port.
    SrcPort(u16),
    /// Match destination port.
    DstPort(u16),
    /// Match destination port range (inclusive).
    DstPortRange(u16, u16),
    /// Match IP protocol.
    Proto(IpProto),
    /// Match incoming interface name.
    InIface(String),
    /// Match outgoing interface name.
    OutIface(String),
    /// Match packet mark.
    Mark(u32),
    /// Invert (NOT) of the contained criterion.
    Not(Box<MatchCriteria>),
}

impl MatchCriteria {
    /// Evaluate this criterion against a packet.
    pub fn matches(&self, pkt: &Packet) -> bool {
        match self {
            MatchCriteria::SrcIp(ip) => pkt.src_ip == *ip,
            MatchCriteria::SrcIpCidr { addr, prefix } => {
                ip_in_cidr(pkt.src_ip, *addr, *prefix)
            }
            MatchCriteria::DstIp(ip) => pkt.dst_ip == *ip,
            MatchCriteria::DstIpCidr { addr, prefix } => {
                ip_in_cidr(pkt.dst_ip, *addr, *prefix)
            }
            MatchCriteria::SrcPort(p) => pkt.src_port == *p,
            MatchCriteria::DstPort(p) => pkt.dst_port == *p,
            MatchCriteria::DstPortRange(lo, hi) => pkt.dst_port >= *lo && pkt.dst_port <= *hi,
            MatchCriteria::Proto(p) => pkt.proto == *p,
            MatchCriteria::InIface(iface) => pkt.in_iface == *iface,
            MatchCriteria::OutIface(iface) => pkt.out_iface == *iface,
            MatchCriteria::Mark(m) => pkt.mark == *m,
            MatchCriteria::Not(inner) => !inner.matches(pkt),
        }
    }
}

/// Return `true` if `ip` is within the CIDR block `(network, prefix)`.
fn ip_in_cidr(ip: Ipv4Addr, network: Ipv4Addr, prefix: u8) -> bool {
    if prefix == 0 {
        return true;
    }
    if prefix > 32 {
        return false;
    }
    let mask = u32::MAX << (32 - prefix);
    let ip_u32 = u32::from(ip);
    let net_u32 = u32::from(network);
    (ip_u32 & mask) == (net_u32 & mask)
}

// ── NetfilterRule ─────────────────────────────────────────────────────────────

/// A single netfilter rule.
///
/// All `criteria` must match.  If they do, `verdict` is applied.
#[derive(Debug, Clone)]
pub struct NetfilterRule {
    /// Match conditions (AND-ed together).
    pub criteria: Vec<MatchCriteria>,
    /// Verdict when all criteria match.
    pub verdict: PacketVerdict,
    /// Human-readable comment.
    pub comment: Option<String>,
    /// Rule counter: number of times this rule matched.
    pub hit_count: u64,
}

impl NetfilterRule {
    /// Create a new rule with the given criteria and verdict.
    pub fn new(criteria: Vec<MatchCriteria>, verdict: PacketVerdict) -> Self {
        NetfilterRule {
            criteria,
            verdict,
            comment: None,
            hit_count: 0,
        }
    }

    /// Add a comment to this rule.
    pub fn with_comment(mut self, c: impl Into<String>) -> Self {
        self.comment = Some(c.into());
        self
    }

    /// Return `true` if this rule matches the given packet.
    pub fn matches(&self, pkt: &Packet) -> bool {
        self.criteria.iter().all(|c| c.matches(pkt))
    }
}

// ── Chain ────────────────────────────────────────────────────────────────────

/// A netfilter chain: an ordered list of rules plus a default policy.
#[derive(Debug)]
pub struct Chain {
    /// Chain name.
    pub name: String,
    /// Ordered list of rules.
    pub rules: Vec<NetfilterRule>,
    /// Policy applied when no rule matches.
    pub default_policy: PacketVerdict,
}

impl Chain {
    /// Create a new chain with the given default policy.
    pub fn new(name: impl Into<String>, default_policy: PacketVerdict) -> Self {
        Chain {
            name: name.into(),
            rules: Vec::new(),
            default_policy,
        }
    }

    /// Append a rule to the chain.
    pub fn add_rule(&mut self, rule: NetfilterRule) {
        self.rules.push(rule);
    }

    /// Prepend a rule to the chain (insert at position 0).
    pub fn insert_rule(&mut self, rule: NetfilterRule) {
        self.rules.insert(0, rule);
    }

    /// Evaluate the chain against a packet.
    ///
    /// Returns the terminal verdict for the packet, or `default_policy`
    /// if no rule matches.
    pub fn evaluate(&mut self, pkt: &Packet) -> PacketVerdict {
        for rule in &mut self.rules {
            if rule.matches(pkt) {
                rule.hit_count += 1;
                if rule.verdict.is_terminal() {
                    return rule.verdict.clone();
                }
                // Non-terminal: Log continues; Jump/Return handled by table.
                match &rule.verdict {
                    PacketVerdict::Log(_) => continue,
                    PacketVerdict::Jump(_) | PacketVerdict::Return => {
                        return rule.verdict.clone();
                    }
                    _ => continue,
                }
            }
        }
        self.default_policy.clone()
    }
}

// ── NetfilterTable ─────────────────────────────────────────────────────────────

/// A netfilter table containing named chains.
///
/// A table corresponds to a Linux `iptables -t TABLE` or `nft add table` context.
#[derive(Debug)]
pub struct NetfilterTable {
    /// Table name (e.g. "filter", "nat", "mangle").
    pub name: String,
    /// Chains keyed by chain name.
    pub chains: HashMap<String, Chain>,
    /// User-defined chains (can be jumped to from base chains).
    pub user_chains: HashMap<String, Chain>,
}

impl NetfilterTable {
    /// Create a `filter` table with default ACCEPT policies on all five hooks.
    pub fn new_filter() -> Self {
        let mut t = NetfilterTable {
            name: "filter".to_string(),
            chains: HashMap::new(),
            user_chains: HashMap::new(),
        };
        for hook in [ChainHook::Input, ChainHook::Forward, ChainHook::Output] {
            t.chains.insert(
                hook.name().to_string(),
                Chain::new(hook.name(), PacketVerdict::Accept),
            );
        }
        t
    }

    /// Create a `nat` table with ACCEPT default policies.
    pub fn new_nat() -> Self {
        let mut t = NetfilterTable {
            name: "nat".to_string(),
            chains: HashMap::new(),
            user_chains: HashMap::new(),
        };
        for hook in [
            ChainHook::Prerouting,
            ChainHook::Output,
            ChainHook::Postrouting,
        ] {
            t.chains.insert(
                hook.name().to_string(),
                Chain::new(hook.name(), PacketVerdict::Accept),
            );
        }
        t
    }

    /// Get a mutable reference to a base chain by hook.
    pub fn chain_mut(&mut self, hook: ChainHook) -> Option<&mut Chain> {
        self.chains.get_mut(hook.name())
    }

    /// Add a rule to the specified hook chain.
    pub fn add_rule(&mut self, hook: ChainHook, rule: NetfilterRule) {
        if let Some(chain) = self.chains.get_mut(hook.name()) {
            chain.add_rule(rule);
        }
    }

    /// Register a user-defined chain.
    pub fn add_user_chain(&mut self, chain: Chain) {
        self.user_chains.insert(chain.name.clone(), chain);
    }

    /// Evaluate a packet through the specified hook chain.
    ///
    /// Handles `Jump` verdicts by recursing into user-defined chains.
    pub fn evaluate_packet(&mut self, hook: ChainHook, pkt: &Packet) -> PacketVerdict {
        let verdict = if let Some(chain) = self.chains.get_mut(hook.name()) {
            chain.evaluate(pkt)
        } else {
            PacketVerdict::Accept
        };

        self.resolve_verdict(verdict, pkt)
    }

    /// Resolve a possibly non-terminal verdict (Jump / Return).
    fn resolve_verdict(&mut self, verdict: PacketVerdict, pkt: &Packet) -> PacketVerdict {
        match &verdict {
            PacketVerdict::Jump(chain_name) => {
                let chain_name = chain_name.clone();
                let jumped = if let Some(chain) = self.user_chains.get_mut(&chain_name) {
                    chain.evaluate(pkt)
                } else {
                    PacketVerdict::Accept
                };
                // After user chain, Return means continue in calling chain.
                if jumped == PacketVerdict::Return {
                    PacketVerdict::Accept
                } else {
                    self.resolve_verdict(jumped, pkt)
                }
            }
            v if v.is_terminal() => v.clone(),
            _ => PacketVerdict::Accept,
        }
    }

    /// Return a multi-line stats string for all chains.
    pub fn stats(&self) -> String {
        let mut out = format!("Table: {}\n", self.name);
        for (name, chain) in &self.chains {
            out.push_str(&format!("  Chain {} (policy: {:?})\n", name, chain.default_policy));
            for (i, rule) in chain.rules.iter().enumerate() {
                out.push_str(&format!(
                    "    rule[{}]: {:?} hit_count={}\n",
                    i, rule.verdict, rule.hit_count
                ));
            }
        }
        out
    }
}

// ── NAT stub ─────────────────────────────────────────────────────────────────

/// NAT translation entry (connection tracking stub).
#[derive(Debug, Clone)]
pub struct NatEntry {
    pub orig_src: Ipv4Addr,
    pub orig_sport: u16,
    pub translated_src: Ipv4Addr,
    pub translated_sport: u16,
}

/// NAT table (stub implementation).
///
/// In production this integrates with the connection tracking subsystem.
#[derive(Debug, Default)]
pub struct NatTable {
    entries: Vec<NatEntry>,
    /// Masquerade source IP (outgoing interface address).
    pub masquerade_addr: Option<Ipv4Addr>,
}

impl NatTable {
    /// Add a static SNAT entry.
    pub fn add_snat(&mut self, entry: NatEntry) {
        self.entries.push(entry);
    }

    /// Enable MASQUERADE (dynamic SNAT) with the given interface address.
    pub fn enable_masquerade(&mut self, addr: Ipv4Addr) {
        self.masquerade_addr = Some(addr);
    }

    /// Apply SNAT to a packet's source address if a rule matches.
    ///
    /// Returns `true` if translation was applied.
    pub fn apply_snat(&self, pkt: &mut Packet) -> bool {
        // Static entries take precedence.
        for entry in &self.entries {
            if pkt.src_ip == entry.orig_src && pkt.src_port == entry.orig_sport {
                pkt.src_ip = entry.translated_src;
                pkt.src_port = entry.translated_sport;
                return true;
            }
        }
        // Masquerade fallback.
        if let Some(masq_addr) = self.masquerade_addr {
            pkt.src_ip = masq_addr;
            return true;
        }
        false
    }
}

// ── Unit Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::net::Ipv4Addr;

    fn make_pkt(dst_port: u16) -> Packet {
        let mut pkt = Packet::tcp(
            Ipv4Addr::new(10, 0, 0, 1),
            Ipv4Addr::new(192, 168, 1, 1),
            12345,
            dst_port,
        );
        pkt.in_iface = "eth0".to_string();
        pkt
    }

    #[test]
    fn test_drop_ssh() {
        let mut table = NetfilterTable::new_filter();
        table.add_rule(
            ChainHook::Input,
            NetfilterRule::new(
                vec![MatchCriteria::DstPort(22), MatchCriteria::Proto(IpProto::Tcp)],
                PacketVerdict::Drop,
            ),
        );

        let pkt = make_pkt(22);
        assert_eq!(table.evaluate_packet(ChainHook::Input, &pkt), PacketVerdict::Drop);
    }

    #[test]
    fn test_allow_http() {
        let mut table = NetfilterTable::new_filter();
        table.add_rule(
            ChainHook::Input,
            NetfilterRule::new(
                vec![MatchCriteria::DstPort(22)],
                PacketVerdict::Drop,
            ),
        );

        // HTTP port 80 should use default policy (Accept).
        let pkt = make_pkt(80);
        assert_eq!(table.evaluate_packet(ChainHook::Input, &pkt), PacketVerdict::Accept);
    }

    #[test]
    fn test_cidr_match() {
        let crit = MatchCriteria::SrcIpCidr {
            addr: Ipv4Addr::new(10, 0, 0, 0),
            prefix: 8,
        };
        let pkt = make_pkt(80);
        assert!(crit.matches(&pkt)); // 10.0.0.1 is in 10.0.0.0/8

        let pkt2 = Packet::tcp(
            Ipv4Addr::new(172, 16, 0, 1),
            Ipv4Addr::new(192, 168, 1, 1),
            1234, 80,
        );
        assert!(!crit.matches(&pkt2)); // 172.16.0.1 not in 10.0.0.0/8
    }

    #[test]
    fn test_port_range_match() {
        let crit = MatchCriteria::DstPortRange(1024, 65535);
        let pkt = make_pkt(8080);
        assert!(crit.matches(&pkt));
        let pkt_low = make_pkt(80);
        assert!(!crit.matches(&pkt_low));
    }

    #[test]
    fn test_jump_to_user_chain() {
        let mut table = NetfilterTable::new_filter();

        // Create user chain that drops SSH.
        let mut ssh_chain = Chain::new("ssh-guard", PacketVerdict::Return);
        ssh_chain.add_rule(NetfilterRule::new(
            vec![MatchCriteria::DstPort(22)],
            PacketVerdict::Drop,
        ));
        table.add_user_chain(ssh_chain);

        // INPUT chain jumps to ssh-guard.
        table.add_rule(
            ChainHook::Input,
            NetfilterRule::new(vec![], PacketVerdict::Jump("ssh-guard".to_string())),
        );

        let pkt = make_pkt(22);
        assert_eq!(table.evaluate_packet(ChainHook::Input, &pkt), PacketVerdict::Drop);
    }

    #[test]
    fn test_nat_masquerade() {
        let mut nat = NatTable::default();
        nat.enable_masquerade(Ipv4Addr::new(203, 0, 113, 1));

        let mut pkt = Packet::tcp(
            Ipv4Addr::new(192, 168, 1, 100),
            Ipv4Addr::new(8, 8, 8, 8),
            54321, 443,
        );
        assert!(nat.apply_snat(&mut pkt));
        assert_eq!(pkt.src_ip, Ipv4Addr::new(203, 0, 113, 1));
    }
}
