"""
SigmaOS Core Module Manifest (v1.0 Apex)
=========================================
Centralized registry of all kernel and ecosystem shards.
Separates orchestration logic from system configuration.
"""

CORE_SYSTEM_MODULES = [
    # Core System & Security
    ("sigma_core.security.warden",              "SecurityWarden",            "security"),
    ("sigma_core.system.user_supremacy",       "SigmaUserSupremacy",        "user_supremacy"),
    ("sigma_core.security.zero_trust",         "SigmaZeroTrust",            "zero_trust"),
    ("sigma_core.system.session_manager",      "SigmaSessionManager",       "sessions"),
    ("sigma_core.system.guardian",             "SigmaGuardian",             "guardian"),
    
    # Management & Drivers
    ("sigma_core.hal.hal",                     "SigmaHAL",                  "hal"),
    ("sigma_core.hal.bootloader",              "SigmaBootloader",           "bootloader"),
    ("sigma_core.system.package_manager",      "SigmaPackageManager",       "package_manager"),
    ("sigma_core.system.ipc_manager",          "SigmaIPC",                  "ipc"),
    
    # Subsystems
    ("sigma_core.system.sigma_fs",             "SigmaFS",                   "fs"),
    ("sigma_core.system.memory_manager",       "SigmaMemoryManager",        "memory"),
    ("sigma_core.system.process_manager",       "SigmaProcessManager",       "process"),
    ("sigma_core.security.network_guardian",   "SigmaNetworkGuardian",      "net_guard"),
    ("sigma_core.ui.window_manager",           "SigmaWindowManager",        "wms"),
    ("sigma_core.system.sovereign_log",        "SovereignLog",              "sul"),
    ("sigma_core.ui.sovereign_shell",          "SovereignShell",            "shell"),
    
    # Performance & AI
    ("sigma_core.system.predictive_scheduler", "SigmaPredictiveScheduler",  "pbs"),
    ("sigma_core.system.neural_fabric",        "SigmaNeuralFabric",         "fabric"),
    ("sigma_core.system.boost_engine",         "SigmaPerformanceBoost",     "perf"),
    ("sigma_core.system.self_repair_engine",   "SigmaSelfRepairEngine",     "repair_engine"),
    ("sigma_core.system.energy_hub",           "AdaptiveEnergyController",  "energy"),
    ("sigma_core.system.app_prewarmer",        "SigmaAppPrewarmer",         "prewarmer"),
    ("sigma_core.system.app_sandbox",          "SigmaAppSandbox",           "sandbox"),
    
    # OS Services (GUI requirements)
    ("sigma_core.system.automation_engine",    "AutomationEngine",          "automator"),
    ("sigma_core.system.mode_manager",         "SigmaModeManager",          "modes"),
    ("sigma_core.system.omni_search",          "SigmaOmniSearch",           "legacy_search"),
    ("userland.system_api.theme_engine",       "SigmaThemeEngine",          "aura"),
    ("sigma_core.security.competitor_crusher", "SovereignCompetitorCrusher", "crusher"),
    ("sigma_core.security.offline_guard",      "SigmaOfflineGuard",         "offline"),
    ("sigma_core.system.stability_watchdog",    "SigmaStabilityWatchdog",    "watchdog"),
    ("sigma_core.system.pulse_engine",          "SigmaPulseEngine",          "pulse"),
    ("sigma_core.system.shadow_state",          "SigmaShadowState",          "shadow"),
    ("sigma_core.system.system_healer",         "SigmaSystemHealer",         "healer"),
    ("sigma_core.system.update_manager",        "SigmaUpdateManager",        "update_manager"),
    ("sigma_core.system.anomaly_detector",      "SigmaAnomalyDetector",      "kad"),
    ("sigma_core.system.crash_reporter",        "SigmaCrashReporter",        "crash_reporter"),
    ("sigma_core.system.system_monitor",        "SystemMonitor",             "monitor"),
    ("sigma_core.system.adaptive_governor",     "AdaptiveGovernor",          "governor"),

    # Specialized Extensions (Sovereign)
    ("sigma_core.ai.intelligence_studio",    "IntelligenceStudio",    "intelligence"),
    ("sigma_core.ai.antigravity_engine",     "AntigravityEngine",     "antigravity_engine"),
    ("sigma_core.legal.legal_engine",        "LegalEngine",           "legal_engine"),
    ("sigma_core.education.ncert_engine",    "NCERTEducationEngine",  "ncert_engine"),
    ("sigma_core.system.sync_engine",        "SigmaSyncEngine",       "sync"),
    ("sigma_core.security.aura_shield",    "SigmaAuraShield",       "shield"),
    ("sigma_core.ai.gurukul_engine",       "GurukulEngine",         "gurukul"),
    ("sigma_core.ai.intelligence_hub",     "SigmaIntelligenceHub",   "intelligence_hub"),
    ("sigma_core.system.web_syncer",       "WebSyncer",             "web_syncer"),
    ("sigma_core.ui.ghostchat",            "SigmaGhostChat",        "ghostchat"),
    ("sigma_core.security.compliance_guard", "ComplianceGuard",     "compliance"),
    ("sigma_core.security.vanguard",       "NetworkVanguard",       "vanguard"),
    ("sigma_core.security.neuro_identity", "NeuroIdentityVault",     "neuro_identity"),
    ("sigma_core.ui.morphic_dashboard",    "MorphicDashboard",      "dashboard"),
    ("sigma_core.ui.transparency_portal",  "TransparencyPortal",     "portal"),
    ("sigma_core.system.community_nexus",  "SovereignNexus",        "nexus"),
    ("sigma_core.system.mesh_dispatcher",   "MeshDispatcher",        "mesh"),
    ("sigma_core.system.sync_engine_v2",    "SovereignSync",         "sync_v2"),
    ("sigma_core.security.compliance_architect", "ComplianceArchitect", "architect"),
    ("sigma_core.system.analytic_hub",     "SovereignAnalyticHub", "hub"),
    ("sigma_core.system.minimalist_controller", "MinimalistController", "minimalist"),
    ("sigma_core.system.autonomic_healer",  "AutonomicHealer",       "healer"),
    ("sigma_core.system.integrity_scanner", "IntegrityScanner",      "integrity_scanner"),
    ("sigma_core.system.recovery_engine",   "RecoveryEngine",        "recovery"),
    ("sigma_core.system.error_manager",     "SovereignErrorManager", "error_mgr"),
    ("sigma_core.system.sovereign_triage",  "SovereignTriage",       "triage"),
    ("sigma_core.legal.legal_sovereignty", "LegalSovereignty",      "legal"),
    ("sigma_core.legal.form_engine",       "LegalFormEngine",       "legal_forms"),
    ("sigma_core.legal.advocate_cms",      "AdvocateCMS",            "cms"),
    ("sigma_core.hal.network_sentinel",     "NetworkSentinel",      "net_sentinel"),
    ("sigma_core.system.sovereign_scribe",   "SovereignScribe",       "scribe"),
    ("sigma_core.system.snapshot_engine",    "SnapshotEngine",        "snapshots"),
    ("sigma_core.system.sovereign_telemetry", "SovereignTelemetry",   "telemetry"),
    ("sigma_core.system.resource_alchemist", "ResourceAlchemist",    "resource_alchemist"),
    ("sigma_core.system.resource_monitor",   "ResourceMonitor",      "monitor_core"),
    ("sigma_core.system.silicon_tuner",     "SiliconTuner",          "tuner"),
    ("sigma_core.ai.cortex_engine",        "CortexEngine",          "cortex"),
    ("sigma_core.ai.neural_mapper",        "NeuralMapper",          "mapper"),
    ("sigma_core.ai.vibe_orchestrator",    "VibeOrchestrator",      "vibe_orch"),
    ("sigma_core.system.personalization",  "PersonalizationEngine", "personalization"),
    ("sigma_core.system.profile_manager",  "ProfileManager",        "profile_mgr"),
    ("sigma_core.system.intent_engine",    "IntentEngine",          "intent"),
    ("sigma_core.system.ritual_orchestrator", "RitualOrchestrator", "rituals"),
    ("sigma_core.system.universal_bridge", "UniversalBridge",      "bridge"),
    ("sigma_core.ui.morphic_layout",       "MorphicLayout",         "layout"),
    ("sigma_core.system.mesh_handoff",      "MeshHandoff",          "handoff"),
    ("sigma_core.system.sovereign_search",  "SovereignSearch",       "sovereign_search"),
    ("sigma_core.system.eco_gamification", "EcoGamification",       "eco"),
    ("sigma_core.system.gamification_engine", "GamificationEngine",  "gamification"),
    ("userland.system_api.antigravity_core", "AntigravityLayer", "antigravity"),
    ("userland.system_api.sigma_auditor",    "SigmaAuditor",      "qa_auditor"),
    ("userland.system_api.sigma_games_engine","SigmaGamesEngine", "games"),
    ("userland.system_api.edge_case_silo",   "EdgeCaseSilo",      "stress_silo"),
    ("userland.system_api.sigma_silo_manager","SigmaSiloManager", "silos"),
    ("userland.system_api.omni_automator",   "SigmaOmniAutomator", "automator"),
    ("userland.system_api.privacy_engine",   "PrivacyScrubber",    "scrubber"),
    ("userland.system_api.continuity_engine","SigmaContinuityEngine", "continuity"),
    ("userland.system_api.accessibility",    "SigmaAccessibilityHub", "accessibility"),
    ("userland.system_api.agentic_runtime",  "SigmaAgenticRuntime",   "agentic_runtime"),
    ("userland.system_api.identity_vault",   "SigmaIdentityVault",     "identity_vault"),
    ("userland.system_api.shared_processor", "SigmaSharedProcessor",   "shared_proc"),
    ("userland.system_api.universal_bridge", "SigmaUniversalBridge",   "userland_bridge"),
    ("userland.system_api.polyglot_runtime", "SigmaPolyglotRuntime", "polyglot_runtime"),
    ("userland.system_api.sovereign_optimizer", "SigmaSovereignOptimizer", "optimizer"),
    ("userland.system_api.net_vantage",      "SigmaNetVantage",        "net_vantage"),
    ("userland.system_api.crypt_guard",      "SigmaCryptGuard",        "crypt_guard"),
    ("userland.system_api.compliance_auditor", "SigmaComplianceAuditor", "compliance"),
    ("userland.system_api.media_forge",       "SigmaMediaForge",       "media_forge"),
    ("userland.system_api.mesh_sync_agent",   "SigmaMeshSyncAgent",     "mesh_sync"),
    ("userland.system_api.ghost_chat",       "SigmaGhostChat",         "ghost_chat"),
    ("userland.system_api.titan_capture",    "SigmaTitanCapture",      "titan_capture"),
    ("userland.system_api.aura_sound_engine", "SigmaAuraSoundEngine",  "sound_engine"),
    ("userland.system_api.task_scheduler",   "SigmaSovereignTaskScheduler", "scheduler"),
    ("userland.system_api.sovereign_registry", "SigmaSovereignRegistry", "sovereign_registry"),
    ("userland.system_api.forensic_scanner",  "SigmaForensicScanner",    "forensic"),
    ("userland.system_api.circuit_breaker",   "SigmaCircuitBreaker",     "breaker"),
    ("userland.system_api.bio_lock",         "SigmaBioLock",            "bio_lock"),
    ("userland.system_api.sovereign_watchdog", "SigmaSovereignWatchdog", "sovereign_watchdog"),
    ("userland.system_api.omni_search_v2",     "SigmaOmniSearch",        "omni_search"),
    ("userland.system_api.sovereign_clipboard_v2", "SigmaSovereignClipboardV2", "clipboard"),
    ("userland.system_api.ncert_lab_engine",  "NCERTLabEngine",          "ncert_lab"),
    
    # Internal Sentinels (Autonomous)
    ("sigma_core.system.sync_sentinel",        "SigmaSyncSentinel",       "repo_sentinel"),
    ("sigma_core.system.forensic_sentinel",    "ForensicSentinel",        "forensic_sentinel"),
]

ECOSYSTEM_APPS = [
    ("ecosystem.aether_orchestrator",  "AetherOrchestrator",        "aether_orch"),
    ("ecosystem.pdf_forge",            "SigmaPDFForge",             "pdf_forge"),
    ("ecosystem.titan_capture",        "SigmaTitanCapture",         "titan_capture"),
    ("ecosystem.sigma_ai_nexus",       "SigmaAINexus",              "nexus"),
    ("ecosystem.sigma_studio",         "SigmaStudioPlus",           "studio"),
    ("ecosystem.aura_assistant",       "SigmaAuraAssistant",        "assistant"),
    ("userland.intelligence_suite.sigma_data_viz", "SigmaDataViz", "viz_engine"),
    ("userland.intelligence_suite.sigma_ml_engine", "SigmaMLEngine", "ml_engine"),
    ("userland.intelligence_suite.sigma_genai_lab", "SigmaGenAILab", "genai_lab"),
    ("userland.intelligence_suite.sigma_insights", "SigmaInsightsEngine", "insights_engine"),
    ("userland.intelligence_suite.sigma_sql_forge", "SigmaSQLForge", "sql_forge"),
    ("userland.intelligence_suite.sigma_hypertune", "SigmaHyperTune", "hypertune"),
]
