#include "../../../../include/libc/SovereignLibC.h"
#define SIGMA_EXCLUDE_STD_ALIASES
// =============================================================================
// SigmaOS — tools/sovereign_wiki — sovereign_wiki_builder.c
// Native C Replacement for scripts/wiki_builder.py
// =============================================================================
// Replaces: scripts/wiki_builder.py, kernel/suites/S10_Registry/wiki_builder.py
// Competitor USPs Absorbed:
//   • Doxygen   — AST-scanning C doc extraction, no Python runtime
//   • Javadoc   — structured /// comment parsing
//   • Rustdoc   — inline module-level documentation from source
// Zero external deps — single-file, compiles with gcc -std=c11 -O2
// =============================================================================

#include "../../../../include/libc/sigma_libc.h"
#include "../../../../include/core/sigma_types.h"

#include <dirent.h>
#include <sys/stat.h>

#define MAX_PATH_LEN    1024
#define MAX_DOC_LINE    512
#define WIKI_VERSION    "2.0.0"

// ── Shard Doc Entry ───────────────────────────────────────────────────────────
typedef struct {
    char suite[32];
    char filename[128];
    char title[128];
    char usps[512];    // Extracted from "Competitor USPs Absorbed:" block
    char description[512];
} ShardDoc;

static ShardDoc docs[1024];
static uint32_t doc_count = 0;

// ── Extract doc metadata from a .c/.h source file ─────────────────────────────
static bool extract_shard_doc(const char* path, const char* suite,
                               const char* filename) {
    FILE* f = sigma_open(path, "r");
    if (!f) return false;

    ShardDoc* doc = &docs[doc_count];
    sigma_strncpy(doc->suite,    suite,    31);
    sigma_strncpy(doc->filename, filename, 127);
    doc->usps[0]        = '\0';
    doc->description[0] = '\0';
    doc->title[0]       = '\0';

    char line[MAX_DOC_LINE];
    bool in_usps = false;

    while (fgets(line, sizeof(line), f)) {
        // Grab shard title from // SigmaOS — Suite — ShardName
        if (strstr(line, "// SigmaOS —") && doc->title[0] == '\0') {
            char* dash = strstr(line, "—");
            if (dash) {
                dash = strstr(dash + 3, "—");
                if (dash) sigma_strncpy(doc->title, dash + 2, 127);
                // Strip trailing newline
                char* nl = strchr(doc->title, '\n');
                if (nl) *nl = '\0';
            }
        }
        // Grab USP block
        if (strstr(line, "Competitor USPs Absorbed:")) { in_usps = true; continue; }
        if (in_usps) {
            if (strstr(line, "//   •")) {
                strncat(doc->usps, line + 6,
                        sizeof(doc->usps) - sigma_strlen(doc->usps) - 1);
            } else if (strstr(line, "// Architecture") ||
                       strstr(line, "// Zero") ||
                       strstr(line, "#include")) {
                in_usps = false;
            }
        }
    }
    sigma_close(f);
    if (doc->title[0] == '\0')
        sigma_strncpy(doc->title, filename, 127);

    doc_count++;
    return true;
}

// ── Walk a suite directory ─────────────────────────────────────────────────────
static void walk_suite(const char* suite_path, const char* suite_name) {
    DIR* dir = opendir(suite_path);
    if (!dir) return;
    struct dirent* entry;
    while ((entry = readdir(dir)) != SIGMA_NULL) {
        if (entry->d_name[0] == '.') continue;
        const char* ext = strrchr(entry->d_name, '.');
        if (!ext) continue;
        if (sigma_strcmp(ext, ".c") != 0 && sigma_strcmp(ext, ".h") != 0 &&
            sigma_strcmp(ext, ".rs") != 0) continue;

        char full_path[MAX_PATH_LEN];
        snsigma_printf(full_path, sizeof(full_path), "%s/%s", suite_path, entry->d_name);
        extract_shard_doc(full_path, suite_name, entry->d_name);
    }
    closedir(dir);
}

// ── Emit Markdown wiki page ───────────────────────────────────────────────────
static void emit_wiki_markdown(const char* out_path) {
    FILE* f = sigma_open(out_path, "w");
    if (!f) { fsigma_printf(stderr, "Cannot open %s\n", out_path); return; }

    fsigma_printf(f, "# SigmaOS Sovereign Shard Wiki\n");
    fsigma_printf(f, "> Auto-generated by `sovereign_wiki_builder` v%s\n\n", WIKI_VERSION);
    fsigma_printf(f, "| Suite | Shard | USPs Absorbed |\n");
    fsigma_printf(f, "|:------|:------|:--------------|\n");

    for (uint32_t i = 0; i < doc_count; i++) {
        ShardDoc* d = &docs[i];
        // Collapse multi-line USP to single line
        char usps_flat[512];
        sigma_strncpy(usps_flat, d->usps, 511);
        for (char* c = usps_flat; *c; c++) if (*c == '\n') *c = ' ';

        fsigma_printf(f, "| `%s` | `%s` | %s |\n",
                d->suite, d->filename, usps_flat[0] ? usps_flat : "—");
    }

    fsigma_printf(f, "\n_Total shards documented: %u_\n", doc_count);
    sigma_close(f);
    sigma_printf("[sigma-wiki] Written %u entries → %s\n", doc_count, out_path);
}

int main(int argc, char* argv[]) {
    const char* suites_root = (argc > 1) ? argv[1] : "kernel/suites";
    const char* output_file = (argc > 2) ? argv[2] : "WIKI/AUTO_SOVEREIGN_WIKI.md";

    DIR* root_dir = opendir(suites_root);
    if (!root_dir) {
        fsigma_printf(stderr, "[sigma-wiki ERROR]: Cannot open suites root: %s\n", suites_root);
        return 1;
    }

    struct dirent* suite_entry;
    while ((suite_entry = readdir(root_dir)) != SIGMA_NULL) {
        if (suite_entry->d_name[0] == '.') continue;
        
        char suite_path[MAX_PATH_LEN];
        snsigma_printf(suite_path, sizeof(suite_path), "%s/%s", suites_root, suite_entry->d_name);

        struct stat st;
        if (stat(suite_path, &st) == 0 && S_ISDIR(st.st_mode)) {
            // Document the suite shards
            char shards_path[MAX_PATH_LEN];
            snsigma_printf(shards_path, sizeof(shards_path), "%s/shards", suite_path);
            
            // Check if shards/ exists, else walk the suite dir directly
            struct stat sst;
            if (stat(shards_path, &sst) == 0 && S_ISDIR(sst.st_mode)) {
                walk_suite(shards_path, suite_entry->d_name);
            } else {
                walk_suite(suite_path, suite_entry->d_name);
            }
        }
    }
    closedir(root_dir);

    emit_wiki_markdown(output_file);
    return 0;
}


