tabs: ttk.Notebook
tab_timer: tk.Frame
tab_converter: tk.Frame
tab_calc: tk.Frame
tab_qr: tk.Frame
tab_fin: tk.Frame
tab_misc: tk.Frame
status: tk.Label
timer_entry: tk.Entry
timer_label: tk.Label
meter_entry: tk.Entry
feet_entry: tk.Entry
usd_entry: tk.Entry
eur_entry: tk.Entry
temp_in: tk.Entry
temp_out: tk.Label
temp_unit: tk.StringVar
expr_entry: tk.Entry
expr_result: tk.Label
loan_principal_entry: tk.Entry
loan_rate_entry: tk.Entry
loan_years_entry: tk.Entry
emi_result: tk.Label
qr_data_entry: tk.Entry
qr_canvas: tk.Canvas
split_total: tk.Entry
split_people: tk.Entry
split_result: tk.Label
bmi_weight: tk.Entry
bmi_height: tk.Entry
bmi_result: tk.Label
pwd_len: tk.Spinbox
pwd_result: tk.Entry
