# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 SigmaOS Project
#
# userland/agent/sigma_agent_shell_integration.nim — Shell hook for sigma-sh
# Inspiration: Claude Code shell integration, ai-shell inline suggestions
# Language: Nim — generates .sigma_agent_rc for sourcing in sigma-sh

import std/[os, strformat, strutils]

# ── Shell Integration Script ──────────────────────────────────────────────────
const SHELL_RC = """
# sigma-agent shell integration — source this in .sigma_profile
# Generated by sigma-agent install --shell-integration

# ── Keybindings ───────────────────────────────────────────────────────────────
# Ctrl+K  : Open sigma-agent with current command as context
# Ctrl+X A: AI explain current command
# Ctrl+X F: AI suggest fix for last error

# ── Aliases ───────────────────────────────────────────────────────────────────
alias ai='sigma-agent'
alias ask='sigma-agent'
alias σ='sigma-agent'
alias explain='sigma-agent explain'
alias suggest='sigma-agent mirror run'
alias watch='sigma-agent watch'
alias fix='sigma-agent fix'

# ── Functions ─────────────────────────────────────────────────────────────────

# Run a command and auto-fix errors with AI
ai_run() {
    local cmd="$*"
    local output
    output=$(eval "$cmd" 2>&1)
    local exit_code=$?
    echo "$output"
    if [ $exit_code -ne 0 ]; then
        echo ""
        echo "⚡ sigma-agent: command failed, suggesting fix..."
        sigma-agent "fix this error: command=$cmd error=$output"
    fi
}

# Explain the last command
ai_explain_last() {
    local last_cmd=$(history 1 | sed 's/^[[:space:]]*[0-9]*[[:space:]]*//')
    sigma-agent "explain what this command does: $last_cmd"
}

# AI-powered cd with suggestions
ai_cd() {
    if [ -z "$1" ]; then
        cd ~ || return
    else
        cd "$1" 2>/dev/null || {
            echo "Directory not found. sigma-agent suggests:"
            sigma-agent "find directory named $1"
        }
    fi
}

# Auto-suggest on command not found
command_not_found_handler() {
    local cmd="$1"
    echo "sigma-agent: '$cmd' not found."
    local suggestion=$(sigma-agent "what is the sigma-os command for: $cmd" 2>/dev/null)
    if [ -n "$suggestion" ]; then
        echo "Did you mean: $suggestion"
    fi
    return 127
}

# ── Prompt enhancement ────────────────────────────────────────────────────────
# Add AI status indicator to prompt (shows backend status)
_sigma_agent_status() {
    if command -v sigma-agent >/dev/null 2>&1; then
        echo -n "σ"
    fi
}

# Source this for enhanced prompt:
# export PS1="$(_sigma_agent_status) $PS1"

# ── Tab completion ────────────────────────────────────────────────────────────
_sigma_agent_complete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local commands="install open list read write run explain fix summarise watch mirror train config"
    COMPREPLY=($(compgen -W "$commands" -- "$cur"))
}

# Enable completions (bash)
complete -F _sigma_agent_complete sigma-agent
complete -F _sigma_agent_complete ai
complete -F _sigma_agent_complete ask

# ── sigma-agent shortcuts ─────────────────────────────────────────────────────
alias ai-dark='sigma-agent "set dark mode"'
alias ai-light='sigma-agent "set light mode"'
alias ai-sysinfo='sigma-agent "system info"'
alias ai-procs='sigma-agent "show processes"'
alias ai-net='sigma-agent "network status"'
alias ai-disk='sigma-agent "disk usage"'
alias ai-install='sigma-pkg install'
alias ai-update='sigma-pkg update'
alias ai-history='sigma-agent history'
alias ai-config='sigma-agent config'
alias ai-train='sigma-agent train'
alias ai-mirror='sigma-agent mirror list'
"""

# ── Fish shell integration ────────────────────────────────────────────────────
const FISH_INTEGRATION = """
# sigma-agent fish shell integration
# Place in: ~/.config/fish/conf.d/sigma_agent.fish

abbr --add ai   sigma-agent
abbr --add ask  sigma-agent
abbr --add explain 'sigma-agent explain'
abbr --add aifix   'sigma-agent fix'

function sigma_agent_suggest
    set cmd (commandline)
    if test (string length $cmd) -gt 0
        sigma-agent "suggest command for: $cmd"
    end
end

function fish_command_not_found
    set cmd $argv[1]
    echo "sigma-agent: '$cmd' not found. Asking AI..."
    sigma-agent "what is the SigmaOS command for: $cmd"
end

bind \ck sigma_agent_suggest
"""

# ── Zsh/sigma-sh integration ──────────────────────────────────────────────────
const ZSH_INTEGRATION = """
# sigma-agent zsh/sigma-sh integration
# Place in: ~/.zshrc or ~/.sigma_profile

alias ai='sigma-agent'
alias explain='sigma-agent explain'
alias aifix='sigma-agent fix'

# Command not found → AI suggestion
command_not_found_handler() {
    echo "sigma-agent: '$1' not found"
    sigma-agent "what SigmaOS command does: $1"
    return 127
}

# Bind Ctrl+K to sigma-agent
bindkey -s '^k' 'sigma-agent "$(fc -ln -1)"^M'
"""

proc install_shell_integration*(shell = "auto") =
  let home = getEnv("HOME", "/tmp")

  let detected = if shell == "auto":
    let sigma_sh = home / ".sigma_profile"
    let bashrc   = home / ".bashrc"
    if fileExists(sigma_sh): "sigma-sh"
    elif fileExists(home / ".config/fish"): "fish"
    elif fileExists(home / ".zshrc"): "zsh"
    else: "bash"
  else: shell

  echo fmt"Installing sigma-agent {detected} integration..."

  case detected
  of "sigma-sh", "bash":
    let rc_file = home / ".sigma_agent_rc"
    writeFile(rc_file, SHELL_RC)
    echo fmt"✓ Written: {rc_file}"

    # Auto-source in .sigma_profile or .bashrc
    let profile = if fileExists(home / ".sigma_profile"): home / ".sigma_profile"
                  else: home / ".bashrc"
    let source_line = fmt"source {rc_file}  # sigma-agent integration"
    let existing = try: readFile(profile) except: ""
    if not existing.contains("sigma-agent integration"):
      var f = open(profile, fmAppend)
      f.writeLine("\n" & source_line)
      f.close()
      echo fmt"✓ Added source line to {profile}"
    else:
      echo fmt"  (already sourced in {profile})"

  of "fish":
    let fish_dir = home / ".config/fish/conf.d"
    createDir(fish_dir)
    writeFile(fish_dir / "sigma_agent.fish", FISH_INTEGRATION)
    echo fmt"✓ Written: {fish_dir}/sigma_agent.fish"

  of "zsh":
    let zshrc = home / ".zshrc"
    let snippet_file = home / ".sigma_agent_zsh"
    writeFile(snippet_file, ZSH_INTEGRATION)
    let existing = try: readFile(zshrc) except: ""
    if not existing.contains("sigma-agent zsh"):
      var f = open(zshrc, fmAppend)
      f.writeLine(fmt"\nsource {snippet_file}  # sigma-agent integration")
      f.close()
    echo fmt"✓ Written: {snippet_file}"

  else:
    echo fmt"Unknown shell: {detected}. Writing generic RC file."
    writeFile(home / ".sigma_agent_rc", SHELL_RC)

  echo fmt"""
Shell integration installed for {detected}!

Restart your shell or run:
  source ~/.sigma_agent_rc

New shortcuts:
  ai "your request"         — natural language OS commands
  ai-dark                   — switch to dark mode
  ai-sysinfo                — system overview
  ai-procs                  — running processes
  explain <command>         — AI explains a command
  aifix <file>              — AI fixes errors in a file
  sigma-agent watch .       — proactive AI file monitoring
"""

proc uninstall_shell_integration*() =
  let home = getEnv("HOME", "/tmp")
  let rc_file = home / ".sigma_agent_rc"
  if fileExists(rc_file): removeFile(rc_file)
  echo "✓ Removed sigma-agent shell integration"
  echo "  You may also want to remove the source line from ~/.sigma_profile"
