[package]
name = "sigma_compositor"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Native display server, shell, and window manager compositor for SigmaOS, displacing Wayland, X11, GNOME, and KDE"

[dependencies]
# Standard library is available in userland
sigma-design-system = { path = "../ui/design_system" }
