//! Omarchy 4 Advanced Parity Module for SigmaOS
//!
//! Inspired by Omarchy 4 Linux ecosystem (https://github.com/omarchy):
//! - Hyprland 0.40+ Dynamic Tiling Manager (Dwindle/Master, Blur/Shadows, Bezier Curves, Smart Gaps)
//! - Waybar Status Applet Studio (JSON/CSS Status Bar Config, Dynamic Module Toggles, System Trays)
//! - Ghostty & Kitty Terminal Emulator Font Studio (Nerd Font Rendering, Hardware-Accelerated Shaders)
//! - Omakase Neovim LSP & Plugin Engine (Mason LSP, Treesitter Parsers, Lazy.nvim Plugin Manifests)
//! - 60-Second Live ISO Installer & Bootstrap System (Archinstall Wrapper & Workstation Provisioning)
//! - Master Omarchy Parity Suite & Readiness Evaluator

#![no_std]

extern crate alloc;

use alloc::collections::BTreeMap;
use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec;
use alloc::vec::Vec;

/// Hyprland Layout Type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HyprlandLayoutType {
    Dwindle,
    Master,
}

/// Hyprland Dynamic Tiling Manager Config Engine
#[derive(Debug, Clone)]
pub struct Omarchy4HyprlandDynamicTilingManager {
    pub layout: HyprlandLayoutType,
    pub gaps_in: u32,
    pub gaps_out: u32,
    pub border_size: u32,
    pub active_border_color: String,
    pub inactive_border_color: String,
    pub rounding: u32,
    pub blur_enabled: bool,
    pub blur_size: u32,
    pub blur_passes: u32,
    pub animation_speed_ms: u32,
    pub window_rules: Vec<String>,
    pub workspace_rules: BTreeMap<u32, String>,
}

impl Omarchy4HyprlandDynamicTilingManager {
    pub fn new() -> Self {
        let mut rules = Vec::new();
        rules.push("float, class:^(pavucontrol)$".to_string());
        rules.push("float, class:^(blueman-manager)$".to_string());
        rules.push("float, title:^(Picture-in-Picture)$".to_string());
        rules.push("pin, title:^(Picture-in-Picture)$".to_string());

        let mut ws_rules = BTreeMap::new();
        ws_rules.insert(1, "monitor:DP-1, default:true".to_string());
        ws_rules.insert(2, "monitor:DP-1".to_string());
        ws_rules.insert(3, "monitor:DP-2".to_string());

        Self {
            layout: HyprlandLayoutType::Dwindle,
            gaps_in: 5,
            gaps_out: 10,
            border_size: 2,
            active_border_color: "rgba(7aa2f7ee) rgba(cba6f7ee) 45deg".to_string(),
            inactive_border_color: "rgba(1a1b26aa)".to_string(),
            rounding: 8,
            blur_enabled: true,
            blur_size: 6,
            blur_passes: 2,
            animation_speed_ms: 200,
            window_rules: rules,
            workspace_rules: ws_rules,
        }
    }

    pub fn set_layout(&mut self, layout: HyprlandLayoutType) {
        self.layout = layout;
    }

    pub fn add_window_rule(&mut self, rule: &str) {
        self.window_rules.push(rule.to_string());
    }

    pub fn assign_workspace_monitor(&mut self, workspace_id: u32, monitor_spec: &str) {
        self.workspace_rules.insert(workspace_id, monitor_spec.to_string());
    }

    pub fn generate_hyprland_conf(&self) -> String {
        let layout_str = match self.layout {
            HyprlandLayoutType::Dwindle => "dwindle",
            HyprlandLayoutType::Master => "master",
        };

        let mut conf = String::new();
        conf.push_str("# Omarchy 4 Autogenerated Hyprland Configuration\n");
        conf.push_str("general {\n");
        conf.push_str(&format!("    gaps_in = {}\n", self.gaps_in));
        conf.push_str(&format!("    gaps_out = {}\n", self.gaps_out));
        conf.push_str(&format!("    border_size = {}\n", self.border_size));
        conf.push_str(&format!("    col.active_border = {}\n", self.active_border_color));
        conf.push_str(&format!("    col.inactive_border = {}\n", self.inactive_border_color));
        conf.push_str(&format!("    layout = {}\n", layout_str));
        conf.push_str("}\n\n");

        conf.push_str("decoration {\n");
        conf.push_str(&format!("    rounding = {}\n", self.rounding));
        conf.push_str("    blur {\n");
        conf.push_str(&format!("        enabled = {}\n", self.blur_enabled));
        conf.push_str(&format!("        size = {}\n", self.blur_size));
        conf.push_str(&format!("        passes = {}\n", self.blur_passes));
        conf.push_str("    }\n");
        conf.push_str("}\n\n");

        conf.push_str("animations {\n");
        conf.push_str("    enabled = true\n");
        conf.push_str("    bezier = omarchyEase, 0.05, 0.9, 0.1, 1.05\n");
        conf.push_str(&format!(
            "    animation = windows, 1, {}, omarchyEase\n",
            self.animation_speed_ms / 30
        ));
        conf.push_str("}\n\n");

        conf.push_str("# Window Rules\n");
        for rule in &self.window_rules {
            conf.push_str(&format!("windowrulev2 = {}\n", rule));
        }

        conf.push_str("\n# Workspace Rules\n");
        for (ws_id, spec) in &self.workspace_rules {
            conf.push_str(&format!("workspace = {}, {}\n", ws_id, spec));
        }

        conf
    }
}

impl Default for Omarchy4HyprlandDynamicTilingManager {
    fn default() -> Self {
        Self::new()
    }
}

/// Waybar Status Applet Studio Module Config
#[derive(Debug, Clone)]
pub struct WaybarModuleConfig {
    pub name: String,
    pub icon: String,
    pub update_interval_secs: u32,
    pub enabled: bool,
}

/// Waybar Status Applet Studio Engine
#[derive(Debug, Clone)]
pub struct OmarchyWaybarStatusAppletStudio {
    pub modules: Vec<WaybarModuleConfig>,
    pub position_top: bool,
    pub height_px: u32,
}

impl OmarchyWaybarStatusAppletStudio {
    pub fn new() -> Self {
        let modules = vec![
            WaybarModuleConfig {
                name: "hyprland/workspaces".to_string(),
                icon: "".to_string(),
                update_interval_secs: 0,
                enabled: true,
            },
            WaybarModuleConfig {
                name: "cpu".to_string(),
                icon: "".to_string(),
                update_interval_secs: 2,
                enabled: true,
            },
            WaybarModuleConfig {
                name: "memory".to_string(),
                icon: "".to_string(),
                update_interval_secs: 5,
                enabled: true,
            },
            WaybarModuleConfig {
                name: "pulseaudio".to_string(),
                icon: "".to_string(),
                update_interval_secs: 1,
                enabled: true,
            },
            WaybarModuleConfig {
                name: "network".to_string(),
                icon: "".to_string(),
                update_interval_secs: 3,
                enabled: true,
            },
            WaybarModuleConfig {
                name: "clock".to_string(),
                icon: "".to_string(),
                update_interval_secs: 1,
                enabled: true,
            },
            WaybarModuleConfig {
                name: "tray".to_string(),
                icon: "⚙".to_string(),
                update_interval_secs: 0,
                enabled: true,
            },
        ];

        Self {
            modules,
            position_top: true,
            height_px: 32,
        }
    }

    pub fn toggle_module(&mut self, module_name: &str, enable: bool) -> bool {
        if let Some(m) = self.modules.iter_mut().find(|m| m.name == module_name) {
            m.enabled = enable;
            true
        } else {
            false
        }
    }

    pub fn generate_waybar_json_config(&self) -> String {
        let mut active_modules = Vec::new();
        for m in &self.modules {
            if m.enabled {
                active_modules.push(format!("\"{}\"", m.name));
            }
        }

        format!(
            "{{\n  \"layer\": \"top\",\n  \"position\": \"{}\",\n  \"height\": {},\n  \"modules-left\": [\"hyprland/workspaces\"],\n  \"modules-center\": [\"clock\"],\n  \"modules-right\": [{}]\n}}",
            if self.position_top { "top" } else { "bottom" },
            self.height_px,
            active_modules.join(", ")
        )
    }

    pub fn generate_waybar_css_theme(&self) -> String {
        r#"/* Omarchy 4 Waybar CSS Theme */
* {
    border: none;
    border-radius: 0;
    font-family: "JetBrainsMono Nerd Font", Roboto, Helvetica, Arial, sans-serif;
    font-size: 13px;
    min-height: 0;
}

window#waybar {
    background-color: rgba(26, 27, 38, 0.85);
    color: #c0caf5;
    transition-property: background-color;
    transition-duration: .5s;
}

#workspaces button {
    padding: 0 5px;
    background-color: transparent;
    color: #565f89;
}

#workspaces button.active {
    color: #7aa2f7;
}

#cpu, #memory, #pulseaudio, #network, #clock {
    padding: 0 10px;
    color: #c0caf5;
}
"#
        .to_string()
    }
}

impl Default for OmarchyWaybarStatusAppletStudio {
    fn default() -> Self {
        Self::new()
    }
}

/// Ghostty & Kitty Terminal Font & Shader Config Generator
#[derive(Debug, Clone)]
pub struct OmarchyGhosttyKittyFontStudio {
    pub font_family: String,
    pub font_size: f32,
    pub line_height: f32,
    pub cursor_shape: String,
    pub enable_gpu_rendering: bool,
    pub opacity: f32,
}

impl OmarchyGhosttyKittyFontStudio {
    pub fn new() -> Self {
        Self {
            font_family: "JetBrainsMono Nerd Font".to_string(),
            font_size: 12.0,
            line_height: 1.2,
            cursor_shape: "block".to_string(),
            enable_gpu_rendering: true,
            opacity: 0.92,
        }
    }

    pub fn generate_kitty_conf(&self) -> String {
        format!(
            "font_family {}\nfont_size {}\nadjust_line_height {}\ncursor_shape {}\nbackground_opacity {}\nrepaint_delay 6\ninput_delay 2\nsync_to_monitor yes\n",
            self.font_family, self.font_size, self.line_height, self.cursor_shape, self.opacity
        )
    }

    pub fn generate_ghostty_config(&self) -> String {
        format!(
            "font-family = \"{}\"\nfont-size = {}\ncursor-style = {}\nbackground-opacity = {}\ngpu-backend = {}\n",
            self.font_family,
            self.font_size,
            self.cursor_shape,
            self.opacity,
            if self.enable_gpu_rendering { "auto" } else { "software" }
        )
    }
}

impl Default for OmarchyGhosttyKittyFontStudio {
    fn default() -> Self {
        Self::new()
    }
}

/// Omakase Neovim LSP & Plugin Spec Engine
#[derive(Debug, Clone)]
pub struct OmarchyOmakaseNeovimLspEngine {
    pub lsp_servers: Vec<String>,
    pub treesitter_parsers: Vec<String>,
    pub lazy_plugins: Vec<String>,
    pub leader_key: String,
}

impl OmarchyOmakaseNeovimLspEngine {
    pub fn new() -> Self {
        let lsp_servers = vec![
            "rust_analyzer".to_string(),
            "gopls".to_string(),
            "pyright".to_string(),
            "ts_ls".to_string(),
            "lua_ls".to_string(),
            "clangd".to_string(),
            "zls".to_string(),
        ];

        let parsers = vec![
            "rust".to_string(),
            "go".to_string(),
            "python".to_string(),
            "typescript".to_string(),
            "lua".to_string(),
            "c".to_string(),
            "cpp".to_string(),
            "zig".to_string(),
            "markdown".to_string(),
        ];

        let plugins = vec![
            "folke/tokyonight.nvim".to_string(),
            "nvim-treesitter/nvim-treesitter".to_string(),
            "neovim/nvim-lspconfig".to_string(),
            "williamboman/mason.nvim".to_string(),
            "hrsh7th/nvim-cmp".to_string(),
            "nvim-telescope/telescope.nvim".to_string(),
            "numToStr/Comment.nvim".to_string(),
        ];

        Self {
            lsp_servers,
            treesitter_parsers: parsers,
            lazy_plugins: plugins,
            leader_key: " ".to_string(),
        }
    }

    pub fn add_lsp_server(&mut self, server: &str) {
        if !self.lsp_servers.iter().any(|s| s == server) {
            self.lsp_servers.push(server.to_string());
        }
    }

    pub fn generate_init_lua(&self) -> String {
        let mut lua = String::new();
        lua.push_str("-- Omarchy 4 Omakase Neovim init.lua\n");
        lua.push_str(&format!("vim.g.mapleader = \"{}\"\n", self.leader_key));
        lua.push_str("vim.opt.number = true\n");
        lua.push_str("vim.opt.relativenumber = true\n");
        lua.push_str("vim.opt.termguicolors = true\n");
        lua.push_str("vim.opt.shiftwidth = 4\n");
        lua.push_str("vim.opt.tabstop = 4\n");
        lua.push_str("vim.opt.expandtab = true\n\n");

        lua.push_str("-- Mason LSP Auto-Installation\n");
        lua.push_str("local mason = require(\"mason\")\n");
        lua.push_str("mason.setup()\n");
        lua.push_str("local lspconfig = require(\"lspconfig\")\n");
        for server in &self.lsp_servers {
            lua.push_str(&format!("lspconfig.{}.setup({{}})\n", server));
        }

        lua
    }
}

impl Default for OmarchyOmakaseNeovimLspEngine {
    fn default() -> Self {
        Self::new()
    }
}

/// 60-Second Workstation Live ISO Installer & Bootstrap System
#[derive(Debug, Clone)]
pub struct OmarchyLiveIsoInstallerBootstrap {
    pub target_disk: String,
    pub hostname: String,
    pub username: String,
    pub auto_partition_btrfs: bool,
    pub install_nvidia_drivers: bool,
    pub install_omarchy_dotfiles: bool,
}

impl OmarchyLiveIsoInstallerBootstrap {
    pub fn new(disk: &str, hostname: &str, user: &str) -> Self {
        Self {
            target_disk: disk.to_string(),
            hostname: hostname.to_string(),
            username: user.to_string(),
            auto_partition_btrfs: true,
            install_nvidia_drivers: false,
            install_omarchy_dotfiles: true,
        }
    }

    pub fn generate_archinstall_creds_json(&self) -> String {
        format!(
            "{{\n  \"disk_layout\": \"btrfs_subvolumes\",\n  \"target_disk\": \"{}\",\n  \"hostname\": \"{}\",\n  \"username\": \"{}\",\n  \"desktop\": \"hyprland\",\n  \"audio\": \"pipewire\",\n  \"dotfiles\": {}\n}}",
            self.target_disk,
            self.hostname,
            self.username,
            self.install_omarchy_dotfiles
        )
    }

    pub fn generate_bootstrap_script(&self) -> String {
        format!(
            r#"#!/usr/bin/env bash
# Omarchy 4 Live Installer Bootstrap
set -euo pipefail

echo "=== Starting 60-second Omarchy 4 Bootstrap ==="
archinstall --config /tmp/omarchy_archinstall.json
arch-chroot /mnt systemctl enable GDM Hyprland
echo "=== Bootstrap Complete. Rebooting into Omarchy 4 ==="
"#
        )
    }
}

/// Master Omarchy Parity Coordinator & Readiness Suite
#[derive(Debug, Clone)]
pub struct OmarchyMasterParitySuite {
    pub tiling_manager: Omarchy4HyprlandDynamicTilingManager,
    pub waybar_studio: OmarchyWaybarStatusAppletStudio,
    pub font_studio: OmarchyGhosttyKittyFontStudio,
    pub nvim_engine: OmarchyOmakaseNeovimLspEngine,
    pub installer: OmarchyLiveIsoInstallerBootstrap,
}

impl OmarchyMasterParitySuite {
    pub fn new() -> Self {
        Self {
            tiling_manager: Omarchy4HyprlandDynamicTilingManager::new(),
            waybar_studio: OmarchyWaybarStatusAppletStudio::new(),
            font_studio: OmarchyGhosttyKittyFontStudio::new(),
            nvim_engine: OmarchyOmakaseNeovimLspEngine::new(),
            installer: OmarchyLiveIsoInstallerBootstrap::new("/dev/nvme0n1", "omarchy-box", "sovereign"),
        }
    }

    pub fn evaluate_parity_score(&self) -> f32 {
        let mut score = 0.0f32;
        if self.tiling_manager.blur_enabled {
            score += 20.0;
        }
        if !self.waybar_studio.modules.is_empty() {
            score += 20.0;
        }
        if self.font_studio.enable_gpu_rendering {
            score += 20.0;
        }
        if !self.nvim_engine.lsp_servers.is_empty() {
            score += 20.0;
        }
        if self.installer.auto_partition_btrfs {
            score += 20.0;
        }
        score
    }
}

impl Default for OmarchyMasterParitySuite {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hyprland_tiling_conf_generation() {
        let mut mgr = Omarchy4HyprlandDynamicTilingManager::new();
        mgr.set_layout(HyprlandLayoutType::Dwindle);
        let conf = mgr.generate_hyprland_conf();
        assert!(conf.contains("layout = dwindle"));
        assert!(conf.contains("gaps_in = 5"));
        assert!(conf.contains("windowrulev2 = float, class:^(pavucontrol)$"));
    }

    #[test]
    fn test_waybar_applet_studio() {
        let mut studio = OmarchyWaybarStatusAppletStudio::new();
        assert!(studio.toggle_module("cpu", true));
        let json = studio.generate_waybar_json_config();
        assert!(json.contains("\"hyprland/workspaces\""));
        let css = studio.generate_waybar_css_theme();
        assert!(css.contains("Omarchy 4 Waybar CSS Theme"));
    }

    #[test]
    fn test_font_studio_kitty_ghostty() {
        let studio = OmarchyGhosttyKittyFontStudio::new();
        let kitty = studio.generate_kitty_conf();
        assert!(kitty.contains("font_family JetBrainsMono Nerd Font"));
        let ghostty = studio.generate_ghostty_config();
        assert!(ghostty.contains("gpu-backend = auto"));
    }

    #[test]
    fn test_omakase_nvim_engine() {
        let mut nvim = OmarchyOmakaseNeovimLspEngine::new();
        nvim.add_lsp_server("wgsl_analyzer");
        let lua = nvim.generate_init_lua();
        assert!(lua.contains("lspconfig.wgsl_analyzer.setup({})"));
    }

    #[test]
    fn test_live_installer_bootstrap() {
        let installer = OmarchyLiveIsoInstallerBootstrap::new("/dev/sda", "test-box", "user1");
        let json = installer.generate_archinstall_creds_json();
        assert!(json.contains("\"target_disk\": \"/dev/sda\""));
        let script = installer.generate_bootstrap_script();
        assert!(script.contains("Omarchy 4 Live Installer Bootstrap"));
    }

    #[test]
    fn test_master_parity_suite_score() {
        let suite = OmarchyMasterParitySuite::new();
        let score = suite.evaluate_parity_score();
        assert_eq!(score, 100.0);
    }
}
