# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 SigmaOS Project
# userland/net/sigma_netctl.nim — sigma-netctl: Network Interface Controller
# Language: Nim — native, OOP via object + methods, no third-party

import std/[os, strutils, osproc, parseopt, strformat, tables]

type
  IfMode = enum Static, Dhcp, Dhcpv6, Manual
  IfStatus = object
    name:    string
    state:   string
    ip4:     string
    ip6:     string
    mac:     string
    mtu:     int
    rx_bytes: uint64
    tx_bytes: uint64

proc read_sys(path: string): string =
  try: readFile(path).strip() except: ""

proc if_status(name: string): IfStatus =
  result.name  = name
  result.state = read_sys(fmt"/sys/class/net/{name}/operstate")
  result.mac   = read_sys(fmt"/sys/class/net/{name}/address")
  result.mtu   = try: parseInt(read_sys(fmt"/sys/class/net/{name}/mtu")) except: 1500
  let rx = read_sys(fmt"/sys/class/net/{name}/statistics/rx_bytes")
  let tx = read_sys(fmt"/sys/class/net/{name}/statistics/tx_bytes")
  result.rx_bytes = try: parseUInt(rx) except: 0
  result.tx_bytes = try: parseUInt(tx) except: 0
  # Get IPv4 from ip addr
  let (out, _) = execCmdEx(fmt"ip addr show {name} 2>/dev/null")
  for line in out.splitLines():
    let s = line.strip()
    if s.startsWith("inet ") and not s.contains("127.0"):
      result.ip4 = s.split(' ')[1]
    elif s.startsWith("inet6 ") and not s.contains("fe80"):
      result.ip6 = s.split(' ')[1]

proc human_bytes(b: uint64): string =
  if b >= 1_073_741_824: fmt"{b div 1_073_741_824}GB"
  elif b >= 1_048_576:   fmt"{b div 1_048_576}MB"
  elif b >= 1024:        fmt"{b div 1024}KB"
  else:                  fmt"{b}B"

proc list_interfaces(): seq[string] =
  result = @[]
  for _, path in walkDir("/sys/class/net"):
    let name = path.extractFilename
    if name != "lo": result.add(name)

proc cmd_list() =
  let ifaces = list_interfaces()
  if ifaces.len == 0: echo "No network interfaces found."; return
  echo fmt"{'Interface':<14} {'State':<8} {'IPv4':<20} {'MAC':<18} {'RX':<10} TX"
  echo "-".repeat(80)
  for name in ifaces:
    let s = if_status(name)
    let state_color = if s.state == "up": "\e[32m" elif s.state == "down": "\e[31m" else: "\e[33m"
    echo fmt"{name:<14} {state_color}{s.state:<8}\e[0m {s.ip4:<20} {s.mac:<18} {human_bytes(s.rx_bytes):<10} {human_bytes(s.tx_bytes)}"

proc cmd_up(name: string) =
  let code = execCmd(fmt"ip link set {name} up 2>/dev/null")
  if code == 0: echo fmt"✓ {name} is up"
  else: echo fmt"✗ Failed to bring up {name}"

proc cmd_down(name: string) =
  let code = execCmd(fmt"ip link set {name} down 2>/dev/null")
  if code == 0: echo fmt"✓ {name} is down"
  else: echo fmt"✗ Failed to bring down {name}"

proc cmd_dhcp(name: string) =
  echo fmt"Requesting DHCP lease on {name}..."
  let code = execCmd(fmt"udhcpc -i {name} -n -q 2>/dev/null || dhclient {name} 2>/dev/null")
  if code == 0:
    let s = if_status(name)
    echo fmt"✓ Assigned: {s.ip4}"
  else: echo fmt"✗ DHCP failed on {name}"

proc cmd_static(name, ip, mask, gw: string) =
  discard execCmd(fmt"ip addr flush dev {name} 2>/dev/null")
  discard execCmd(fmt"ip addr add {ip}/{mask} dev {name} 2>/dev/null")
  if gw.len > 0:
    discard execCmd(fmt"ip route add default via {gw} dev {name} 2>/dev/null")
  echo fmt"✓ Set {name}: {ip}/{mask} gw={gw}"

proc cmd_dns(servers: seq[string]) =
  var content = "# Generated by sigma-netctl\n"
  for s in servers: content.add(fmt"nameserver {s}\n")
  writeFile("/etc/resolv.conf", content)
  echo "✓ DNS updated: " & servers.join(", ")

proc cmd_show(name: string) =
  let s = if_status(name)
  echo fmt"Interface:  {s.name}"
  echo fmt"State:      {s.state}"
  echo fmt"IPv4:       {if s.ip4.len > 0: s.ip4 else: '(none)'}"
  echo fmt"IPv6:       {if s.ip6.len > 0: s.ip6 else: '(none)'}"
  echo fmt"MAC:        {s.mac}"
  echo fmt"MTU:        {s.mtu}"
  echo fmt"RX / TX:    {human_bytes(s.rx_bytes)} / {human_bytes(s.tx_bytes)}"

proc cmd_scan(name: string) =
  echo fmt"Scanning for Wi-Fi networks on {name}..."
  let (out, _) = execCmdEx(fmt"iw dev {name} scan 2>/dev/null | grep -E 'SSID:|signal:' ")
  if out.strip().len > 0: echo out
  else: echo "No networks found (ensure interface is up and supports Wi-Fi)"

proc cmd_connect_wifi(name, ssid, password: string) =
  echo fmt"Connecting {name} to '{ssid}'..."
  # Write wpa_supplicant config
  let conf = fmt"""network={{
  ssid="{ssid}"
  psk="{password}"
  key_mgmt=WPA-PSK
}}"""
  writeFile("/tmp/sigma_wpa.conf", conf)
  discard execCmd(fmt"wpa_supplicant -B -i {name} -c /tmp/sigma_wpa.conf 2>/dev/null")
  discard execCmd(fmt"udhcpc -i {name} -n -q 2>/dev/null")
  let s = if_status(name)
  if s.ip4.len > 0: echo fmt"✓ Connected: {s.ip4}"
  else: echo "✗ Connection failed"

proc usage() =
  echo "sigma-netctl — Network Interface Controller v15.0"
  echo "Usage:"
  echo "  sigma-netctl list                        List all interfaces"
  echo "  sigma-netctl show <iface>                Show interface details"
  echo "  sigma-netctl up <iface>                  Bring interface up"
  echo "  sigma-netctl down <iface>                Bring interface down"
  echo "  sigma-netctl dhcp <iface>                Request DHCP lease"
  echo "  sigma-netctl static <iface> <ip> <mask> [gw]  Set static IP"
  echo "  sigma-netctl dns <server1> [server2...]  Set DNS servers"
  echo "  sigma-netctl scan <iface>                Scan Wi-Fi networks"
  echo "  sigma-netctl wifi <iface> <ssid> <pass>  Connect to Wi-Fi"

proc main() =
  let args = commandLineParams()
  if args.len == 0: usage(); quit(0)
  case args[0]
  of "list":   cmd_list()
  of "show":
    if args.len < 2: echo "Usage: sigma-netctl show <iface>"; quit(1)
    cmd_show(args[1])
  of "up":
    if args.len < 2: echo "Usage: sigma-netctl up <iface>"; quit(1)
    cmd_up(args[1])
  of "down":
    if args.len < 2: echo "Usage: sigma-netctl down <iface>"; quit(1)
    cmd_down(args[1])
  of "dhcp":
    if args.len < 2: echo "Usage: sigma-netctl dhcp <iface>"; quit(1)
    cmd_up(args[1]); cmd_dhcp(args[1])
  of "static":
    if args.len < 4: echo "Usage: sigma-netctl static <iface> <ip> <mask> [gw]"; quit(1)
    cmd_static(args[1], args[2], args[3], if args.len > 4: args[4] else: "")
  of "dns":
    if args.len < 2: echo "Usage: sigma-netctl dns <server1> ..."; quit(1)
    cmd_dns(args[1..^1])
  of "scan":
    if args.len < 2: echo "Usage: sigma-netctl scan <iface>"; quit(1)
    cmd_scan(args[1])
  of "wifi":
    if args.len < 4: echo "Usage: sigma-netctl wifi <iface> <ssid> <pass>"; quit(1)
    cmd_up(args[1]); cmd_connect_wifi(args[1], args[2], args[3])
  else: usage(); quit(1)

main()
