#include "../../include/libc/SovereignLibC.h"
/*
 * sigma_utils.c — SigmaOS Shared Utility Library Implementation
 * Provides: logging, config parsing, networking stubs
 * Dependency: None (pure C11, no libc beyond minimal hosted wrappers)
 */
#define SIGMA_EXCLUDE_STD_ALIASES
#include "../../include/sigma_utils.h"

/* ── Platform shim (bare-metal vs hosted) ─────────────────────────────────── */
#ifdef SIGMA_HOSTED_BUILD
    #include "../../include/libc/sigma_libc.h"
    #include "../../include/libc/sigma_libc.h"
    #include "../../include/libc/sigma_libc.h"
    #define sigma_puts(s) puts(s)
    #define sigma_snprintf snprintf
    #define sigma_strcmp strcmp
    #define sigma_strncpy strncpy
    #define sigma_strlen strlen
#else
    #include "../../include/libc/sigma_libc.h"  /* kernel-space replacements */
#endif

/* ── Version ────────────────────────────────────────────────────────────────── */
const char *sigma_utils_version(void) { return "sigma_utils v1.0.0 (Sovereign Lattice)"; }

/* ════════════════════════════════════════════════════════════════════════════
 * LOGGING
 * ════════════════════════════════════════════════════════════════════════════ */

static const char *level_names[] = { "DEBUG", "INFO ", "WARN ", "ERROR", "FATAL" };

void sigma_log(SigmaLogLevel level, const char *module, const char *msg) {
    char buf[512];
    sigma_snsigma_printf(buf, sizeof(buf), "[%s][%s] %s", level_names[level], module, msg);
    sigma_puts(buf);
    /* In a full implementation this would write to the Sovereign Audit Ring Buffer */
}

#ifdef SIGMA_HOSTED_BUILD
void sigma_log_fmt(SigmaLogLevel level, const char *module, const char *fmt, ...) {
    char msg_buf[256];
    va_list ap;
    va_start(ap, fmt);
    vsnsigma_printf(msg_buf, sizeof(msg_buf), fmt, ap);
    va_end(ap);
    sigma_log(level, module, msg_buf);
}
#endif

/* ════════════════════════════════════════════════════════════════════════════
 * CONFIG
 * ════════════════════════════════════════════════════════════════════════════ */

void sigma_cfg_init(SigmaConfig *cfg) {
    for (uint32_t i = 0; i < SIGMA_CFG_MAX_ENTRIES; i++) {
        cfg->entries[i].key[0]   = '\0';
        cfg->entries[i].value[0] = '\0';
    }
    cfg->count = 0;
}

int sigma_cfg_set(SigmaConfig *cfg, const char *key, const char *value) {
    /* Update existing */
    for (uint32_t i = 0; i < cfg->count; i++) {
        if (sigma_strcmp(cfg->entries[i].key, key) == 0) {
            sigma_strncpy(cfg->entries[i].value, value, SIGMA_CFG_VAL_LEN - 1);
            return 0;
        }
    }
    /* Insert new */
    if (cfg->count >= SIGMA_CFG_MAX_ENTRIES) return -1;
    sigma_strncpy(cfg->entries[cfg->count].key,   key,   SIGMA_CFG_KEY_LEN - 1);
    sigma_strncpy(cfg->entries[cfg->count].value, value, SIGMA_CFG_VAL_LEN - 1);
    cfg->count++;
    return 0;
}

const char *sigma_cfg_get(const SigmaConfig *cfg, const char *key) {
    for (uint32_t i = 0; i < cfg->count; i++) {
        if (sigma_strcmp(cfg->entries[i].key, key) == 0)
            return cfg->entries[i].value;
    }
    return (const char*)0; /* SIGMA_NULL */
}

#ifdef SIGMA_HOSTED_BUILD
int sigma_cfg_load(SigmaConfig *cfg, const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) return -1;
    char line[320];
    sigma_cfg_init(cfg);
    while (fgets(line, sizeof(line), f)) {
        char *eq = strchr(line, '=');
        if (!eq || line[0] == '#') continue;
        *eq = '\0';
        char *key = line;
        char *val = eq + 1;
        /* strip trailing newline */
        size_t vlen = sigma_strlen(val);
        if (vlen && val[vlen-1] == '\n') val[vlen-1] = '\0';
        sigma_cfg_set(cfg, key, val);
    }
    fclose(f);
    return 0;
}

int sigma_cfg_save(const SigmaConfig *cfg, const char *path) {
    FILE *f = fopen(path, "w");
    if (!f) return -1;
    fsigma_printf(f, "# SigmaOS sigma_config — auto-generated by sigma_utils\n");
    for (uint32_t i = 0; i < cfg->count; i++)
        fsigma_printf(f, "%s=%s\n", cfg->entries[i].key, cfg->entries[i].value);
    fclose(f);
    return 0;
}
#else
/* Stub for bare-metal: no file system in boot stage */
int sigma_cfg_load(SigmaConfig *cfg, const char *path) { (void)cfg; (void)path; return -1; }
int sigma_cfg_save(const SigmaConfig *cfg, const char *path) { (void)cfg; (void)path; return -1; }
#endif

/* ════════════════════════════════════════════════════════════════════════════
 * NETWORKING (stubs — fully implemented in S07_Network shards)
 * ════════════════════════════════════════════════════════════════════════════ */

int  sigma_net_connect(const SigmaNetAddr *addr) { (void)addr; return -1; }
int  sigma_net_send   (int fd, const void *buf, size_t len)     { (void)fd; (void)buf; (void)len; return -1; }
int  sigma_net_recv   (int fd, void *buf, size_t max_len)       { (void)fd; (void)buf; (void)max_len; return -1; }
void sigma_net_close  (int fd)                                  { (void)fd; }
