
# ================================================================
# SigmaOS â€” Extract Inline Styles from zenith.html
# Converts all style="..." attributes to data-driven CSS classes
# and appends them to ui/themes/zenith_inline.css
# ================================================================

$html  = Get-Content 'zenith.html' -Raw
$cssOut = [System.Text.StringBuilder]::new()
$null   = $cssOut.AppendLine("/* =====================================================")
$null   = $cssOut.AppendLine(" * zenith_inline.css â€” Auto-extracted inline styles")
$null   = $cssOut.AppendLine(" * Generated by fix_zenith_inline.ps1")
$null   = $cssOut.AppendLine(" * DO NOT edit manually â€” regenerate via script")
$null   = $cssOut.AppendLine(" * ===================================================== */")
$null   = $cssOut.AppendLine("")

# Track: styleValue -> className mappings to deduplicate
$styleMap  = [System.Collections.Generic.Dictionary[string,string]]::new()
$classCounter = 0

# Named replacements for known semantic patterns (improves readability)
$namedClasses = [ordered]@{
    'min-height: 150px; background: rgba(0,0,0,0.5); border-top: 1px solid rgba(0,255,255,0.2); border-bottom: 1px solid rgba(0,255,255,0.2); padding: 10px; font-size: 0.85em; display: flex; flex-direction: column; justify-content: center; align-items: center;' = 'live-canvas-inner'
    'color: var(--text-muted);' = 'text-muted-label'
    'margin-top: 10px; display: flex; flex-direction: column; gap: 8px;' = 'shard-list'
    'background: rgba(255,255,255,0.05); padding: 8px; border-radius: 6px; font-size: 0.8em; display: flex; justify-content: space-between; align-items: center;' = 'market-item-inner'
    'background: rgba(255,255,255,0.05); padding: 8px; border-radius: 6px; font-size: 0.8em;' = 'app-shard-inner'
    'display: flex; justify-content: space-between; margin-bottom: 4px;' = 'shard-row'
    'height: 4px;' = 'stat-bar-thin'
    'width: 100%;' = 'stat-full'
    'width: 85%;' = 'stat-85'
    'width: 0%;' = 'stat-zero'
    'position: fixed; bottom: 60px; right: 20px; width: 350px; height: 220px; background: rgba(0,0,0,0.85); backdrop-filter: blur(20px); border: 1px solid rgba(0,255,255,0.2); border-radius: 12px; display: flex; flex-direction: column; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.5); z-index: 1000;' = 'kernel-console-panel'
    'background: rgba(255,255,255,0.05); padding: 8px 12px; font-size: 0.7em; color: var(--accent); display: flex; justify-content: space-between; border-bottom: 1px solid rgba(255,255,255,0.1);' = 'console-header-bar'
    'flex: 1; padding: 10px; font-family: ''JetBrains Mono'', monospace; font-size: 0.75em; color: rgba(255,255,255,0.8); overflow-y: auto;' = 'console-output-area'
    'margin-top: 10px; max-height: 40px; overflow: hidden; font-size: 0.8em; color: var(--accent);' = 'cognitive-queue-inner'
    'position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none;' = 'mesh-overlay-svg'
}

# Pre-populate styleMap with named classes
foreach ($kv in $namedClasses.GetEnumerator()) {
    $styleMap[$kv.Key] = $kv.Value
    $null = $cssOut.AppendLine(".zen-$($kv.Value) {")
    $null = $cssOut.AppendLine("    $($kv.Key.TrimEnd(';').Replace('; ', ';`n    ').Replace(';', ';'))")
    $null = $cssOut.AppendLine("}")
    $null = $cssOut.AppendLine("")
}

# Find all style="..." attributes
$regex = [regex]'(?s)\sstyle="([^"]+)"'
$regexMatches = $regex.Matches($html)

foreach ($m in $regexMatches) {
    $styleVal = $m.Groups[1].Value.Trim()
    if (-not $styleMap.ContainsKey($styleVal)) {
        $classCounter++
        $className = "zen-auto-$classCounter"
        $styleMap[$styleVal] = $className

        # Write the CSS class
        $null = $cssOut.AppendLine(".$className {")
        # Split declarations and indent each
        $decls = $styleVal -split ';\s*' | Where-Object { $_.Trim() -ne '' }
        foreach ($d in $decls) {
            $null = $cssOut.AppendLine("    $($d.Trim());")
        }
        $null = $cssOut.AppendLine("}")
        $null = $cssOut.AppendLine("")
    }
}

# Write the CSS file
Set-Content 'ui\themes\zenith_inline.css' -Value $cssOut.ToString() -Encoding UTF8
Write-Host "[CREATED] ui/themes/zenith_inline.css with $($styleMap.Count) classes"

# ----------------------------------------------------------------
# Now patch zenith.html: replace style="VALUE" with the class
# ----------------------------------------------------------------
$patchedHtml = $html

foreach ($kv in $styleMap.GetEnumerator()) {
    $styleAttr   = ' style="' + $kv.Key + '"'
    $replacement = ' class="' + $kv.Value + '"'
    
    # If the element already has a class="..." attribute, append to it instead
    # Use regex to detect existing class attr on same tag
    $patchedHtml = $patchedHtml.Replace($styleAttr, " data-zenclass=`"$($kv.Value)`"")
}

# Second pass: convert data-zenclass back to proper class merges
# For elements already having class="...", merge:
$patchedHtml = [regex]::Replace($patchedHtml, '(class="[^"]+")([^>]*?) data-zenclass="([^"]+)"', {
    param($m)
    $existing = $m.Groups[1].Value -replace '"$', ''
    $extra    = $m.Groups[3].Value
    $rest     = $m.Groups[2].Value
    "$existing $extra`"$rest"
})

# For elements with ONLY data-zenclass (no existing class), convert to class:
$patchedHtml = $patchedHtml -replace ' data-zenclass="([^"]+)"', ' class="$1"'

Set-Content 'zenith.html' -Value $patchedHtml -Encoding UTF8
Write-Host "[PATCHED] zenith.html â€” all inline styles replaced with CSS classes"

# ----------------------------------------------------------------
# Ensure zenith.html references zenith_inline.css
# ----------------------------------------------------------------
$zenHtml = Get-Content 'zenith.html' -Raw
if ($zenHtml -notmatch 'zenith_inline\.css') {
    $zenHtml = $zenHtml -replace '(<link[^>]+zenith_desktop\.css[^>]*>)', '$1' + "`n    <link rel=`"stylesheet`" href=`"ui/themes/zenith_inline.css`">"
    Set-Content 'zenith.html' -Value $zenHtml -Encoding UTF8
    Write-Host "[LINKED] zenith_inline.css added to zenith.html <head>"
}

Write-Host ""
Write-Host "=== zenith.html inline style extraction complete. ==="

