// Archive Subsystem for SigmaOS
// Inspired by BSD libarchive, Linux GNU tar, zip/unzip, cpio, and ISO-9660 image tools.

/// Archive formats supported by SigmaOS
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ArchiveFormat {
    Tar,
    Zip,
    Cpio,
    Iso9660,
    Ar,
}

impl ArchiveFormat {
    pub fn as_str(&self) -> &'static str {
        match self {
            ArchiveFormat::Tar => "TAR Archive (.tar)",
            ArchiveFormat::Zip => "ZIP Compressed Archive (.zip)",
            ArchiveFormat::Cpio => "CPIO Initramfs Archive (.cpio)",
            ArchiveFormat::Iso9660 => "ISO-9660 Disk Image (.iso)",
            ArchiveFormat::Ar => "Unix Static Library Archive (.a / .ar)",
        }
    }
}

/// Compression codecs
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompressionCodec {
    None,
    Gzip,
    Bzip2,
    Xz,
    Zstd,
}

/// Archive entry type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EntryType {
    RegularFile,
    Directory,
    Symlink,
}

/// Archive entry record (file metadata & payload)
#[derive(Debug, Clone)]
pub struct ArchiveEntry {
    pub path: String,
    pub size_bytes: usize,
    pub permissions_mode: u32, // POSIX octal mode (e.g. 0o755, 0o644)
    pub uid: u32,
    pub gid: u32,
    pub mtime: u64,
    pub entry_type: EntryType,
    pub payload: Vec<u8>,
    pub checksum_crc32: u32,
}

impl ArchiveEntry {
    pub fn new_file(path: &str, payload: &[u8], permissions: u32) -> Self {
        let mut crc = 0u32;
        for &b in payload {
            crc = crc.wrapping_add(b as u32).wrapping_mul(31);
        }

        Self {
            path: path.to_string(),
            size_bytes: payload.len(),
            permissions_mode: permissions,
            uid: 1000,
            gid: 1000,
            mtime: 1000,
            entry_type: EntryType::RegularFile,
            payload: payload.to_vec(),
            checksum_crc32: crc,
        }
    }

    pub fn new_dir(path: &str, permissions: u32) -> Self {
        Self {
            path: path.to_string(),
            size_bytes: 0,
            permissions_mode: permissions,
            uid: 0,
            gid: 0,
            mtime: 1000,
            entry_type: EntryType::Directory,
            payload: Vec::new(),
            checksum_crc32: 0,
        }
    }
}

/// Complete Archive Image Container
#[derive(Debug, Clone)]
pub struct ArchiveImage {
    pub format: ArchiveFormat,
    pub codec: CompressionCodec,
    pub entries: Vec<ArchiveEntry>,
    pub comment: String,
}

/// Archive Manager Engine (BSD libarchive & GNU tar parity)
pub struct ArchiveManager {
    pub created_archives_count: usize,
}

impl ArchiveManager {
    pub fn new() -> Self {
        Self {
            created_archives_count: 0,
        }
    }

    /// Create a new archive containing the provided entries
    pub fn create_archive(&mut self, format: ArchiveFormat, codec: CompressionCodec, entries: Vec<ArchiveEntry>) -> ArchiveImage {
        self.created_archives_count += 1;
        ArchiveImage {
            format,
            codec,
            entries,
            comment: format!("Generated by SigmaOS Archive Subsystem ({:?})", format),
        }
    }

    /// Extract matching entries from an archive image
    pub fn extract_entry<'a>(&self, archive: &'a ArchiveImage, path: &str) -> Option<&'a ArchiveEntry> {
        archive.entries.iter().find(|e| e.path == path)
    }

    /// Verify integrity of all entries in an archive
    pub fn verify_archive_integrity(&self, archive: &ArchiveImage) -> bool {
        for entry in &archive.entries {
            if entry.entry_type == EntryType::RegularFile {
                let mut computed_crc = 0u32;
                for &b in &entry.payload {
                    computed_crc = computed_crc.wrapping_add(b as u32).wrapping_mul(31);
                }
                if computed_crc != entry.checksum_crc32 {
                    return false;
                }
            }
        }
        true
    }

    /// List all file paths contained in the archive
    pub fn list_files(&self, archive: &ArchiveImage) -> Vec<String> {
        archive.entries.iter().map(|e| e.path.clone()).collect()
    }
}

impl Default for ArchiveManager {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_archive_creation_extraction_and_verification() {
        let mut mgr = ArchiveManager::new();

        let f1 = ArchiveEntry::new_file("usr/bin/sigma-cli", b"#!/bin/sh\necho SigmaOS", 0o755);
        let f2 = ArchiveEntry::new_file("etc/sigma.conf", b"key=value\n", 0o644);
        let d1 = ArchiveEntry::new_dir("usr/bin", 0o755);

        let archive = mgr.create_archive(ArchiveFormat::Tar, CompressionCodec::Gzip, vec![d1, f1, f2]);

        assert_eq!(archive.format, ArchiveFormat::Tar);
        assert_eq!(archive.codec, CompressionCodec::Gzip);
        assert_eq!(archive.entries.len(), 3);

        // Verify integrity
        assert!(mgr.verify_archive_integrity(&archive));

        // Extract file entry
        let extracted = mgr.extract_entry(&archive, "etc/sigma.conf").unwrap();
        assert_eq!(extracted.payload, b"key=value\n");

        let files = mgr.list_files(&archive);
        assert_eq!(files, vec!["usr/bin", "usr/bin/sigma-cli", "etc/sigma.conf"]);
    }
}
