# src/ai/code_generator.nim
# AI-powered code generation for SigmaOS plugins/themes/tools
# Pure Nim (no Python/JS dependencies)

import strutils, sequtils, tables, json, strformat

type
  CodeLanguage* = enum
    Rust, Zig, Nim

  PluginTarget* = enum
    Shell, Compositor, Kernel, Theme, Tool

  PluginSpec* = object
    name*: string
    description*: string
    language*: CodeLanguage
    target*: PluginTarget
    features*: seq[string]
    dependencies*: seq[string]

  GeneratedCode* = object
    sourceCode*: string
    buildScript*: string
    manifest*: string
    tests*: string

  CodeTemplate* = object
    header*: string
    imports*: string
    structDef*: string
    methods*: string
    tests*: string

  CodeGenerator* = object
    templates: Table[CodeLanguage, CodeTemplate]
    llmBackend: LLMBackend
    validator: CodeValidator

  LLMBackend* = object
    modelPath*: string
    maxTokens*: int
    temperature*: float

  CodeValidator* = object
    syntaxChecks*: bool
    typeChecks*: bool
    securityScans*: bool

  ValidationResult* = object
    valid*: bool
    errors*: seq[string]
    warnings*: seq[string]
    suggestions*: seq[string]

# Initialize code generator
proc newCodeGenerator*(): CodeGenerator =
  result.templates = initTable[CodeLanguage, CodeTemplate]()
  result.llmBackend = LLMBackend(
    modelPath: "/var/lib/sigma/models/codegen",
    maxTokens: 2048,
    temperature: 0.7
  )
  result.validator = CodeValidator(
    syntaxChecks: true,
    typeChecks: true,
    securityScans: true
  )
  
  # Initialize templates
  result.initializeTemplates()

# Initialize language templates
proc initializeTemplates(gen: var CodeGenerator) =
  # Rust template
  gen.templates[Rust] = CodeTemplate(
    header: """// {name}
// {description}
// Auto-generated by SigmaOS Agent

#![no_std]

extern crate alloc;
use alloc::vec::Vec;
use alloc::string::String;
""",
    imports: """
use crate::klib::types::*;
use crate::kernel::process::*;
""",
    structDef: """
pub struct {name} {{
    // Generated fields
}}
""",
    methods: """
impl {name} {{
    pub fn new() -> Self {{
        Self {{}}
    }}
    
    pub fn initialize(&mut self) -> Result<(), Error> {{
        Ok(())
    }}
}}
""",
    tests: """
#[cfg(test)]
mod tests {{
    use super::*;
    
    #[test]
    fn test_initialization() {{
        let mut instance = {name}::new();
        assert!(instance.initialize().is_ok());
    }}
}}
"""
  )
  
  # Zig template
  gen.templates[Zig] = CodeTemplate(
    header: """// {name}
// {description}
// Auto-generated by SigmaOS Agent

const std = @import("std");
""",
    imports: """const kernel = @import("kernel");
const types = @import("types");
""",
    structDef: """
pub const {name} = struct {{
    // Generated fields
    
    pub fn init() {name} {{
        return .{{}};
    }}
}};
""",
    methods: """
pub fn initialize(self: *{name}) !void {{
    // Initialization logic
}}

pub fn deinit(self: *{name}) void {{
    // Cleanup logic
}}
""",
    tests: """
test "{name} initialization" {{
    var instance = {name}.init();
    try instance.initialize();
    defer instance.deinit();
}}
"""
  )
  
  # Nim template
  gen.templates[Nim] = CodeTemplate(
    header: """# {name}
# {description}
# Auto-generated by SigmaOS Agent

import std/[tables, sequtils, strutils]
""",
    imports: """import sigma/[types, kernel, process]
""",
    structDef: """
type {name}* = object
  # Generated fields
""",
    methods: """
proc new{name}*(): {name} =
  result = {name}()

proc initialize*(self: var {name}) =
  # Initialization logic
  discard

proc cleanup*(self: var {name}) =
  # Cleanup logic
  discard
""",
    tests: """
when isMainModule:
  var instance = new{name}()
  instance.initialize()
  instance.cleanup()
  echo "{name} test passed"
"""
  )

# Generate plugin code from specification
proc generatePlugin*(gen: var CodeGenerator, spec: PluginSpec): GeneratedCode =
  result = GeneratedCode()
  
  case spec.language
  of Rust:
    result = gen.generateRustPlugin(spec)
  of Zig:
    result = gen.generateZigPlugin(spec)
  of Nim:
    result = gen.generateNimPlugin(spec)
  
  # Validate generated code
  let validation = gen.validate(result.sourceCode, spec.language)
  if not validation.valid:
    echo &"Warning: Generated code has validation issues"
    for error in validation.errors:
      echo &"  ERROR: {error}"
    for warning in validation.warnings:
      echo &"  WARNING: {warning}"

# Generate Rust plugin
proc generateRustPlugin(gen: CodeGenerator, spec: PluginSpec): GeneratedCode =
  let template = gen.templates[Rust]
  
  var code = template.header
    .replace("{name}", spec.name)
    .replace("{description}", spec.description)
  
  code.add(template.imports)
  code.add("\n")
  code.add(template.structDef.replace("{name}", spec.name))
  code.add("\n")
  code.add(template.methods.replace("{name}", spec.name))
  code.add("\n")
  code.add(template.tests.replace("{name}", spec.name))
  
  result.sourceCode = code
  result.buildScript = gen.generateRustBuildScript(spec)
  result.manifest = gen.generateCargoToml(spec)
  result.tests = template.tests.replace("{name}", spec.name)

# Generate Zig plugin
proc generateZigPlugin(gen: CodeGenerator, spec: PluginSpec): GeneratedCode =
  let template = gen.templates[Zig]
  
  var code = template.header
    .replace("{name}", spec.name)
    .replace("{description}", spec.description)
  
  code.add(template.imports)
  code.add("\n")
  code.add(template.structDef.replace("{name}", spec.name))
  code.add("\n")
  code.add(template.methods.replace("{name}", spec.name))
  code.add("\n")
  code.add(template.tests.replace("{name}", spec.name))
  
  result.sourceCode = code
  result.buildScript = gen.generateZigBuildScript(spec)
  result.manifest = gen.generateZigBuild(spec)
  result.tests = template.tests.replace("{name}", spec.name)

# Generate Nim plugin
proc generateNimPlugin(gen: CodeGenerator, spec: PluginSpec): GeneratedCode =
  let template = gen.templates[Nim]
  
  var code = template.header
    .replace("{name}", spec.name)
    .replace("{description}", spec.description)
  
  code.add(template.imports)
  code.add("\n")
  code.add(template.structDef.replace("{name}", spec.name))
  code.add("\n")
  code.add(template.methods.replace("{name}", spec.name))
  code.add("\n")
  code.add(template.tests.replace("{name}", spec.name))
  
  result.sourceCode = code
  result.buildScript = gen.generateNimBuildScript(spec)
  result.manifest = gen.generateNimbleFile(spec)
  result.tests = template.tests.replace("{name}", spec.name)

# Generate Cargo.toml
proc generateCargoToml(gen: CodeGenerator, spec: PluginSpec): string =
  result = &"""[package]
name = "{spec.name.toLowerAscii()}"
version = "0.1.0"
edition = "2021"
authors = ["SigmaOS Agent"]

[lib]
name = "{spec.name.toLowerAscii()}"
crate-type = ["cdylib", "rlib"]

[dependencies]
"""
  for dep in spec.dependencies:
    result.add(&"{dep} = \"*\"\n")

# Generate build.zig
proc generateZigBuild(gen: CodeGenerator, spec: PluginSpec): string =
  result = &"""const std = @import("std");

pub fn build(b: *std.Build) void {{
    const target = b.standardTargetOptions(.{{}});
    const optimize = b.standardOptimizeOption(.{{}});
    
    const lib = b.addStaticLibrary(.{{
        .name = "{spec.name.toLowerAscii()}",
        .root_source_file = .{{ .path = "src/{spec.name.toLowerAscii()}.zig" }},
        .target = target,
        .optimize = optimize,
    }});
    
    b.installArtifact(lib);
    
    const tests = b.addTest(.{{
        .root_source_file = .{{ .path = "src/{spec.name.toLowerAscii()}.zig" }},
        .target = target,
        .optimize = optimize,
    }});
    
    const test_step = b.step("test", "Run tests");
    test_step.dependOn(&tests.step);
}}
"""

# Generate .nimble file
proc generateNimbleFile(gen: CodeGenerator, spec: PluginSpec): string =
  result = &"""# Package

version       = "0.1.0"
author        = "SigmaOS Agent"
description   = "{spec.description}"
license       = "MIT"

# Dependencies

requires "nim >= 1.6.0"
"""
  for dep in spec.dependencies:
    result.add(&"requires \"{dep}\"\n")

# Generate build scripts
proc generateRustBuildScript(gen: CodeGenerator, spec: PluginSpec): string =
  result = """#!/bin/bash
cargo build --release
cargo test
"""

proc generateZigBuildScript(gen: CodeGenerator, spec: PluginSpec): string =
  result = """#!/bin/bash
zig build
zig build test
"""

proc generateNimBuildScript(gen: CodeGenerator, spec: PluginSpec): string =
  result = """#!/bin/bash
nim c -d:release --noMain --app:lib src/""" & spec.name.toLowerAscii() & """.nim
nim c -r """ & spec.name.toLowerAscii() & """.nim
"""

# Validate generated code
proc validate(gen: CodeGenerator, code: string, lang: CodeLanguage): ValidationResult =
  result.valid = true
  result.errors = @[]
  result.warnings = @[]
  result.suggestions = @[]
  
  # Basic syntax checks
  if code.len == 0:
    result.valid = false
    result.errors.add("Empty code generated")
    return
  
  # Language-specific validation
  case lang
  of Rust:
    # Check for unsafe blocks
    if code.contains("unsafe"):
      result.warnings.add("Contains unsafe code blocks")
    
    # Check for unwrap() calls
    if code.contains(".unwrap()"):
      result.warnings.add("Contains unwrap() calls - consider error handling")
    
    # Check for proper error handling
    if not code.contains("Result<"):
      result.suggestions.add("Consider adding Result<T, E> error types")
  
  of Zig:
    # Check for error handling
    if not code.contains("!"):
      result.suggestions.add("Consider adding error unions")
    
    # Check for proper cleanup
    if code.contains("init") and not code.contains("deinit"):
      result.warnings.add("Init found but no corresponding deinit")
  
  of Nim:
    # Check for exception handling
    if code.contains("raise") and not code.contains("try"):
      result.warnings.add("Raises exceptions but no try blocks found")
    
    # Check for proper cleanup
    if code.contains("new") and not code.contains("cleanup"):
      result.suggestions.add("Consider adding cleanup procedures")

# Generate theme code
proc generateTheme*(gen: var CodeGenerator, name: string, colors: Table[string, string]): GeneratedCode =
  result.sourceCode = &"""# {name} Theme
# Auto-generated by SigmaOS Agent

type Theme* = object
  background*: string
  foreground*: string
  accent*: string
  border*: string

proc new{name}Theme*(): Theme =
  result = Theme(
"""
  
  for key, value in colors:
    result.sourceCode.add(&"    {key}: \"{value}\",\n")
  
  result.sourceCode.add("  )\n")

# Generate widget code
proc generateWidget*(gen: var CodeGenerator, name: string, widgetType: string): GeneratedCode =
  let spec = PluginSpec(
    name: name,
    description: &"Auto-generated {widgetType} widget",
    language: Nim,
    target: Shell,
    features: @[widgetType],
    dependencies: @["sigma_shell"]
  )
  
  result = gen.generatePlugin(spec)

# Export C-compatible API for Rust FFI
proc code_generator_create(): ptr CodeGenerator {.exportc.} =
  var gen = newCodeGenerator()
  return addr gen

proc code_generator_destroy(gen: ptr CodeGenerator) {.exportc.} =
  # Cleanup
  discard

# Tests
when isMainModule:
  echo "Testing Code Generator..."
  
  var gen = newCodeGenerator()
  
  let spec = PluginSpec(
    name: "TestPlugin",
    description: "A test plugin",
    language: Rust,
    target: Shell,
    features: @["test"],
    dependencies: @[]
  )
  
  let code = gen.generatePlugin(spec)
  echo "Generated Rust code:"
  echo code.sourceCode
  echo "\nBuild script:"
  echo code.buildScript
  echo "\nManifest:"
  echo code.manifest
  
  echo "\n✓ Code generator tests passed"
