# Generated method: SovereignCodeForge._build_ui
import tkinter as tk
from tkinter import ttk, filedialog, messagebox, scrolledtext
import os, re, sys, subprocess, threading
from typing import Any, Optional

class SovereignCodeForge:
    def _build_ui(self):
        self.toolbar = tk.Frame(self, bg=PAL['gutter'], height=48, padx=20)
        self.toolbar.pack(side='top', fill='x')
        self.toolbar.pack_propagate(False)
        tk.Label(self.toolbar, text=f"{ICONS.get('code', '⚙')} CODEFORGE PRO", font=('Segoe UI', 11, 'bold'), fg=PAL['accent'], bg=PAL['gutter']).pack(side='left', padx=(0, 20))
        btns = [(f"{ICONS.get('fs', '📁')} OPEN", self.load_file, None), (f"{ICONS.get('snapshots', '💾')} SAVE", self.save_file, None), (f"{ICONS.get('perf', '▶')} RUN", self.run_code, PAL['success']), (f"{ICONS.get('minimalist', '■')} STOP", self.stop_exec, PAL['error']), (f"{ICONS.get('warden', '✨')} LINT", self._trigger_lint, None)]
        for txt, cmd, col in btns:
            b = tk.Button(self.toolbar, text=txt, font=('Segoe UI', 8, 'bold'), bg=PAL['sidebar'], fg=col or 'white', relief='flat', padx=14, pady=8, command=cmd, activebackground=PAL['accent'], activeforeground='white')
            b.pack(side='left', padx=4)
            b.bind('<Enter>', lambda e, bt=b: bt.config(bg=PAL['accent']))
            b.bind('<Leave>', lambda e, bt=b, c=PAL['sidebar']: bt.config(bg=c))
        self.file_lbl = tk.Label(self.toolbar, text='[New File]', font=('Segoe UI', 9), fg=PAL['dim'], bg=PAL['gutter'])
        self.file_lbl.pack(side='left', padx=20)
        self.tab_bar = tk.Frame(self, bg=PAL['gutter'], height=32)
        self.tab_bar.pack(fill='x')
        self._active_tab = tk.Label(self.tab_bar, text=f"  {ICONS.get('code', '🐍')} untitled.py  ×", font=('Segoe UI', 9), fg='white', bg=PAL['accent'], padx=3, pady=3)
        self._active_tab.pack(side='left')
        self.panes = ttk.PanedWindow(self, orient='horizontal')
        self.panes.pack(fill='both', expand=True)
        self.sidebar = tk.Frame(self.panes, bg=PAL['sidebar'], width=220)
        self.panes.add(self.sidebar, weight=1)
        tk.Label(self.sidebar, text=f"{ICONS.get('search', '🔎')} EXPLORER", font=('Segoe UI', 7, 'bold'), fg=PAL['dim'], bg=PAL['sidebar'], pady=8, padx=10).pack(anchor='w')
        self._tree = ttk.Treeview(self.sidebar, selectmode='browse', show='tree')
        self._tree.pack(fill='both', expand=True)
        self._populate_tree()
        self._tree.bind('<<TreeviewSelect>>', self._tree_load)
        self.v_panes = ttk.PanedWindow(self.panes, orient='vertical')
        self.panes.add(self.v_panes, weight=5)
        edit_fr = tk.Frame(self.v_panes, bg=PAL['editor'])
        self.v_panes.add(edit_fr, weight=3)
        self.num_bar = tk.Text(edit_fr, width=4, bg=PAL['gutter'], fg=PAL['line_num'], font=('Cascadia Code', 11), state='disabled', borderwidth=0, padx=5, pady=11, cursor='arrow')
        self.num_bar.pack(side='left', fill='y')
        self.txt = tk.Text(edit_fr, bg=PAL['editor'], fg=PAL['text'], insertbackground='white', font=('Cascadia Code', 11), undo=True, borderwidth=0, padx=15, pady=10, selectbackground=PAL['accent'], tabs='4c')
        self.txt.pack(side='left', fill='both', expand=True)
        scroll_e = ttk.Scrollbar(edit_fr, command=self.txt.yview)
        scroll_e.pack(side='right', fill='y')
        self.txt.config(yscrollcommand=scroll_e.set)
        self.txt.bind('<KeyRelease>', self._on_key)
        self.txt.bind('<Tab>', self._insert_tab)
        self.txt.bind('<Return>', self._auto_indent)
        term_fr = tk.Frame(self.v_panes, bg='#000')
        self.v_panes.add(term_fr, weight=1)
        tk.Label(term_fr, text=f"{ICONS.get('terminal', '🐚')} SIGMA RUNTIME", font=('Segoe UI', 7, 'bold'), fg=PAL['dim'], bg='#1a1a1a', pady=4, padx=10).pack(fill='x', anchor='w')
        self.term = scrolledtext.ScrolledText(term_fr, bg='#0d0d0d', fg=PAL['success'], font=('Cascadia Code', 10), borderwidth=0, padx=10, pady=8, insertbackground=PAL['success'])
        self.term.pack(fill='both', expand=True)
        self.term.tag_config('err', foreground=PAL['error'])
        self.term.tag_config('warn', foreground=PAL['warning'])
        self.term.tag_config('sys', foreground=PAL['dim'])
        self.term.tag_config('hint', foreground=PAL['accent'], font=('Cascadia Code', 9, 'italic'))
        self.ac_popup = tk.Listbox(self, bg=PAL['gutter'], fg=PAL['text'], font=('Cascadia Code', 10), borderwidth=1, highlightthickness=0, selectbackground=PAL['accent'])
        self.ac_popup.place_forget()
        self.ac_popup.bind('<Double-Button-1>', lambda e: self._apply_ac())
        self.status = tk.Label(self, text='CODEFORGE READY | Python Runtime | UTF-8 | Ln 1, Col 1', bg=PAL['accent'], fg='white', font=('Segoe UI', 8, 'bold'), pady=4)
        self.status.pack(side='bottom', fill='x')