//! Sovereign GRUB2 & FreeBSD Loader Inspired Boot Engine
//!
//! Provides native #![no_std] / std compatible GRUB2 & FreeBSD loader(8) capabilities for SigmaOS:
//! - GRUB2 `grub.cfg` parsing & generation (`menuentry`, `linux`, `initrd`, `chainloader`, `set default`, `set timeout`)
//! - BTRFS & ZFS boot environment snapshot selection (Timeshift/Snapper/beadm)
//! - Multiboot2, Linux x86_64, FreeBSD VNET/Jail kernel chainloading
//! - Fallback and sub-menu boot recovery policies

#![allow(dead_code)]

use std::collections::BTreeMap;
use std::string::{String, ToString};
use std::vec::Vec;
use std::format;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BootKernelType {
    SigmaOS,
    Linux,
    FreeBSD,
    OpenBSD,
    NetBSD,
    Multiboot2,
    ChainloadMBR,
    ChainloadEFI,
}

#[derive(Debug, Clone)]
pub struct ChainloadKernelSpec {
    pub title: String,
    pub kernel_type: BootKernelType,
    pub kernel_path: String,
    pub initrd_path: Option<String>,
    pub cmdline_params: String,
    pub root_device_uuid: String,
    pub snapshot_subvol: Option<String>,
}

#[derive(Debug, Clone)]
pub struct Grub2MenuEntry {
    pub index: usize,
    pub name: String,
    pub kernel_spec: ChainloadKernelSpec,
    pub is_fallback: bool,
    pub is_recovery: bool,
}

pub struct ZfsBtrfsBootSnapshotSelector {
    pub fs_type: String, // "btrfs" or "zfs"
    pub dataset_or_subvol: String,
    pub available_snapshots: Vec<(String, u64)>, // (snapshot_name, creation_sec)
    pub active_snapshot: Option<String>,
}

impl ZfsBtrfsBootSnapshotSelector {
    pub fn new(fs_type: &str, target_path: &str) -> Self {
        Self {
            fs_type: fs_type.to_string(),
            dataset_or_subvol: target_path.to_string(),
            available_snapshots: Vec::new(),
            active_snapshot: None,
        }
    }

    pub fn register_snapshot(&mut self, snap_name: &str, creation_sec: u64) {
        self.available_snapshots.push((snap_name.to_string(), creation_sec));
    }

    pub fn select_snapshot(&mut self, snap_name: &str) -> Result<(), &'static str> {
        if self.available_snapshots.iter().any(|(s, _)| s == snap_name) {
            self.active_snapshot = Some(snap_name.to_string());
            Ok(())
        } else {
            Err("Snapshot selector: Target snapshot not found")
        }
    }

    pub fn get_active_subvol_param(&self) -> Option<String> {
        self.active_snapshot.as_ref().map(|s| {
            if self.fs_type == "btrfs" {
                format!("subvol=@snapshots/{}", s)
            } else {
                format!("zfs=rpool/ROOT/{}", s)
            }
        })
    }
}

pub struct SovereignGrubConfigEngine {
    pub entries: Vec<Grub2MenuEntry>,
    pub default_entry_index: usize,
    pub timeout_seconds: u32,
    pub custom_variables: BTreeMap<String, String>,
    pub snapshot_selector: Option<ZfsBtrfsBootSnapshotSelector>,
}

impl SovereignGrubConfigEngine {
    pub fn new() -> Self {
        let mut engine = Self {
            entries: Vec::new(),
            default_entry_index: 0,
            timeout_seconds: 5,
            custom_variables: BTreeMap::new(),
            snapshot_selector: None,
        };

        // Add primary SigmaOS GRUB menu entry
        engine.add_menu_entry(
            "SigmaOS Sovereign Kernel (Defensive PQC)",
            ChainloadKernelSpec {
                title: "SigmaOS Main".to_string(),
                kernel_type: BootKernelType::SigmaOS,
                kernel_path: "/boot/vmlinuz-sigmaos".to_string(),
                initrd_path: Some("/boot/initramfs-sigmaos.img".to_string()),
                cmdline_params: "root=UUID=sigma-root-uuid quiet splash rw pcm=1".to_string(),
                root_device_uuid: "sigma-root-uuid".to_string(),
                snapshot_subvol: None,
            },
            false,
            false,
        );

        engine
    }

    pub fn add_menu_entry(
        &mut self,
        name: &str,
        spec: ChainloadKernelSpec,
        is_fallback: bool,
        is_recovery: bool,
    ) -> usize {
        let idx = self.entries.len();
        self.entries.push(Grub2MenuEntry {
            index: idx,
            name: name.to_string(),
            kernel_spec: spec,
            is_fallback,
            is_recovery,
        });
        idx
    }

    pub fn set_variable(&mut self, key: &str, val: &str) {
        self.custom_variables.insert(key.to_string(), val.to_string());
    }

    pub fn generate_grub_cfg(&self) -> String {
        let mut cfg = String::new();
        cfg.push_str("# GRUB2 Configuration File generated by SigmaOS Boot Engine\n");
        cfg.push_str(&format!("set default=\"{}\"\n", self.default_entry_index));
        cfg.push_str(&format!("set timeout={}\n", self.timeout_seconds));

        for (k, v) in &self.custom_variables {
            cfg.push_str(&format!("set {}=\"{}\"\n", k, v));
        }

        cfg.push_str("\ninsmod part_gpt\ninsmod part_msdos\ninsmod btrfs\ninsmod zfs\ninsmod ext2\n\n");

        for entry in &self.entries {
            cfg.push_str(&format!("menuentry '{}' {{\n", entry.name));
            cfg.push_str(&format!("    search --no-floppy --fs-uuid --set=root {}\n", entry.kernel_spec.root_device_uuid));

            match entry.kernel_spec.kernel_type {
                BootKernelType::SigmaOS | BootKernelType::Linux => {
                    let mut cmdline = entry.kernel_spec.cmdline_params.clone();
                    if let Some(ref subvol) = entry.kernel_spec.snapshot_subvol {
                        cmdline.push_str(&format!(" {}", subvol));
                    }
                    cfg.push_str(&format!("    linux {} {}\n", entry.kernel_spec.kernel_path, cmdline));
                    if let Some(ref initrd) = entry.kernel_spec.initrd_path {
                        cfg.push_str(&format!("    initrd {}\n", initrd));
                    }
                }
                BootKernelType::FreeBSD => {
                    cfg.push_str(&format!("    kfreebsd {}\n", entry.kernel_spec.kernel_path));
                    cfg.push_str(&format!("    kfreebsd_loadenv /boot/device.hints\n"));
                }
                BootKernelType::Multiboot2 => {
                    cfg.push_str(&format!("    multiboot2 {} {}\n", entry.kernel_spec.kernel_path, entry.kernel_spec.cmdline_params));
                    if let Some(ref module) = entry.kernel_spec.initrd_path {
                        cfg.push_str(&format!("    module2 {}\n", module));
                    }
                }
                BootKernelType::ChainloadEFI | BootKernelType::ChainloadMBR => {
                    cfg.push_str(&format!("    chainloader {}\n", entry.kernel_spec.kernel_path));
                }
                _ => {
                    cfg.push_str(&format!("    linux {} {}\n", entry.kernel_spec.kernel_path, entry.kernel_spec.cmdline_params));
                }
            }
            cfg.push_str("}\n\n");
        }

        cfg
    }

    pub fn parse_grub_cfg(cfg_text: &str) -> Result<Self, &'static str> {
        let mut engine = Self {
            entries: Vec::new(),
            default_entry_index: 0,
            timeout_seconds: 5,
            custom_variables: BTreeMap::new(),
            snapshot_selector: None,
        };

        let mut current_entry_name: Option<String> = None;
        let mut current_linux: Option<String> = None;
        let mut current_initrd: Option<String> = None;
        let mut current_uuid: String = "root-uuid".to_string();

        for line in cfg_text.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("set default=") {
                if let Some(val) = trimmed.split('=').nth(1) {
                    let clean = val.trim_matches('"').trim_matches('\'');
                    if let Ok(idx) = clean.parse::<usize>() {
                        engine.default_entry_index = idx;
                    }
                }
            } else if trimmed.starts_with("set timeout=") {
                if let Some(val) = trimmed.split('=').nth(1) {
                    if let Ok(t) = val.parse::<u32>() {
                        engine.timeout_seconds = t;
                    }
                }
            } else if trimmed.starts_with("menuentry ") {
                if let Some(start) = trimmed.find('\'') {
                    if let Some(end) = trimmed[start + 1..].find('\'') {
                        current_entry_name = Some(trimmed[start + 1..start + 1 + end].to_string());
                    }
                }
            } else if trimmed.starts_with("search ") && trimmed.contains("--fs-uuid") {
                if let Some(uuid) = trimmed.split_whitespace().last() {
                    current_uuid = uuid.to_string();
                }
            } else if trimmed.starts_with("linux ") {
                current_linux = Some(trimmed["linux ".len()..].to_string());
            } else if trimmed.starts_with("initrd ") {
                current_initrd = Some(trimmed["initrd ".len()..].to_string());
            } else if trimmed == "}" {
                if let Some(name) = current_entry_name.take() {
                    let (path, cmdline) = if let Some(ref l) = current_linux {
                        let mut parts = l.split_whitespace();
                        let p = parts.next().unwrap_or("/boot/vmlinuz").to_string();
                        let rest = parts.collect::<Vec<&str>>().join(" ");
                        (p, rest)
                    } else {
                        ("/boot/vmlinuz".to_string(), String::new())
                    };

                    engine.add_menu_entry(
                        &name,
                        ChainloadKernelSpec {
                            title: name.clone(),
                            kernel_type: BootKernelType::Linux,
                            kernel_path: path,
                            initrd_path: current_initrd.take(),
                            cmdline_params: cmdline,
                            root_device_uuid: current_uuid.clone(),
                            snapshot_subvol: None,
                        },
                        false,
                        false,
                    );
                }
            }
        }

        Ok(engine)
    }
}

impl Default for SovereignGrubConfigEngine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_grub_config_engine_generation() {
        let mut engine = SovereignGrubConfigEngine::new();
        engine.set_variable("GRUB_COLOR_NORMAL", "white/black");
        engine.set_variable("GRUB_COLOR_HIGHLIGHT", "black/white");

        engine.add_menu_entry(
            "FreeBSD 14.1-RELEASE VNET",
            ChainloadKernelSpec {
                title: "FreeBSD".to_string(),
                kernel_type: BootKernelType::FreeBSD,
                kernel_path: "/boot/kernel/kernel".to_string(),
                initrd_path: None,
                cmdline_params: "".to_string(),
                root_device_uuid: "freebsd-zfs-uuid".to_string(),
                snapshot_subvol: None,
            },
            false,
            false,
        );

        let cfg = engine.generate_grub_cfg();
        assert!(cfg.contains("set default=\"0\""));
        assert!(cfg.contains("set timeout=5"));
        assert!(cfg.contains("menuentry 'SigmaOS Sovereign Kernel (Defensive PQC)'"));
        assert!(cfg.contains("menuentry 'FreeBSD 14.1-RELEASE VNET'"));
        assert!(cfg.contains("kfreebsd /boot/kernel/kernel"));
    }

    #[test]
    fn test_grub_config_parser() {
        let sample_cfg = r#"
set default="1"
set timeout=10
menuentry 'Arch Linux' {
    search --no-floppy --fs-uuid --set=root 1234-ABCD
    linux /boot/vmlinuz-linux root=UUID=1234-ABCD rw quiet
    initrd /boot/initramfs-linux.img
}
menuentry 'SigmaOS Secondary' {
    search --no-floppy --fs-uuid --set=root 5678-EFGH
    linux /boot/vmlinuz-sigma2 root=UUID=5678-EFGH rw
}
"#;

        let engine = SovereignGrubConfigEngine::parse_grub_cfg(sample_cfg).unwrap();
        assert_eq!(engine.default_entry_index, 1);
        assert_eq!(engine.timeout_seconds, 10);
        assert_eq!(engine.entries.len(), 2);
        assert_eq!(engine.entries[0].name, "Arch Linux");
        assert_eq!(engine.entries[0].kernel_spec.root_device_uuid, "1234-ABCD");
        assert_eq!(engine.entries[0].kernel_spec.initrd_path, Some("/boot/initramfs-linux.img".to_string()));
    }

    #[test]
    fn test_zfs_btrfs_boot_snapshot_selector() {
        let mut selector = ZfsBtrfsBootSnapshotSelector::new("btrfs", "/");
        selector.register_snapshot("snap-2026-03-01", 1700000000);
        selector.register_snapshot("snap-2026-03-02", 1700086400);

        assert!(selector.select_snapshot("snap-2026-03-02").is_ok());
        let param = selector.get_active_subvol_param().unwrap();
        assert_eq!(param, "subvol=@snapshots/snap-2026-03-02");

        let mut zfs_selector = ZfsBtrfsBootSnapshotSelector::new("zfs", "rpool/ROOT");
        zfs_selector.register_snapshot("be-14.1", 1700000000);
        assert!(zfs_selector.select_snapshot("be-14.1").is_ok());
        assert_eq!(zfs_selector.get_active_subvol_param().unwrap(), "zfs=rpool/ROOT/be-14.1");
    }
}
