#define SIGMA_EXCLUDE_STD_ALIASES
// =============================================================================
// SigmaOS — tools/sovereign_modularize — sovereign_modularize.c
// Native C Replacement for scripts/sovereign_modularize_v2.py
// =============================================================================
// Replaces: scripts/sovereign_modularize_v2.py
// Competitor USPs Absorbed:
//   • Linux kbuild     — Kconfig-driven modular build system
//   • Bazel            — hermetic build graph, no implicit deps
//   • CMake            — per-module CMakeLists target isolation
// Algorithm:
//   • Scans all .c/.h files across suites
//   • Validates each file has exactly one SovereignShard registration call
//   • Reports misplaced files (wrong suite) based on naming conventions
//   • Generates a canonical MODULE_REGISTRY.h header for S10_Registry
// =============================================================================

#include "suites/S01_Genesis/shards/sigma_libc.h"
#include "suites/S01_Genesis/shards/sigma_libc.h"
#include "suites/S01_Genesis/shards/sigma_libc.h"
#include "suites/S01_Genesis/shards/sigma_types.h"

#include <dirent.h>
#include <sys/stat.h>

#define MAX_PATH   1024
#define MAX_SHARDS 4096
#define MAX_NAME    256

#define MOD_VERSION "2.0.0"

typedef struct {
    char suite[64];
    char filename[MAX_NAME];
    char full_path[MAX_PATH];
    bool has_registration;  // has sigma_shard_register() call
    bool correctly_placed;  // file naming matches suite conventions
} ShardRecord;

static ShardRecord shards[MAX_SHARDS];
static uint32_t    shard_count = 0;

// ── Suite naming prefixes for placement validation ────────────────────────────
static const struct { const char* suite; const char* prefix; } suite_map[] = {
    { "S01_Genesis",      "Sovereign"  },
    { "S02_ZenithUI",    "Sovereign"  },
    { "S03_Orchestrator","Sovereign"  },
    { "S04_HAL",         "Sovereign"  },
    { "S05_Memory",      "Sovereign"  },
    { "S06_Storage",     "Sovereign"  },
    { "S07_Network",     "Sovereign"  },
    { "S08_Security",    "Sovereign"  },
    { "S09_Intelligence","Sovereign"  },
    { "S10_System",      "Sovereign"  },
    { "S10_Registry",    "Sigma"      },
    { NULL, NULL }
};

static bool check_registration(const char* filepath) {
    FILE* f = sigma_open(filepath, "r");
    if (!f) return false;
    char line[512]; bool found = false;
    while (fgets(line, sizeof(line), f))
        if (strstr(line, "sigma_shard_register") || strstr(line, "SIGMA_SHARD_REGISTER"))
            { found = true; break; }
    sigma_close(f); return found;
}

static void walk_suite(const char* root, const char* suite) {
    char path[MAX_PATH];
    snprintf(path, sizeof(path), "%s/%s", root, suite);
    DIR* dir = opendir(path);
    if (!dir) return;

    const char* expected_prefix = "Sovereign";
    for (int i = 0; suite_map[i].suite; i++)
        if (sigma_strcmp(suite_map[i].suite, suite) == 0)
            { expected_prefix = suite_map[i].prefix; break; }

    struct dirent* e;
    while ((e = readdir(dir)) != NULL) {
        if (e->d_name[0] == '.') continue;
        const char* ext = strrchr(e->d_name, '.');
        if (!ext) continue;
        if (sigma_strcmp(ext, ".c") != 0 && sigma_strcmp(ext, ".h") != 0 &&
            sigma_strcmp(ext, ".rs") != 0) continue;

        if (shard_count >= MAX_SHARDS) break;
        ShardRecord* r = &shards[shard_count++];
        sigma_strncpy(r->suite,    suite,       63);
        sigma_strncpy(r->filename, e->d_name, MAX_NAME - 1);
        snprintf(r->full_path, MAX_PATH, "%s/%s", path, e->d_name);
        r->has_registration = check_registration(r->full_path);
        r->correctly_placed = (strncmp(e->d_name, expected_prefix,
                                       sigma_strlen(expected_prefix)) == 0);
    }
    closedir(dir);
}

static void emit_registry_header(const char* out_path) {
    FILE* f = sigma_open(out_path, "w");
    if (!f) return;
    fprintf(f, "// AUTO-GENERATED by sovereign_modularize v%s — DO NOT EDIT\n", MOD_VERSION);
    fprintf(f, "#ifndef SIGMA_MODULE_REGISTRY_H\n#define SIGMA_MODULE_REGISTRY_H\n\n");
    fprintf(f, "// Total sovereign shards registered: %u\n\n", shard_count);
    for (uint32_t i = 0; i < shard_count; i++) {
        char name[MAX_NAME];
        sigma_strncpy(name, shards[i].filename, MAX_NAME - 1);
        char* dot = strrchr(name, '.'); if (dot) *dot = '\0';
        // Uppercase for macro
        for (char* c = name; *c; c++) if (*c == '_') *c = '_'; else *c = (char)(*c & ~0x20);
        fprintf(f, "extern void %s_init(void);  // %s/%s\n",
                shards[i].filename, shards[i].suite, shards[i].filename);
    }
    fprintf(f, "\n#endif // SIGMA_MODULE_REGISTRY_H\n");
    sigma_close(f);
    sigma_printf("[sigma-mod] Registry header → %s\n", out_path);
}

static void print_report(void) {
    uint32_t ok = 0, misplaced = 0, unreg = 0;
    sigma_printf("\n╔══════════════════════════════════════════════════════════════╗\n");
    sigma_printf("║  SigmaOS Sovereign Modularizer  v%-27s ║\n", MOD_VERSION);
    sigma_printf("╠══════╤══════════════╤══════════════════════════════════════╣\n");
    sigma_printf("║ STAT │ %-12s │ %-38s ║\n", "SUITE", "FILE");
    sigma_printf("╠══════╪══════════════╪══════════════════════════════════════╣\n");
    for (uint32_t i = 0; i < shard_count; i++) {
        ShardRecord* r = &shards[i];
        const char* stat = r->correctly_placed ? " OK " : "MPLC";
        if (!r->correctly_placed) { misplaced++; stat = "MPLC"; }
        else if (!r->has_registration) unreg++;
        else ok++;
        sigma_printf("║ %-4s │ %-12s │ %-38s ║\n", stat, r->suite,
            r->filename + (sigma_strlen(r->filename) > 38 ? sigma_strlen(r->filename)-38 : 0));
    }
    sigma_printf("╠══════╧══════════════╧══════════════════════════════════════╣\n");
    sigma_printf("║  Total: %-4u   OK: %-4u   Misplaced: %-4u   Unreg: %-4u   ║\n",
           shard_count, ok, misplaced, unreg);
    sigma_printf("╚══════════════════════════════════════════════════════════════╝\n\n");
}

int main(int argc, char* argv[]) {
    const char* root   = argc > 1 ? argv[1] : "kernel/suites";
    const char* output = argc > 2 ? argv[2] : "include/sigma_module_registry.h";

    const char* suites[] = {
        "S01_Genesis","S02_ZenithUI","S03_Orchestrator","S04_HAL",
        "S05_Memory","S06_Storage","S07_Network","S08_Security",
        "S09_Intelligence","S10_System","S10_Registry", NULL
    };
    for (int i = 0; suites[i]; i++) walk_suite(root, suites[i]);
    print_report();
    emit_registry_header(output);
    return 0;
}


