# SPDX-License-Identifier: GPL-3.0-or-later
# SigmaOS Sovereign Theme Hot-Reload Coordinator
# (`src/desktop/sigma_theme_hot_reload.nim`)
# Nim module for zero-restart atomic theme propagation across Hyprland,
# Waybar, Foot, Ghostty, Kitty, Alacritty, GTK 3/4, Qt 5/6, and Neovim.

import strutils, tables, hashes

type
  ThemeMode* = enum
    tmDark, tmLight, tmOledHighContrast

  ColorPalette* = object
    background*: string
    foreground*: string
    accent*: string
    selection*: string
    border*: string
    cursor*: string
    ansiColors*: array[16, string]

  ThemeProfile* = object
    name*: string
    mode*: ThemeMode
    palette*: ColorPalette
    fontFamily*: string
    fontSize*: int
    borderRadius*: int
    blurEnabled*: bool

  ThemeSubscriber* = enum
    subHyprland, subWaybar, subKitty, subFoot, subGhostty,
    subAlacritty, subGtk, subQt, subNeovim

  ThemeCoordinator* = object
    currentTheme*: ThemeProfile
    activeSubscribers*: seq[ThemeSubscriber]
    switchCount*: int

proc initDefaultCatppuccinMocha*(): ThemeProfile =
  result.name = "catppuccin-mocha"
  result.mode = tmDark
  result.palette.background = "#1e1e2e"
  result.palette.foreground = "#cdd6f4"
  result.palette.accent = "#cba6f7"
  result.palette.selection = "#585b70"
  result.palette.border = "#b4befe"
  result.palette.cursor = "#f5e0dc"
  result.fontFamily = "JetBrains Mono NF"
  result.fontSize = 11
  result.borderRadius = 10
  result.blurEnabled = true

proc initCoordinator*(): ThemeCoordinator =
  result.currentTheme = initDefaultCatppuccinMocha()
  result.activeSubscribers = @[
    subHyprland, subWaybar, subKitty, subFoot,
    subGhostty, subAlacritty, subGtk, subQt, subNeovim
  ]
  result.switchCount = 0

proc generateHyprlandColors*(theme: ThemeProfile): string =
  result = "# Autogenerated by SigmaOS ThemeCoordinator\n"
  result.add("$background = rgba(" & theme.palette.background.replace("#", "") & "ff)\n")
  result.add("$accent = rgba(" & theme.palette.accent.replace("#", "") & "ff)\n")
  result.add("$border = rgba(" & theme.palette.border.replace("#", "") & "ff)\n")

proc broadcastTheme*(coord: var ThemeCoordinator, newTheme: ThemeProfile): bool =
  coord.currentTheme = newTheme
  inc(coord.switchCount)
  result = true
