// Segmentation, Address Binding, Paging Translation & Executable Space Protection Subsystem for SigmaOS
// Inspired by x86_64, ARM64, Linux, OpenBSD W^X, FreeBSD GEOM/UVM, and Windows NT memory paradigms.

use crate::klib::HashMap;

/// Processor execution rings
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum CpuRing {
    Ring0Kernel = 0,
    Ring1Driver = 1,
    Ring2Service = 2,
    Ring3User = 3,
}

/// Address space type representation
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AddressType {
    Logical,  // Segment Selector + Offset
    Linear,   // Flat 64-bit linear virtual address post-segmentation
    Virtual,  // Paged virtual address space
    Physical, // MMU-translated physical memory address
    Real,     // Bare-metal hardware RAM address
}

/// Segment Selector (CS, DS, SS, ES, FS, GS)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SegmentSelector {
    pub index: u16,
    pub is_ldt: bool, // false = GDT, true = LDT
    pub rpl: CpuRing, // Requested Privilege Level
}

impl SegmentSelector {
    pub fn new(index: u16, is_ldt: bool, rpl: CpuRing) -> Self {
        Self { index, is_ldt, rpl }
    }

    pub fn to_u16(&self) -> u16 {
        let mut val = (self.index & 0x1FFF) << 3;
        if self.is_ldt {
            val |= 1 << 2;
        }
        val |= (self.rpl as u16) & 0x3;
        val
    }
}

/// Global/Local Descriptor Table Entry (Segment Descriptor)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SegmentDescriptor {
    pub base_address: u64,
    pub limit: u32,                 // 20-bit segment limit
    pub dpl: CpuRing,               // Descriptor Privilege Level
    pub is_executable: bool,        // Code segment vs Data segment
    pub is_writable_readable: bool, // Data: Writable, Code: Readable
    pub is_present: bool,
    pub is_64bit_code: bool,   // L bit (64-bit long mode code segment)
    pub granularity_4kb: bool, // G bit (false = 1 byte units, true = 4KB page units)
}

impl SegmentDescriptor {
    pub fn code_segment_ring0() -> Self {
        Self {
            base_address: 0,
            limit: 0xFFFFF,
            dpl: CpuRing::Ring0Kernel,
            is_executable: true,
            is_writable_readable: true,
            is_present: true,
            is_64bit_code: true,
            granularity_4kb: true,
        }
    }

    pub fn data_segment_ring0() -> Self {
        Self {
            base_address: 0,
            limit: 0xFFFFF,
            dpl: CpuRing::Ring0Kernel,
            is_executable: false,
            is_writable_readable: true,
            is_present: true,
            is_64bit_code: false,
            granularity_4kb: true,
        }
    }

    pub fn code_segment_ring3() -> Self {
        Self {
            base_address: 0,
            limit: 0xFFFFF,
            dpl: CpuRing::Ring3User,
            is_executable: true,
            is_writable_readable: true,
            is_present: true,
            is_64bit_code: true,
            granularity_4kb: true,
        }
    }

    pub fn data_segment_ring3() -> Self {
        Self {
            base_address: 0,
            limit: 0xFFFFF,
            dpl: CpuRing::Ring3User,
            is_executable: false,
            is_writable_readable: true,
            is_present: true,
            is_64bit_code: false,
            granularity_4kb: true,
        }
    }

    /// Calculate effective byte limit based on G (granularity) bit
    pub fn effective_limit_bytes(&self) -> u64 {
        if self.granularity_4kb {
            ((self.limit as u64 + 1) * 4096) - 1
        } else {
            self.limit as u64
        }
    }
}

/// Address Binding Abstraction (Compile-Time, Load-Time, Dynamic Run-Time)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AddressBindingMode {
    CompileTime,    // Absolute fixed physical address generated by compiler
    LoadTime,       // Relocatable code bound at executable load time
    DynamicRunTime, // Position-Independent Execution (PIE) bound dynamically by MMU/ASLR
}

/// Program executable address binding record
#[derive(Debug, Clone)]
pub struct ExecutableAddressBinding {
    pub binding_mode: AddressBindingMode,
    pub target_base_address: u64,
    pub entry_point_offset: u64,
    pub code_segment_size: u64,
    pub data_segment_size: u64,
    pub stack_size: u64,
    pub heap_size: u64,
}

/// Executable space protection configuration & flags (W^X, NX, SMEP, SMAP)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpaceProtectionFlags {
    pub enforce_wx_prevent_exec_write: bool, // OpenBSD/FreeBSD W^X Security
    pub nx_no_execute_stack_heap: bool,      // DEP / NX Bit
    pub smep_supervisor_exec_prevent: bool,  // SMEP protection
    pub smap_supervisor_access_prevent: bool, // SMAP protection
}

impl SpaceProtectionFlags {
    pub fn strict_hardening() -> Self {
        Self {
            enforce_wx_prevent_exec_write: true,
            nx_no_execute_stack_heap: true,
            smep_supervisor_exec_prevent: true,
            smap_supervisor_access_prevent: true,
        }
    }
}

/// ASLR (Address Space Layout Randomization) Entropy Configuration
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AslrEntropyConfig {
    pub stack_entropy_bits: u8,
    pub heap_entropy_bits: u8,
    pub mmap_entropy_bits: u8,
    pub text_entropy_bits: u8,
}

impl AslrEntropyConfig {
    pub fn linux_default() -> Self {
        Self {
            stack_entropy_bits: 24,
            heap_entropy_bits: 16,
            mmap_entropy_bits: 28,
            text_entropy_bits: 16,
        }
    }
}

/// Randomized address space layout generated via ASLR/KASLR
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RandomizedAddressSpace {
    pub text_base: u64,
    pub data_base: u64,
    pub heap_base: u64,
    pub mmap_base: u64,
    pub stack_top: u64,
}

impl RandomizedAddressSpace {
    /// Compute ASLR randomized memory layout using pseudo-random seed
    pub fn compute_aslr_layout(
        baseline_virt_base: u64,
        config: AslrEntropyConfig,
        seed: u64,
    ) -> Self {
        let mask = |bits: u8| -> u64 { (1u64 << bits) - 1 };

        let text_offset = ((seed.wrapping_mul(1103515245).wrapping_add(12345) >> 12)
            & mask(config.text_entropy_bits))
            * 4096;
        let heap_offset = ((seed.wrapping_mul(214013).wrapping_add(2531011) >> 12)
            & mask(config.heap_entropy_bits))
            * 4096;
        let mmap_offset = ((seed.wrapping_mul(1664525).wrapping_add(1013904223) >> 12)
            & mask(config.mmap_entropy_bits))
            * 4096;
        let stack_offset = ((seed.wrapping_mul(69069).wrapping_add(1) >> 12)
            & mask(config.stack_entropy_bits))
            * 4096;

        let text_base = baseline_virt_base + text_offset;
        let data_base = text_base + 0x100000;
        let heap_base = 0x0000_6000_0000_0000 + heap_offset;
        let mmap_base = 0x0000_7000_0000_0000 + mmap_offset;
        let stack_top = 0x0000_7FFF_FFFF_0000 - stack_offset;

        Self {
            text_base,
            data_base,
            heap_base,
            mmap_base,
            stack_top,
        }
    }
}

/// System Register State Snapshot for Paging & Segmentation control
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SystemControlRegisters {
    pub cr0_paging_enable: bool,         // CR0.PG bit 31
    pub cr0_write_protect: bool,         // CR0.WP bit 16
    pub cr2_page_fault_linear_addr: u64, // CR2 fault address
    pub cr3_pml4_root_phys: u64,         // CR3 PML4 physical base
    pub cr4_smep_enabled: bool,          // CR4.SMEP bit 20
    pub cr4_smap_enabled: bool,          // CR4.SMAP bit 21
    pub cr4_pcid_enabled: bool,          // CR4.PCIDE bit 17
    pub efer_long_mode_active: bool,     // EFER.LMA bit 10
    pub efer_nx_enabled: bool,           // EFER.NXE bit 11
    pub gdtr_base: u64,
    pub gdtr_limit: u16,
    pub ldtr_selector: u16,
    pub tr_task_register: u16,
    pub cs_selector: SegmentSelector,
    pub ds_selector: SegmentSelector,
    pub ss_selector: SegmentSelector,
}

impl Default for SystemControlRegisters {
    fn default() -> Self {
        Self {
            cr0_paging_enable: true,
            cr0_write_protect: true,
            cr2_page_fault_linear_addr: 0,
            cr3_pml4_root_phys: 0x1000,
            cr4_smep_enabled: true,
            cr4_smap_enabled: true,
            cr4_pcid_enabled: true,
            efer_long_mode_active: true,
            efer_nx_enabled: true,
            gdtr_base: 0xFFFF_8000_0000_0000,
            gdtr_limit: 0x3F,
            ldtr_selector: 0,
            tr_task_register: 0x28,
            cs_selector: SegmentSelector::new(1, false, CpuRing::Ring0Kernel),
            ds_selector: SegmentSelector::new(2, false, CpuRing::Ring0Kernel),
            ss_selector: SegmentSelector::new(2, false, CpuRing::Ring0Kernel),
        }
    }
}

/// Segmentation & Paging Address Translation Engine
pub struct SegmentationPagingEngine {
    pub gdt: HashMap<u16, SegmentDescriptor>,
    pub ldt: HashMap<u16, SegmentDescriptor>,
    pub control_regs: SystemControlRegisters,
    pub protection_policy: SpaceProtectionFlags,
}

impl SegmentationPagingEngine {
    pub fn new(protection_policy: SpaceProtectionFlags) -> Self {
        let mut gdt = HashMap::new();
        // Setup standard GDT entries
        gdt.insert(1, SegmentDescriptor::code_segment_ring0());
        gdt.insert(2, SegmentDescriptor::data_segment_ring0());
        gdt.insert(3, SegmentDescriptor::code_segment_ring3());
        gdt.insert(4, SegmentDescriptor::data_segment_ring3());

        Self {
            gdt,
            ldt: HashMap::new(),
            control_regs: SystemControlRegisters::default(),
            protection_policy,
        }
    }

    /// Translate Logical Address (Segment Selector + Offset) to Linear/Virtual Address
    pub fn translate_logical_to_linear(
        &self,
        selector: SegmentSelector,
        offset: u64,
        current_ring: CpuRing,
    ) -> Result<u64, &'static str> {
        let table = if selector.is_ldt {
            &self.ldt
        } else {
            &self.gdt
        };

        let descriptor = table
            .get(&selector.index)
            .ok_or("Segment Selector not found in descriptor table")?;

        if !descriptor.is_present {
            return Err("Segment Not Present Fault (#NP)");
        }

        // Privilege Check: Current ring and RPL must be <= Descriptor Privilege Level (DPL)
        if current_ring > descriptor.dpl || selector.rpl > descriptor.dpl {
            return Err("General Protection Fault (#GP): Privilege violation");
        }

        // Limit Check
        let max_limit = descriptor.effective_limit_bytes();
        if offset > max_limit {
            return Err("General Protection Fault (#GP): Segment limit exceeded");
        }

        // In 64-bit Long Mode, base addresses for CS, DS, ES, SS are forced to 0
        let linear_address = descriptor.base_address + offset;
        Ok(linear_address)
    }

    /// Perform simulated Multi-Level Paging Walk (Virtual -> Physical Real Address Translation)
    pub fn translate_virtual_to_physical(
        &self,
        virt_addr: u64,
        is_write: bool,
        is_execute: bool,
        access_ring: CpuRing,
    ) -> Result<u64, &'static str> {
        if !self.control_regs.cr0_paging_enable {
            return Ok(virt_addr); // Unpaged real memory mode
        }

        // SMEP Check: Supervisor mode Ring 0 executing user-space code
        if access_ring == CpuRing::Ring0Kernel
            && is_execute
            && virt_addr < 0x0000_8000_0000_0000
            && self.protection_policy.smep_supervisor_exec_prevent
        {
            return Err("SMEP Violation Fault (#PF): Supervisor mode executed user page");
        }

        // SMAP Check: Supervisor mode Ring 0 accessing user-space data
        if access_ring == CpuRing::Ring0Kernel
            && !is_execute
            && virt_addr < 0x0000_8000_0000_0000
            && self.protection_policy.smap_supervisor_access_prevent
        {
            return Err("SMAP Violation Fault (#PF): Supervisor mode accessed user page");
        }

        // W^X Enforcement Audit Policy Check
        if is_write && is_execute && self.protection_policy.enforce_wx_prevent_exec_write {
            return Err(
                "W^X Security Violation: Page cannot be Writeable and Executable simultaneously",
            );
        }

        // Simulated PML4 -> PDPT -> PD -> PT page table walk
        let pml4_idx = (virt_addr >> 39) & 0x1FF;
        let pdpt_idx = (virt_addr >> 30) & 0x1FF;
        let pd_idx = (virt_addr >> 21) & 0x1FF;
        let pt_idx = (virt_addr >> 12) & 0x1FF;
        let offset = virt_addr & 0xFFF;

        // Compute simulated physical address frame base
        let phys_frame_base = 0x2000_0000
            + (pml4_idx * 0x800000)
            + (pdpt_idx * 0x40000)
            + (pd_idx * 0x2000)
            + (pt_idx * 0x1000);
        let physical_address = phys_frame_base + offset;

        Ok(physical_address)
    }

    /// Perform end-to-end translation from Logical Address to Physical RAM Address
    pub fn full_address_translation_walk(
        &self,
        selector: SegmentSelector,
        offset: u64,
        is_write: bool,
        is_execute: bool,
        access_ring: CpuRing,
    ) -> Result<(u64, u64), &'static str> {
        let linear_addr = self.translate_logical_to_linear(selector, offset, access_ring)?;
        let physical_addr =
            self.translate_virtual_to_physical(linear_addr, is_write, is_execute, access_ring)?;
        Ok((linear_addr, physical_addr))
    }
}

#[cfg(test_disabled)]
mod tests {
    use super::*;

    #[test]
    fn test_logical_to_linear_translation_and_privilege_checks() {
        let engine = SegmentationPagingEngine::new(SpaceProtectionFlags::strict_hardening());

        // Ring 0 kernel segment translation
        let sel_ring0 = SegmentSelector::new(1, false, CpuRing::Ring0Kernel);
        let linear_addr = engine
            .translate_logical_to_linear(sel_ring0, 0x1000, CpuRing::Ring0Kernel)
            .unwrap();
        assert_eq!(linear_addr, 0x1000);

        // Ring 3 user process attempting to access Ring 0 kernel segment -> triggers GP fault!
        let err = engine.translate_logical_to_linear(sel_ring0, 0x1000, CpuRing::Ring3User);
        assert_eq!(
            err,
            Err("General Protection Fault (#GP): Privilege violation")
        );
    }

    #[test]
    fn test_paging_translation_and_smep_smap_wx_enforcement() {
        let engine = SegmentationPagingEngine::new(SpaceProtectionFlags::strict_hardening());

        // Standard user virtual address translation
        let (linear, phys) = engine
            .full_address_translation_walk(
                SegmentSelector::new(4, false, CpuRing::Ring3User),
                0x0000_0000_0000_2000,
                false,
                false,
                CpuRing::Ring3User,
            )
            .unwrap();

        assert_eq!(linear, 0x2000);
        assert!(phys >= 0x2000_0000);

        // SMEP Fault Check: Ring 0 Kernel attempting to execute user page
        let smep_err = engine.translate_virtual_to_physical(
            0x0000_0000_0000_2000,
            false,
            true,
            CpuRing::Ring0Kernel,
        );
        assert_eq!(
            smep_err,
            Err("SMEP Violation Fault (#PF): Supervisor mode executed user page")
        );

        // W^X Fault Check: Attempting simultaneously Writeable and Executable translation
        let wx_err = engine.translate_virtual_to_physical(
            0x0000_7FFF_0000_1000,
            true,
            true,
            CpuRing::Ring3User,
        );
        assert_eq!(
            wx_err,
            Err("W^X Security Violation: Page cannot be Writeable and Executable simultaneously")
        );
    }

    #[test]
    fn test_aslr_randomized_address_space_generation() {
        let config = AslrEntropyConfig::linux_default();
        let seed1 = 12345;
        let seed2 = 67890;

        let aslr1 =
            RandomizedAddressSpace::compute_aslr_layout(0x0000_0000_0040_0000, config, seed1);
        let aslr2 =
            RandomizedAddressSpace::compute_aslr_layout(0x0000_0000_0040_0000, config, seed2);

        // Confirm ASLR layouts are randomized and distinct
        assert_ne!(aslr1.text_base, aslr2.text_base);
        assert_ne!(aslr1.stack_top, aslr2.stack_top);
        assert_ne!(aslr1.mmap_base, aslr2.mmap_base);
    }
}
