"""
Auto-split from userland\apps\pulseplayer.py — PulsePlayer._build_ui
"""

import tkinter as tk
from tkinter import messagebox, ttk, filedialog
import time, random, threading, os
from typing import Any, List, Dict



class PulsePlayer:
    def _build_ui(self):
        head = tk.Frame(self, bg=PAL['header'], height=65, padx=30)
        head.pack(side='top', fill='x')
        head.pack_propagate(False)
        tk.Label(head, text=f"{ICONS.get('media', '♫')} PULSEPLAYER PRO", font=('Segoe UI', 14, 'bold'), fg=PAL['accent'], bg=PAL['header']).pack(side='left', pady=15)
        search_fr = tk.Frame(head, bg='#1A1A24', padx=10, pady=6)
        search_fr.pack(side='right', padx=10, pady=12)
        tk.Label(search_fr, text=ICONS.get('search', '🔍'), fg=PAL['dim'], bg='#1A1A24').pack(side='left')
        self.srch = tk.Entry(search_fr, bg='#1A1A24', fg='white', borderwidth=0, font=('Segoe UI', 10), insertbackground='white', width=22)
        self.srch.pack(side='left', padx=5)
        self.srch.bind('<KeyRelease>', self._filter_tracks)
        body = tk.Frame(self, bg=PAL['bg'], padx=20, pady=15)
        body.pack(fill='both', expand=True)
        left_col = tk.Frame(body, bg=PAL['bg'])
        left_col.pack(side='left', fill='both', expand=True)
        art_fr = tk.Frame(left_col, bg='#1A1A24', width=300, height=300, highlightthickness=2, highlightbackground=PAL['secondary'])
        art_fr.pack(pady=10)
        art_fr.pack_propagate(False)
        self.art_lbl = tk.Label(art_fr, text='💿', font=('Segoe UI Symbol', 100), fg=PAL['secondary'], bg='#1A1A24')
        self.art_lbl.place(relx=0.5, rely=0.5, anchor='center')
        self.title_lbl = tk.Label(left_col, text='Select a track', font=('Segoe UI', 16, 'bold'), fg='white', bg=PAL['bg'])
        self.title_lbl.pack()
        self.artist_lbl = tk.Label(left_col, text='—', font=('Segoe UI', 10), fg=PAL['dim'], bg=PAL['bg'])
        self.artist_lbl.pack(pady=(0, 10))
        self.viz = tk.Canvas(left_col, bg=PAL['bg'], height=100, highlightthickness=0)
        self.viz.pack(fill='x', padx=20)
        self._draw_viz()
        eq_fr = tk.Frame(left_col, bg=PAL['bg'])
        eq_fr.pack(fill='x', padx=20, pady=10)
        tk.Label(eq_fr, text='EQ', font=('Segoe UI', 8, 'bold'), fg=PAL['dim'], bg=PAL['bg']).pack(anchor='w')
        for band in ['Bass', 'Mid', 'High', 'Air']:
            row = tk.Frame(eq_fr, bg=PAL['bg'])
            row.pack(fill='x', pady=2)
            tk.Label(row, text=band, font=('Segoe UI', 8), fg=PAL['dim'], bg=PAL['bg'], width=5, anchor='w').pack(side='left')
            v = tk.DoubleVar(value=70)
            self._eq_vars.append(v)
            ttk.Scale(row, from_=0, to=100, variable=v, orient='horizontal').pack(side='left', fill='x', expand=True)
        right_col = tk.Frame(body, bg=PAL['player_bg'], width=340, padx=15, pady=15)
        right_col.pack(side='right', fill='y', padx=(20, 0))
        right_col.pack_propagate(False)
        r_head = tk.Frame(right_col, bg=PAL['player_bg'])
        r_head.pack(fill='x', pady=(0, 10))
        tk.Label(r_head, text='SOVEREIGN QUEUE', font=('Segoe UI', 8, 'bold'), fg=PAL['dim'], bg=PAL['player_bg']).pack(side='left')
        tk.Button(r_head, text=f"{ICONS.get('snapshots', '＋')} ADD FILES", font=('Segoe UI', 7, 'bold'), bg=PAL['secondary'], fg='white', relief='flat', padx=8, command=self._add_files).pack(side='right')
        self.queue_tree = ttk.Treeview(right_col, columns=('T', 'D'), show='headings', height=18)
        self.queue_tree.heading('T', text='TRACK')
        self.queue_tree.heading('D', text='LEN')
        self.queue_tree.column('T', width=230)
        self.queue_tree.column('D', width=55, anchor='center')
        self.queue_tree.pack(fill='both', expand=True)
        self.queue_tree.bind('<<TreeviewSelect>>', self._on_select)
        self._populate_queue()
        dock = tk.Frame(self, bg=PAL['header'], height=150)
        dock.pack(side='bottom', fill='x')
        dock.pack_propagate(False)
        prog_fr = tk.Frame(dock, bg=PAL['header'], padx=40, pady=12)
        prog_fr.pack(fill='x')
        self.time_lbl = tk.Label(prog_fr, text='0:00', font=('Cascadia Code', 8), fg=PAL['dim'], bg=PAL['header'])
        self.time_lbl.pack(side='left')
        self.prog_var = tk.DoubleVar(value=0)
        self.prog_bar = ttk.Scale(prog_fr, from_=0, to=100, variable=self.prog_var, orient='horizontal', command=self._on_seek)
        self.prog_bar.pack(side='left', fill='x', expand=True, padx=10)
        self.dur_lbl = tk.Label(prog_fr, text='0:00', font=('Cascadia Code', 8), fg=PAL['dim'], bg=PAL['header'])
        self.dur_lbl.pack(side='right')
        btn_fr = tk.Frame(dock, bg=PAL['header'])
        btn_fr.pack()
        controls = [(ICONS.get('minimalist', '⏮'), 18, self._prev), ('⏪', 15, None), (ICONS.get('perf', '▶'), 36, self.toggle), ('⏩', 15, None), (ICONS.get('code', '⏭'), 18, self._next)]
        for i, (txt, size, cmd) in enumerate(controls):
            b = tk.Button(btn_fr, text=txt, font=('Segoe UI Symbol', size), bg=PAL['header'], fg=PAL['accent'] if size == 36 else 'white', relief='flat', borderwidth=0, command=cmd or (lambda: None))
            b.pack(side='left', padx=14)
            if i == 2:
                self.play_btn = b
        vol_fr = tk.Frame(dock, bg=PAL['header'])
        vol_fr.place(relx=0.87, rely=0.5, anchor='center')
        tk.Label(vol_fr, text=ICONS.get('media', '🔊'), fg='white', bg=PAL['header']).pack(side='left')
        self._vol = tk.DoubleVar(value=80)
        ttk.Scale(vol_fr, from_=0, to=100, variable=self._vol, orient='horizontal').pack(side='left')
        self._sovereign_mode = tk.BooleanVar(value=True)
        self._spatial_audio = tk.BooleanVar(value=False)
        tk.Button(dock, text=f"{ICONS.get('intelligence', '✨')} NEURAL", font=('Segoe UI', 8, 'bold'), bg='#252529', fg=PAL['secondary'], relief='flat', padx=10, command=self._neural).place(relx=0.12, rely=0.5, anchor='center')
        sov_fr = tk.Frame(dock, bg=PAL['header'])
        sov_fr.place(relx=0.25, rely=0.5, anchor='center')
        tk.Checkbutton(sov_fr, text='SOVEREIGN MODE', variable=self._sovereign_mode, bg=PAL['header'], fg=PAL['accent'], selectcolor=PAL['bg'], activebackground=PAL['header'], activeforeground='white', font=('Segoe UI', 7, 'bold'), command=self._toggle_sov).pack()
        spat_fr = tk.Frame(dock, bg=PAL['header'])
        spat_fr.place(relx=0.25, rely=0.75, anchor='center')
        tk.Checkbutton(spat_fr, text='SPATIAL AUDIO', variable=self._spatial_audio, bg=PAL['header'], fg=PAL['accent'], selectcolor=PAL['bg'], activebackground=PAL['header'], activeforeground='white', font=('Segoe UI', 7, 'bold'), command=self._toggle_spatial).pack()
        self.status = tk.Label(self, text='', bg=PAL['accent'], fg='white', font=('Segoe UI', 8, 'bold'), pady=4)
        self.status.pack(side='bottom', fill='x')
