import os

def build_wiki():
    suites_root = 'kernel/suites'
    wiki_path = 'WIKI/AUTO_SOVEREIGN_WIKI.md'
    
    if not os.path.exists('WIKI'):
        os.makedirs('WIKI')
        
    entries = []
    
    for suite in os.listdir(suites_root):
        suite_path = os.path.join(suites_root, suite)
        if not os.path.isdir(suite_path):
            continue
            
        shards_path = os.path.join(suite_path, 'shards')
        path_to_walk = shards_path if os.path.exists(shards_path) else suite_path
        
        for file in os.listdir(path_to_walk):
            if file.endswith(('.c', '.h')):
                file_path = os.path.join(path_to_walk, file)
                usps = []
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    in_usps = False
                    for line in f:
                        if "Competitor USPs Absorbed:" in line:
                            in_usps = True
                            continue
                        if in_usps:
                            if "//   •" in line:
                                usps.append(line.replace("//   •", "").strip())
                            elif any(x in line for x in ["// Architecture", "// Zero", "#include"]):
                                in_usps = False
                
                entries.append({
                    'suite': suite,
                    'file': file,
                    'usps': ", ".join(usps) if usps else "—"
                })
                
    with open(wiki_path, 'w', encoding='utf-8') as f:
        f.write("# SigmaOS Sovereign Shard Wiki\n")
        f.write("> Auto-generated by `sovereign_wiki_builder_py` v2.0.0\n\n")
        f.write("| Suite | Shard | USPs Absorbed |\n")
        f.write("|:------|:------|:--------------|\n")
        for entry in entries:
            f.write(f"| `{entry['suite']}` | `{entry['file']}` | {entry['usps']} |\n")
            
    print(f"Verified {len(entries)} shards. Wiki updated at {wiki_path}")

if __name__ == "__main__":
    build_wiki()
