#!/usr/bin/env bash
# Report feature parity across remote branches; optional merge plan (dry-run default).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT=0
DRY_RUN=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --report) REPORT=1; shift ;;
    --apply) DRY_RUN=0; shift ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

cd "$ROOT"
git fetch --all --prune 2>/dev/null || true

BRANCHES=(
  main
  release/standalone
  release/cloud
  release/microkernel
  kernel-exp
  drivers-dev
)

echo "[sigma-branch-sync] feature parity report"
FAIL=0
for b in "${BRANCHES[@]}"; do
  if git show-ref --verify --quiet "refs/remotes/origin/${b}"; then
    if ! "${ROOT}/scripts/ci_branch_check.sh" --branch "$b"; then
      FAIL=1
    fi
  else
    echo "[sigma-branch-sync] skip missing origin/${b}"
  fi
done

if [[ "$REPORT" -eq 1 ]]; then
  WIKI="${ROOT}/wiki_repo/Branch-Parity-Report.md"
  {
    echo "# Branch Parity Report"
    echo ""
    echo "Generated by \`scripts/sigma_branch_sync.sh --report\`"
    echo ""
    echo "| Branch | Profile |"
    echo "|--------|---------|"
    for b in "${BRANCHES[@]}"; do
      echo "| ${b} | see FEATURE_MATRIX.md |"
    done
  } > "$WIKI"
  echo "[sigma-branch-sync] wrote ${WIKI}"
fi

if [[ "$DRY_RUN" -eq 0 ]]; then
  echo "[sigma-branch-sync] --apply: merge main into release/* manually per branch policy"
  echo "  Example: git checkout release/standalone && git merge origin/main"
fi

exit "$FAIL"
