[package]
name = "sigma_app"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Native application suite for SigmaOS, containing text editor buffers and web rendering stacks displacing Neovim, Helix, VS Code, Zed, Lapce, and WebKit"

[dependencies]
# Standard library is available in userland
