# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 SigmaOS Project
#
# tools/sigma_shard_generator.nim — Shard skeleton generator
# Novel: `sigma-shard-new --template networking` generates a complete
# Hello World shard with Cargo.toml, probe/init/shutdown, sigma-bus IPC,
# sigma_pledge declaration, unit tests, CI job, and wiki stub.
#
# Language: Nim (stdlib only)

import std/[os, strutils, strformat, osproc, json]

# ── Shard templates ───────────────────────────────────────────────────────
type ShardTemplate = enum
  TplNetworking, TplStorage, TplSecurity, TplAudio,
  TplDisplay, TplInput, TplIpc, TplMinimal, TplCli

proc tpl_from_str(s: string): ShardTemplate =
  case s.toLowerAscii
  of "networking","net":  TplNetworking
  of "storage","disk":    TplStorage
  of "security","sec":    TplSecurity
  of "audio","sound":     TplAudio
  of "display","gpu":     TplDisplay
  of "input","hid":       TplInput
  of "ipc","bus":         TplIpc
  of "cli","tool":        TplCli
  else:                   TplMinimal

proc tpl_pledge(t: ShardTemplate): string =
  case t
  of TplNetworking: "\"stdio\", \"rpath\", \"inet\""
  of TplStorage:    "\"stdio\", \"rpath\", \"wpath\", \"cpath\""
  of TplSecurity:   "\"stdio\""
  of TplAudio:      "\"stdio\", \"audio\""
  of TplDisplay:    "\"stdio\", \"video\""
  of TplInput:      "\"stdio\", \"device\""
  of TplIpc:        "\"stdio\""
  of TplCli:        "\"stdio\", \"rpath\""
  else:             "\"stdio\""

proc tpl_bus_channel(t: ShardTemplate): string =
  case t
  of TplNetworking: "BUS_NETWORK"
  of TplStorage:    "BUS_STORAGE"
  of TplSecurity:   "BUS_SECURITY"
  of TplAudio:      "BUS_AUDIO"
  of TplDisplay:    "BUS_DISPLAY"
  of TplInput:      "BUS_INPUT"
  of TplIpc:        "BUS_CUSTOM"
  else:             "BUS_SHARD"

# ── File generators ────────────────────────────────────────────────────────
proc gen_cargo_toml(shard_name, author: string): string =
  fmt"""[package]
name        = "sigma-shard-{shard_name}"
version     = "0.1.0"
edition     = "2021"
authors     = ["{author}"]
description = "SigmaOS shard: {shard_name}"
license     = "MIT"

# SigmaOS zero-dependency policy — no external crates in kernel shards
[dependencies]

[profile.release]
opt-level     = "z"
lto           = true
codegen-units = 1
panic         = "abort"
"""

proc gen_lib_rs(shard_name: string, tpl: ShardTemplate): string =
  let name_upper = shard_name.toUpperAscii.replace("-","_")
  let pledge     = tpl_pledge(tpl)
  let bus_chan    = tpl_bus_channel(tpl)
  fmt"""// SPDX-License-Identifier: MIT
// Copyright (c) 2024-2026 SigmaOS Project
//
// sigma-shard-{shard_name} — SigmaOS {shard_name} shard
// Generated by: sigma-shard-new --template {$tpl}
//
// SDF lifecycle: probe() → init() → run() → shutdown()
// sigma_pledge: {pledge}
// sigma-bus channel: {bus_chan}

#![no_std]
#![allow(dead_code)]

// ── Shard metadata ────────────────────────────────────────────────────────
pub const SHARD_NAME:    &str = "sigma-{shard_name}";
pub const SHARD_VERSION: &str = "0.1.0";
pub const SHARD_AUTHOR:  &str = "SigmaOS Project";

// ── Shard state ────────────────────────────────────────────────────────────
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
#[repr(u8)]
pub enum ShardState {{
    Probing, Initialised, Running, Stopped, Failed,
}}

pub struct {name_upper}Shard {{
    pub state:   ShardState,
    pub version: &'static str,
}}

impl {name_upper}Shard {{
    pub const fn new() -> Self {{
        Self {{ state: ShardState::Probing, version: SHARD_VERSION }}
    }}
}}

// ── SDF Lifecycle ─────────────────────────────────────────────────────────

/// probe(): Called by kernel to check if this shard should load on this hardware
#[no_mangle]
pub extern "C" fn {shard_name}_probe() -> bool {{
    // TODO: Check hardware capability / feature flag
    // Return true if this shard should be loaded
    true
}}

/// init(): Called once at shard load time
#[no_mangle]
pub extern "C" fn {shard_name}_init() -> i32 {{
    // TODO: Allocate resources, register with sigma-bus
    // Call sigma_pledge() to restrict capabilities
    unsafe {{
        extern "C" {{
            fn sigma_pledge(promises: *const u8, len: usize) -> i32;
        }}
        let promises = concat!({pledge}, "\\0");
        sigma_pledge(promises.as_ptr(), promises.len());
    }}
    0  // 0 = success
}}

/// run(): Main shard loop — processes sigma-bus messages
#[no_mangle]
pub extern "C" fn {shard_name}_run() {{
    loop {{
        // TODO: Receive from sigma-bus, process, send response
        // sigma_bus_recv(BUS_CHANNEL, &mut buf, buf_len, timeout_ms)
        // Process message
        // sigma_bus_send(BUS_CHANNEL, response.as_ptr(), response.len())
        break;  // Remove this for actual daemon loop
    }}
}}

/// shutdown(): Called when shard is unloaded
#[no_mangle]
pub extern "C" fn {shard_name}_shutdown() {{
    // TODO: Release resources, deregister from sigma-bus
}}

// ── sigma-bus message types ────────────────────────────────────────────────
#[repr(C)]
#[derive(Copy, Clone)]
pub struct {name_upper}Request {{
    pub msg_type: u32,
    pub payload:  [u8; 128],
}}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct {name_upper}Response {{
    pub status:   i32,
    pub payload:  [u8; 128],
}}

// ── Tests ─────────────────────────────────────────────────────────────────
#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn test_probe() {{
        assert!({shard_name}_probe());
    }}

    #[test]
    fn test_shard_state() {{
        let shard = {name_upper}Shard::new();
        assert_eq!(shard.state, ShardState::Probing);
        assert_eq!(shard.version, SHARD_VERSION);
    }}
}}
"""

proc gen_sigma_manifest(shard_name: string, tpl: ShardTemplate): string =
  let pledge = tpl_pledge(tpl)
  fmt"""[shard]
name        = "sigma-{shard_name}"
version     = "0.1.0"
description = "SigmaOS {shard_name} shard"
license     = "MIT"
sdf_version = "1.0"

[security]
pledge  = [{pledge}]
unveil  = []

[bus]
channels = ["{tpl_bus_channel(tpl)}"]

[lifecycle]
probe    = "{shard_name}_probe"
init     = "{shard_name}_init"
run      = "{shard_name}_run"
shutdown = "{shard_name}_shutdown"
"""

proc gen_ci_yml(shard_name: string): string =
  fmt"""name: sigma-shard-{shard_name} CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with: {{toolchain: stable, override: true}}
      - name: Build shard
        run: cargo build --release -p sigma-shard-{shard_name}
      - name: Test shard
        run: cargo test -p sigma-shard-{shard_name}
      - name: Clippy
        run: cargo clippy -p sigma-shard-{shard_name} -- -D warnings || true
"""

proc gen_readme(shard_name: string, tpl: ShardTemplate): string =
  fmt"""# sigma-shard-{shard_name}

> SigmaOS {shard_name} shard — generated by sigma-shard-new

## Overview

This shard implements the `{shard_name}` capability for SigmaOS.
It follows the Sovereign Driver Framework (SDF) lifecycle:
`probe() → init() → run() → shutdown()`

## Security

- **sigma_pledge:** {tpl_pledge(tpl)}
- **sigma-bus:** {tpl_bus_channel(tpl)}

## Build

```bash
cargo build --release -p sigma-shard-{shard_name}
cargo test -p sigma-shard-{shard_name}
```

## Install

```bash
sigma-pkg install sigma-shard-{shard_name}
```

## Contributing

See [Community Governance](https://github.com/AaryanSinghChauhan09/SigmaOS/wiki/Community-Governance)
"""

proc gen_wiki_stub(shard_name: string): string =
  fmt"""# sigma-shard-{shard_name}

> SigmaOS capability shard: {shard_name}

## Status

| Component | Status |
|---|---|
| probe() | ⬜ |
| init()  | ⬜ |
| run()   | ⬜ |
| shutdown() | ⬜ |
| Unit tests | ⬜ |

## sigma-bus Protocol

TODO: Document message types.

## Security

- sigma_pledge: {"{tpl_pledge(TplMinimal)}"}
- sigma_unveil: none

*Generated by sigma-shard-new*
"""

# ── Main generator ────────────────────────────────────────────────────────
proc generate_shard*(shard_name, author, output_dir: string, tpl: ShardTemplate) =
  let shard_dir = output_dir / fmt"sigma-shard-{shard_name}"
  let src_dir   = shard_dir / "src"
  createDir(src_dir)

  let files = [
    (shard_dir / "Cargo.toml",       gen_cargo_toml(shard_name, author)),
    (src_dir   / "lib.rs",           gen_lib_rs(shard_name, tpl)),
    (shard_dir / "sigma-shard.toml", gen_sigma_manifest(shard_name, tpl)),
    (shard_dir / ".github" / "workflows" / "ci.yml", gen_ci_yml(shard_name)),
    (shard_dir / "README.md",        gen_readme(shard_name, tpl)),
    (shard_dir / "WIKI_STUB.md",     gen_wiki_stub(shard_name)),
  ]
  for (path, content) in files:
    createDir(path.parentDir())
    writeFile(path, content)

  echo fmt"\e[38;2;52;211;153m✓ Shard scaffold generated: {shard_dir}\e[0m"
  echo fmt"\n  Structure:"
  echo fmt"  {shard_dir}/"
  echo fmt"  ├── Cargo.toml"
  echo fmt"  ├── sigma-shard.toml    (SDF manifest)"
  echo fmt"  ├── src/lib.rs          (probe/init/run/shutdown + tests)"
  echo fmt"  ├── README.md"
  echo fmt"  └── .github/workflows/ci.yml"
  echo fmt"\n  Next steps:"
  echo fmt"  1. cd {shard_dir} && cargo build --release"
  echo fmt"  2. Implement probe()/init()/run() in src/lib.rs"
  echo fmt"  3. sigma-pkg publish sigma-shard-{shard_name}"
  echo fmt"  4. Submit PR to github.com/AaryanSinghChauhan09/SigmaOS"

# ── CLI ────────────────────────────────────────────────────────────────────
proc shard_gen_cmd*(args: seq[string]) =
  if args.len == 0 or args[0] == "help":
    echo """sigma-shard-new — Shard skeleton generator

Usage:
  sigma-shard-new <name>                       Minimal shard
  sigma-shard-new <name> --template <tpl>      Template-based shard
  sigma-shard-new <name> --output <dir>        Custom output directory
  sigma-shard-new <name> --author "Name"       Set author
  sigma-shard-new --list                        List available templates

Templates:
  networking    Network device driver (sigma-bus: BUS_NETWORK)
  storage       Block storage driver (BUS_STORAGE)
  security      Security enforcer shard (BUS_SECURITY)
  audio         Audio device driver (BUS_AUDIO)
  display       Display/GPU driver (BUS_DISPLAY)
  input         Input device driver (BUS_INPUT)
  ipc           IPC relay shard (BUS_CUSTOM)
  cli           CLI tool shard (no bus)
  minimal       Bare-bones shard (default)

Examples:
  sigma-shard-new my-wifi-driver --template networking
  sigma-shard-new sigma-usb3 --template storage --author "Jane Dev"
  sigma-shard-new my-security-check --template security
  sigma-shard-new --list
"""
    return

  if args[0] == "--list":
    echo "Available templates:"
    for t in [TplNetworking, TplStorage, TplSecurity, TplAudio,
              TplDisplay, TplInput, TplIpc, TplCli, TplMinimal]:
      echo fmt"  {$t:<20} pledge={tpl_pledge(t)}"
    return

  let shard_name = args[0].toLowerAscii.replace(" ", "-")
  let tpl_idx    = args.find("--template")
  let tpl        = if tpl_idx >= 0 and tpl_idx+1 < args.len:
                     tpl_from_str(args[tpl_idx+1])
                   else: TplMinimal
  let out_idx    = args.find("--output")
  let out_dir    = if out_idx >= 0 and out_idx+1 < args.len: args[out_idx+1]
                   else: getCurrentDir()
  let auth_idx   = args.find("--author")
  let author     = if auth_idx >= 0 and auth_idx+1 < args.len: args[auth_idx+1]
                   else: "SigmaOS Contributor"

  generate_shard(shard_name, author, out_dir, tpl)
