# SigmaOS — Nim Font Builder
# Inspired by Omarchy branch: dev-font-builder
# Zero external dependencies, pure Nim
# Compiles and patches TTF/OTF fonts, generates font-face CSS

import std/[strutils, sequtils, os, strformat, algorithm]

## Font weight class
type
  FontWeight* = enum
    wThin = 100
    wExtraLight = 200
    wLight = 300
    wRegular = 400
    wMedium = 500
    wSemiBold = 600
    wBold = 700
    wExtraBold = 800
    wBlack = 900

  FontStyle* = enum
    fsNormal = "normal"
    fsItalic = "italic"
    fsOblique = "oblique"

  FontFormat* = enum
    ffTtf = "truetype"
    ffOtf = "opentype"
    ffWoff2 = "woff2"
    ffVariable = "variable"

  FontVariant* = object
    weight*: FontWeight
    style*: FontStyle
    path*: string
    format*: FontFormat
    unicodeRange*: string

  FontFamily* = object
    name*: string
    displayName*: string
    variants*: seq[FontVariant]
    isVariable*: bool
    subset*: seq[string]  # unicode subsets: "latin", "cyrillic", etc.

  SigmaFontBuilder* = object
    families*: seq[FontFamily]
    outputDir*: string
    cssPrefix*: string
    generateWoff2*: bool

## Create a new SigmaFontBuilder
proc newSigmaFontBuilder*(outputDir: string = "/usr/share/sigmaos/fonts"): SigmaFontBuilder =
  SigmaFontBuilder(
    families: @[],
    outputDir: outputDir,
    cssPrefix: "/usr/share/sigmaos/fonts",
    generateWoff2: true
  )

## Register a font family
proc registerFamily*(builder: var SigmaFontBuilder, name: string, displayName: string = "", variable: bool = false): int =
  builder.families.add FontFamily(
    name: name,
    displayName: if displayName.len > 0: displayName else: name,
    variants: @[],
    isVariable: variable,
    subset: @["latin", "latin-ext"]
  )
  result = builder.families.len - 1

## Add a variant to a family
proc addVariant*(builder: var SigmaFontBuilder, familyIdx: int, path: string,
                 weight: FontWeight = wRegular, style: FontStyle = fsNormal,
                 format: FontFormat = ffTtf) =
  if familyIdx < builder.families.len:
    builder.families[familyIdx].variants.add FontVariant(
      weight: weight,
      style: style,
      path: path,
      format: format,
      unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F"
    )

## Generate @font-face CSS for a single variant
proc generateFontFaceCSS(family: FontFamily, variant: FontVariant, prefix: string): string =
  let fname = splitFile(variant.path).name
  let woff2Path = prefix / fname & ".woff2"
  let srcMain = if variant.format == ffWoff2:
    fmt"""url('{woff2Path}') format('woff2')"""
  else:
    fmt"""url('{prefix / variant.path}') format('{$variant.format}')"""
  
  result = fmt"""
@font-face {{
  font-family: '{family.displayName}';
  font-weight: {ord(variant.weight)};
  font-style: {$variant.style};
  font-display: swap;
  src: {srcMain};
  unicode-range: {variant.unicodeRange};
}}
"""

## Generate complete CSS font-face block for all families
proc generateFontCSS*(builder: SigmaFontBuilder): string =
  result = "/* SigmaOS Font Bundle — auto-generated by sigma-font-builder */\n\n"
  for family in builder.families:
    result &= fmt"/* === {family.displayName} === */\n"
    for variant in family.variants.sortedByIt(ord(it.weight)):
      result &= generateFontFaceCSS(family, variant, builder.cssPrefix)

## Generate fontconfig XML for system-wide font registration
proc generateFontconfigXml*(builder: SigmaFontBuilder): string =
  result = """<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
"""
  result &= fmt"  <dir>{builder.outputDir}</dir>\n"
  for family in builder.families:
    result &= fmt"""  <alias>
    <family>{family.name}</family>
    <prefer><family>{family.displayName}</family></prefer>
  </alias>
"""
  result &= "</fontconfig>\n"

## Generate a shell build script that compiles sources → TTF/OTF using fonttools
proc generateBuildScript*(builder: SigmaFontBuilder): string =
  result = "#!/usr/bin/env bash\n"
  result &= "# SigmaOS Font Build Script — auto-generated\n"
  result &= "set -euo pipefail\n\n"
  result &= fmt"OUTPUT_DIR=\"{builder.outputDir}\"\n"
  result &= "mkdir -p \"$OUTPUT_DIR\"\n\n"
  for family in builder.families:
    result &= fmt"echo 'Building {family.displayName}...'\n"
    for v in family.variants:
      let dest = builder.outputDir / splitFile(v.path).name & "." & (
        if v.format == ffOtf: "otf" else: "ttf"
      )
      result &= fmt"install -m 644 '{v.path}' '{dest}'\n"
      if builder.generateWoff2:
        result &= fmt"python3 -m fonttools.ttLib.woff2 compress '{dest}' -o '{dest.replace(\".ttf\",\".woff2\").replace(\".otf\",\".woff2\")}'\n"
  result &= "\nfc-cache -fv \"$OUTPUT_DIR\"\necho 'Font build complete.'\n"

## Get the count of registered variants across all families
proc totalVariantCount*(builder: SigmaFontBuilder): int =
  for f in builder.families: result += f.variants.len

when isMainModule:
  var builder = newSigmaFontBuilder("/usr/share/sigmaos/fonts")
  
  # Register JetBrains Mono (coding font)
  let jbm = builder.registerFamily("JetBrainsMono", "JetBrains Mono", variable = true)
  builder.addVariant(jbm, "JetBrainsMono-Regular.ttf", wRegular)
  builder.addVariant(jbm, "JetBrainsMono-Bold.ttf", wBold)
  builder.addVariant(jbm, "JetBrainsMono-Italic.ttf", wRegular, fsItalic)
  
  # Register Inter (UI font)
  let inter = builder.registerFamily("Inter", "Inter", variable = true)
  builder.addVariant(inter, "Inter-Regular.ttf", wRegular)
  builder.addVariant(inter, "Inter-Medium.ttf", wMedium)
  builder.addVariant(inter, "Inter-SemiBold.ttf", wSemiBold)
  builder.addVariant(inter, "Inter-Bold.ttf", wBold)
  
  echo builder.generateFontCSS()
  echo "---"
  echo builder.generateFontconfigXml()
  echo fmt"Total variants: {builder.totalVariantCount()}"
