name: Anchore Grype Vulnerability Scan
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  anchore-grype:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@11bd5193b48c4b3c7778881999d4b1d7e0ba3a8c # v4.2.2
      - name: Scan repository for vulnerabilities
        uses: anchore/scan-action@bb6bcf9fbb3a90ee3f8af714615b6ae7b3b65e6e # v6.0.0
        id: grype-scan
        continue-on-error: true
        with:
          path: "."
          fail-build: false
          severity-cutoff: high
          output-format: sarif
      - name: Upload Grype SARIF report
        if: ${{ !cancelled() && steps.grype-scan.outcome == 'success' }}
        uses: github/codeql-action/upload-sarif@8685613e7270999a0b60a2bb20a5666b789c9b0e # v3.27.9
        continue-on-error: true
        with:
          sarif_file: ${{ steps.grype-scan.outputs.sarif }}
