name: Scorecard supply-chain security
on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@0ad4b8fadaa221615c556ef6a276828e6dbdd4cf
        with:
          persist-credentials: false

      - name: "Run scorecard"
        uses: ossf/scorecard-action@dc5088702f4f31805f9c8498836b35af44f776d8
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: "Upload SARIF"
        uses: github/codeql-action/upload-sarif@b6f47e18f9c8a16e4c45bbc8625d2f7b7fea8506
        with:
          sarif_file: results.sarif
