name: Semgrep Security Scan
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep SAST Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@11bd5193b48c4b3c7778881999d4b1d7e0ba3a8c # v4.2.2
      - run: semgrep scan --config auto --sarif --output=semgrep.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@8685613e7270999a0b60a2bb20a5666b789c9b0e # v3.27.9
        with:
          sarif_file: semgrep.sarif
        if: always()
