name: Semgrep Security Scan
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep SAST Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@0ad4b8fadaa221615c556ef6a276828e6dbdd4cf
      - run: semgrep scan --config auto --sarif --output=semgrep.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@b6f47e18f9c8a16e4c45bbc8625d2f7b7fea8506
        with:
          sarif_file: semgrep.sarif
        if: always()
