name: Sovereign Distro GitHub Pages Auto-Deploy

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.2.2

      - name: Setup Pages
        uses: actions/configure-pages@1f813d38ab810320f71692857543d798d8f76020 # v5.0.0

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: 'web_ui'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db5d4108080f5c2f483c6c0b3956bf1f38e658 # v4.0.5
