name: Trivy Security Scan
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262


      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@d2a0b60797ff03db6132bd4e2b293f9b37081297

        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@5ba2889ada762081db2c4f32a729827dce632c7b

        with:
          sarif_file: 'trivy-results.sarif'
