// Debian-style Package Transaction, Verification, and Mirror Selector Suite
// Replicates netselect-apt, dpkg transactional safety guarantees, and maintainer script sanitization

use crate::sigpkg::{Package, Version};
use std::collections::HashMap;

/// Represents a Debian-style repository mirror with speed metrics
#[derive(Debug, Clone)]
pub struct DebianMirror {
    pub url: String,
    pub latency_ms: u32,
    pub bandwidth_mbps: u32,
}

/// Debian netselect-apt style dynamic mirror selector
pub struct SovereignMirrorSelector {
    pub mirrors: Vec<DebianMirror>,
}

impl SovereignMirrorSelector {
    pub fn new() -> Self {
        Self {
            mirrors: Vec::new(),
        }
    }

    pub fn register_mirror(&mut self, url: &str, latency: u32, bandwidth: u32) {
        self.mirrors.push(DebianMirror {
            url: url.to_string(),
            latency_ms: latency,
            bandwidth_mbps: bandwidth,
        });
    }

    /// Selects the optimal Debian archive mirror based on latency and bandwidth score
    pub fn select_best_mirror(&self) -> Option<DebianMirror> {
        self.mirrors.iter().min_by_key(|m| {
            // We want minimum latency, but offset by high bandwidth
            let score = m.latency_ms as i32 - (m.bandwidth_mbps as i32 * 2);
            score
        }).cloned()
    }

    /// Dynamically generates standard Debian /etc/apt/sources.list configuration
    pub fn generate_sources_list(&self, suite: &str) -> Result<String, &'static str> {
        let best_mirror = self.select_best_mirror().ok_or("No mirrors registered")?;
        let sources = format!(
            "# Dynamically generated by SovereignMirrorSelector\n\
             deb {} {} main contrib non-free non-free-firmware\n\
             deb-src {} {} main contrib non-free non-free-firmware\n",
            best_mirror.url, suite, best_mirror.url, suite
        );
        Ok(sources)
    }
}

impl Default for SovereignMirrorSelector {
    fn default() -> Self {
        Self::new()
    }
}

/// Represents the status of a dpkg-style packaging transaction
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransactionStatus {
    Pending,
    Committing,
    Committed,
    RollingBack,
    RolledBack,
}

/// Dpkg-style transactional safety and atomic state rollbacks
pub struct SovereignTransactionManager {
    pub active_packages: HashMap<String, Version>,
    pub backup_packages: HashMap<String, Version>,
    pub status: TransactionStatus,
}

impl SovereignTransactionManager {
    pub fn new() -> Self {
        Self {
            active_packages: HashMap::new(),
            backup_packages: HashMap::new(),
            status: TransactionStatus::Pending,
        }
    }

    pub fn register_package(&mut self, name: &str, version: Version) {
        self.active_packages.insert(name.to_string(), version);
    }

    /// Begins an atomic transaction, backing up the current packages database state
    pub fn begin_transaction(&mut self) -> Result<(), &'static str> {
        if self.status == TransactionStatus::Committing {
            return Err("Transaction is already in progress");
        }
        self.backup_packages = self.active_packages.clone();
        self.status = TransactionStatus::Committing;
        Ok(())
    }

    /// Commits metadata changes on successful package installation
    pub fn commit_transaction(&mut self) -> Result<(), &'static str> {
        if self.status != TransactionStatus::Committing {
            return Err("No active transaction to commit");
        }
        self.backup_packages.clear();
        self.status = TransactionStatus::Committed;
        Ok(())
    }

    /// Rolls back the entire packages database state to the backup, preventing dpkg half-configured lockouts
    pub fn rollback_transaction(&mut self) -> Result<(), &'static str> {
        if self.status != TransactionStatus::Committing {
            return Err("Cannot rollback without active transaction");
        }
        self.status = TransactionStatus::RollingBack;
        self.active_packages = self.backup_packages.clone();
        self.backup_packages.clear();
        self.status = TransactionStatus::RolledBack;
        Ok(())
    }
}

impl Default for SovereignTransactionManager {
    fn default() -> Self {
        Self::new()
    }
}

/// Sanitizes Debian-style maintainer scripts (preinst, postinst)
pub struct SovereignSandboxEnforcer {
    pub restricted_paths: Vec<String>,
}

impl SovereignSandboxEnforcer {
    pub fn new() -> Self {
        Self {
            restricted_paths: vec!["/etc/shadow".to_string(), "/boot".to_string(), "/sys".to_string()],
        }
    }

    /// Audits maintainer script shell command content for unauthorized ambient-access writes
    pub fn audit_maintainer_script(&self, script_content: &str) -> Result<bool, &'static str> {
        for path in &self.restricted_paths {
            if script_content.contains(path) && (script_content.contains("rm ") || script_content.contains(">") || script_content.contains("tee ")) {
                return Err("Security violation: script attempts out-of-sandbox modifications to restricted system directories");
            }
        }
        Ok(true)
    }
}

impl Default for SovereignSandboxEnforcer {
    fn default() -> Self {
        Self::new()
    }
}

/// Advanced Debian package delta compiler (calculates minimal upgrade diffs)
pub struct SovereignDeltaGenerator;

impl SovereignDeltaGenerator {
    pub fn generate_binary_delta(&self, old: &[u8], new: &[u8]) -> Vec<u8> {
        let mut delta = Vec::new();
        // Simplified binary diff (in production use bsdiff/xdelta)
        let min_len = std::cmp::min(old.len(), new.len());
        for i in 0..min_len {
            if old[i] != new[i] {
                delta.push(new[i]);
            }
        }
        if new.len() > old.len() {
            delta.extend_from_slice(&new[min_len..]);
        }
        delta
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mirror_selection() {
        let mut selector = SovereignMirrorSelector::new();
        selector.register_mirror("http://debian.org/stable", 50, 100);
        selector.register_mirror("http://us.debian.org/stable", 10, 1000); // Optimal

        let best = selector.select_best_mirror().unwrap();
        assert_eq!(best.url, "http://us.debian.org/stable");

        let sources = selector.generate_sources_list("bookworm").unwrap();
        assert!(sources.contains("deb http://us.debian.org/stable bookworm"));
    }

    #[test]
    fn test_dpkg_transaction_safety() {
        let mut manager = SovereignTransactionManager::new();
        manager.register_package("bash", Version::new(5, 1, 0));
        manager.register_package("nano", Version::new(7, 2, 0));

        // Start install transaction
        manager.begin_transaction().unwrap();
        assert_eq!(manager.status, TransactionStatus::Committing);

        // Simulate installing newer nano
        manager.register_package("nano", Version::new(7, 3, 0));

        // Rollback on failure
        manager.rollback_transaction().unwrap();
        assert_eq!(manager.status, TransactionStatus::RolledBack);
        assert_eq!(manager.active_packages.get("nano").unwrap(), &Version::new(7, 2, 0)); // Rolled back
    }

    #[test]
    fn test_maintainer_scripts_sandbox() {
        let enforcer = SovereignSandboxEnforcer::new();

        // Safe script
        let safe = "echo 'configuring package...'";
        assert!(enforcer.audit_maintainer_script(safe).is_ok());

        // Insecure script
        let malicious = "echo 'payload' > /etc/shadow";
        assert!(enforcer.audit_maintainer_script(malicious).is_err());
    }

    #[test]
    fn test_binary_deltas() {
        let generator = SovereignDeltaGenerator;
        let old = b"hello old world";
        let new = b"hello new world";
        let delta = generator.generate_binary_delta(old, new);
        assert!(!delta.is_empty());
    }
}
