// Debian-style Package Transaction, Verification, and Mirror Selector Suite
// Replicates netselect-apt, dpkg transactional safety guarantees, and maintainer script sanitization
// Enhanced with Debian update-alternatives and APT Pinning /preferences routing engines

#[cfg(not(test))]
use crate::sigpkg::{Package, Version};

#[cfg(test)]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Version {
    pub major: u32,
    pub minor: u32,
    pub patch: u32,
}

#[cfg(test)]
impl Version {
    pub fn new(major: u32, minor: u32, patch: u32) -> Self {
        Self { major, minor, patch }
    }
}

use std::collections::HashMap;

/// Represents a Debian-style repository mirror with speed metrics
#[derive(Debug, Clone)]
pub struct DebianMirror {
    pub url: String,
    pub latency_ms: u32,
    pub bandwidth_mbps: u32,
}

/// Debian netselect-apt style dynamic mirror selector
pub struct SovereignMirrorSelector {
    pub mirrors: Vec<DebianMirror>,
}

impl SovereignMirrorSelector {
    pub fn new() -> Self {
        Self {
            mirrors: Vec::new(),
        }
    }

    pub fn register_mirror(&mut self, url: &str, latency: u32, bandwidth: u32) {
        self.mirrors.push(DebianMirror {
            url: url.to_string(),
            latency_ms: latency,
            bandwidth_mbps: bandwidth,
        });
    }

    /// Selects the optimal Debian archive mirror based on latency and bandwidth score
    pub fn select_best_mirror(&self) -> Option<DebianMirror> {
        self.mirrors.iter().min_by_key(|m| {
            // We want minimum latency, but offset by high bandwidth
            let score = m.latency_ms as i32 - (m.bandwidth_mbps as i32 * 2);
            score
        }).cloned()
    }

    /// Dynamically generates standard Debian /etc/apt/sources.list configuration
    pub fn generate_sources_list(&self, suite: &str) -> Result<String, &'static str> {
        let best_mirror = self.select_best_mirror().ok_or("No mirrors registered")?;
        let sources = format!(
            "# Dynamically generated by SovereignMirrorSelector\n\
             deb {} {} main contrib non-free non-free-firmware\n\
             deb-src {} {} main contrib non-free non-free-firmware\n",
            best_mirror.url, suite, best_mirror.url, suite
        );
        Ok(sources)
    }
}

impl Default for SovereignMirrorSelector {
    fn default() -> Self {
        Self::new()
    }
}

/// Represents the status of a dpkg-style packaging transaction
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransactionStatus {
    Pending,
    Committing,
    Committed,
    RollingBack,
    RolledBack,
}

/// Dpkg-style transactional safety and atomic state rollbacks
pub struct SovereignTransactionManager {
    pub active_packages: HashMap<String, Version>,
    pub backup_packages: HashMap<String, Version>,
    pub status: TransactionStatus,
}

impl SovereignTransactionManager {
    pub fn new() -> Self {
        Self {
            active_packages: HashMap::new(),
            backup_packages: HashMap::new(),
            status: TransactionStatus::Pending,
        }
    }

    pub fn register_package(&mut self, name: &str, version: Version) {
        self.active_packages.insert(name.to_string(), version);
    }

    /// Begins an atomic transaction, backing up the current packages database state
    pub fn begin_transaction(&mut self) -> Result<(), &'static str> {
        if self.status == TransactionStatus::Committing {
            return Err("Transaction is already in progress");
        }
        self.backup_packages = self.active_packages.clone();
        self.status = TransactionStatus::Committing;
        Ok(())
    }

    /// Commits metadata changes on successful package installation
    pub fn commit_transaction(&mut self) -> Result<(), &'static str> {
        if self.status != TransactionStatus::Committing {
            return Err("No active transaction to commit");
        }
        self.backup_packages.clear();
        self.status = TransactionStatus::Committed;
        Ok(())
    }

    /// Rolls back the entire packages database state to the backup, preventing dpkg half-configured lockouts
    pub fn rollback_transaction(&mut self) -> Result<(), &'static str> {
        if self.status != TransactionStatus::Committing {
            return Err("Cannot rollback without active transaction");
        }
        self.status = TransactionStatus::RollingBack;
        self.active_packages = self.backup_packages.clone();
        self.backup_packages.clear();
        self.status = TransactionStatus::RolledBack;
        Ok(())
    }
}

impl Default for SovereignTransactionManager {
    fn default() -> Self {
        Self::new()
    }
}

/// Sanitizes Debian-style maintainer scripts (preinst, postinst)
pub struct SovereignSandboxEnforcer {
    pub restricted_paths: Vec<String>,
}

impl SovereignSandboxEnforcer {
    pub fn new() -> Self {
        Self {
            restricted_paths: vec!["/etc/shadow".to_string(), "/boot".to_string(), "/sys".to_string()],
        }
    }

    /// Audits maintainer script shell command content for unauthorized ambient-access writes
    pub fn audit_maintainer_script(&self, script_content: &str) -> Result<bool, &'static str> {
        for path in &self.restricted_paths {
            if script_content.contains(path) && (script_content.contains("rm ") || script_content.contains(">") || script_content.contains("tee ")) {
                return Err("Security violation: script attempts out-of-sandbox modifications to restricted system directories");
            }
        }
        Ok(true)
    }
}

impl Default for SovereignSandboxEnforcer {
    fn default() -> Self {
        Self::new()
    }
}

/// Advanced Debian package delta compiler (calculates minimal upgrade diffs)
pub struct SovereignDeltaGenerator;

impl SovereignDeltaGenerator {
    pub fn generate_binary_delta(&self, old: &[u8], new: &[u8]) -> Vec<u8> {
        let mut delta = Vec::new();
        // Simplified binary diff (in production use bsdiff/xdelta)
        let min_len = std::cmp::min(old.len(), new.len());
        for i in 0..min_len {
            if old[i] != new[i] {
                delta.push(new[i]);
            }
        }
        if new.len() > old.len() {
            delta.extend_from_slice(&new[min_len..]);
        }
        delta
    }
}

// ==========================================
// 5. Debian-style update-alternatives Subsystem
// ==========================================

#[derive(Debug, Clone)]
pub struct AlternativeOption {
    pub path: String,
    pub priority: i32,
}

#[derive(Debug, Clone)]
pub struct AlternativeGroup {
    pub link_name: String,
    pub options: Vec<AlternativeOption>,
    pub manual_selection: Option<String>,
}

pub struct SovereignAlternativesSystem {
    pub groups: HashMap<String, AlternativeGroup>,
}

impl SovereignAlternativesSystem {
    pub fn new() -> Self {
        Self {
            groups: HashMap::new(),
        }
    }

    pub fn register_alternative(&mut self, group: &str, link: &str, path: &str, priority: i32) {
        let entry = self.groups.entry(group.to_string()).or_insert_with(|| AlternativeGroup {
            link_name: link.to_string(),
            options: Vec::new(),
            manual_selection: None,
        });
        entry.options.push(AlternativeOption {
            path: path.to_string(),
            priority,
        });
    }

    pub fn set_manual_override(&mut self, group: &str, target_path: &str) -> Result<(), &'static str> {
        let entry = self.groups.get_mut(group).ok_or("Alternatives group not found")?;
        let exists = entry.options.iter().any(|o| o.path == target_path);
        if !exists {
            return Err("Target path not registered in alternatives group");
        }
        entry.manual_selection = Some(target_path.to_string());
        Ok(())
    }

    pub fn set_auto_mode(&mut self, group: &str) -> Result<(), &'static str> {
        let entry = self.groups.get_mut(group).ok_or("Alternatives group not found")?;
        entry.manual_selection = None;
        Ok(())
    }

    /// Resolves the current target command link based on update-alternatives rules
    pub fn resolve_link(&self, group: &str) -> Option<String> {
        let entry = self.groups.get(group)?;
        if let Some(ref manual) = entry.manual_selection {
            Some(manual.clone())
        } else {
            // Auto Mode: Select the highest priority registered alternative option
            entry.options.iter()
                .max_by_key(|o| o.priority)
                .map(|o| o.path.clone())
        }
    }
}

impl Default for SovereignAlternativesSystem {
    fn default() -> Self {
        Self::new()
    }
}

// ==========================================
// 6. APT preferences Pinning Engine
// ==========================================

#[derive(Debug, Clone)]
pub struct PinPreferenceRule {
    pub package_pattern: String,
    pub pin_release: String,
    pub priority: i32,
}

pub struct AptPinningResolver {
    pub preferences: Vec<PinPreferenceRule>,
}

impl AptPinningResolver {
    pub fn new() -> Self {
        Self {
            preferences: Vec::new(),
        }
    }

    pub fn add_pin_rule(&mut self, pattern: &str, release: &str, priority: i32) {
        self.preferences.push(PinPreferenceRule {
            package_pattern: pattern.to_string(),
            pin_release: release.to_string(),
            priority,
        });
    }

    /// Evaluates the highest priority candidate package version according to APT Pin-Priority rules
    pub fn resolve_pinned_version(
        &self,
        package_name: &str,
        candidates: &[(String, String)], // list of (version_str, release_source)
    ) -> Option<String> {
        if candidates.is_empty() {
            return None;
        }

        // Sort candidates by custom computed APT priority weights
        let mut best_version: Option<String> = None;
        let mut max_priority = -1;

        for (version, release) in candidates {
            let mut priority = 500; // Standard candidate default priority in APT

            for rule in &self.preferences {
                let matches_pkg = rule.package_pattern == "*" || rule.package_pattern == package_name;
                let matches_release = rule.pin_release == release;
                if matches_pkg && matches_release {
                    priority = rule.priority;
                }
            }

            if priority > max_priority {
                max_priority = priority;
                best_version = Some(version.clone());
            }
        }

        best_version
    }
}

impl Default for AptPinningResolver {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mirror_selection() {
        let mut selector = SovereignMirrorSelector::new();
        selector.register_mirror("http://debian.org/stable", 50, 100);
        selector.register_mirror("http://us.debian.org/stable", 10, 1000); // Optimal

        let best = selector.select_best_mirror().unwrap();
        assert_eq!(best.url, "http://us.debian.org/stable");

        let sources = selector.generate_sources_list("bookworm").unwrap();
        assert!(sources.contains("deb http://us.debian.org/stable bookworm"));
    }

    #[test]
    fn test_dpkg_transaction_safety() {
        let mut manager = SovereignTransactionManager::new();
        manager.register_package("bash", Version::new(5, 1, 0));
        manager.register_package("nano", Version::new(7, 2, 0));

        // Start install transaction
        manager.begin_transaction().unwrap();
        assert_eq!(manager.status, TransactionStatus::Committing);

        // Simulate installing newer nano
        manager.register_package("nano", Version::new(7, 3, 0));

        // Rollback on failure
        manager.rollback_transaction().unwrap();
        assert_eq!(manager.status, TransactionStatus::RolledBack);
        assert_eq!(manager.active_packages.get("nano").unwrap(), &Version::new(7, 2, 0)); // Rolled back
    }

    #[test]
    fn test_maintainer_scripts_sandbox() {
        let enforcer = SovereignSandboxEnforcer::new();

        // Safe script
        let safe = "echo 'configuring package...'";
        assert!(enforcer.audit_maintainer_script(safe).is_ok());

        // Insecure script
        let malicious = "echo 'payload' > /etc/shadow";
        assert!(enforcer.audit_maintainer_script(malicious).is_err());
    }

    #[test]
    fn test_binary_deltas() {
        let generator = SovereignDeltaGenerator;
        let old = b"hello old world";
        let new = b"hello new world";
        let delta = generator.generate_binary_delta(old, new);
        assert!(!delta.is_empty());
    }

    #[test]
    fn test_alternatives_resolutions() {
        let mut system = SovereignAlternativesSystem::new();

        // Register vi with priority 20 and nano with priority 40
        system.register_alternative("editor", "/usr/bin/editor", "/usr/bin/vi", 20);
        system.register_alternative("editor", "/usr/bin/editor", "/usr/bin/nano", 40);

        // Auto mode should resolve to highest priority (nano)
        assert_eq!(system.resolve_link("editor").unwrap(), "/usr/bin/nano");

        // Set manual override to vi
        system.set_manual_override("editor", "/usr/bin/vi").unwrap();
        assert_eq!(system.resolve_link("editor").unwrap(), "/usr/bin/vi");

        // Reset to auto mode
        system.set_auto_mode("editor").unwrap();
        assert_eq!(system.resolve_link("editor").unwrap(), "/usr/bin/nano");
    }

    #[test]
    fn test_apt_pinning_preferences() {
        let mut resolver = AptPinningResolver::new();

        let candidates = vec![
            ("1.0.0".to_string(), "stable".to_string()),
            ("2.0.0-unstable".to_string(), "unstable".to_string()),
        ];

        // Default resolves to unstable if no rules are present (due to position, or custom logic)
        // Let's add a pinning rule to explicitly pin stable release to priority 990
        resolver.add_pin_rule("*", "stable", 990);
        resolver.add_pin_rule("*", "unstable", 100);

        let chosen = resolver.resolve_pinned_version("nginx", &candidates).unwrap();
        assert_eq!(chosen, "1.0.0");
    }
}
